dags/main_summary.py
The job is expected to take 3-4 hours, but was intermittently
timing out at 6 hours. Increase to 10 hours while profiling and
debugging the job.
=> Increase timeout to 10 hours (temporarily).

README.md, ansible/envs/stage.yml
This affects all jobs via the location of the airflow.sh script, but
in particular, it also moves the output location for the
`main_summary.py` and `crash_aggregates.py` jobs.
New jobs should be tested by explicitly writing to the test bucket.
=> Move data output to the telemetry-parquet bucket.

ansible/deploy_aws.yml, ansible/deploy_local.yml
By default the scheduler runs forever. Apparently this causes it
to get jammed up periodically, and the recommended practice is to
restart the scheduler frequently. This change sets the scheduler
to exit after 5 runs. Docker should take care of restarting it for
us.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/22)
=> Bug 1286825: Set num_runs for scheduler.

ansible/provision_aws.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/27)
=> Reaper should spare ECS instances.

ansible/files/airflow/airflow.cfg, dags/main_summary.py
Set the max number of active runs so we don't overwhelm the system,
and rewind the start date by a couple of days to test that the
scheduler does the right thing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/30)
=> Bug 1275889 - Prepare "Main Summary" job for backfill

dags/mobile_clients.py
The mobile_clients task is timing out after 2h, let's try to increase it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/33)
=> Increase mobile_clients execution timeout

dags/backfill_main_summary.py
Dags do not automatically detect changes to start date and
schedule their own backfill. Using the airflow cli does not
appear to respect the concurrency settings. This change
introduces a new DAG that just does the backfill for the
main_summary v3 dataset.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/39)
=> Bug 1275889 - Add a dummy dag for backfill

.gitignore, ansible/deploy_aws.yml, ansible/deploy_local.yml, ansible/envs/dev.yml, ansible/envs/stage.yml, ansible/files/docker-compose.yml, dags/operators/emr_spark_operator.py
As we want to support multiple versions of Spark we have to allow users
to configure the EMR release they want their tasks to run in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/41)
=> EMR release version should be configurable

dags/longitudinal.py, jobs/addon_recommender.sh, jobs/client_count_view.sh, jobs/crash_aggregate_view.sh, jobs/longitudinal_view.sh, jobs/main_summary_view.sh
This patch will ensure that Scala jobs use the latest available
version of telemetry-batch-view written for Spark 1.6. This is needed as
the master branch of telemetry-batch-view is going to be based on Spark 2.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/42)
=> Force Scala jobs to use Spark 1.6

ansible/files/spark/airflow.sh
The PYSPARK_DRIVER_PYTHON inherited by the environment is jupyter by
default, so we need to revert it to plain python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/50)
=> Bug 1306558 - Don't use jupyter to run .py files

dags/main_summary.py
Handle the increased timeout to flush data to S3, ensuring that all
data is available for the previous day when we process main pings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/52)
=> Bug 1304662 - Increase main_summary delay to 1hr

dags/bugzilla_dataset.py, dags/crash_aggregates.py, dags/crash_aggregates_backfill.py, dags/example.py, dags/telemetry_aggregates.py
Not sure how I should be testing these, but the dags are kicking off fine locally so it looks like the timeouts are being parsed correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/55)
=> Bug 1286249: Add timeouts to jobs without them

dags/longitudinal.py, dags/utils/constants.py
This hasn't been tested on an actual run, but the rendered output on each of the tasks looks correct:
Note that this means if we trigger a manual run of the DAG, the date passed will be current_date + 7 days since there's no way to override execution date in that command.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/56)
=> Bug 1290146 - Change date param to end of the week in longitudinal tasks

dags/utils/constants.py
The weekly date fix from last week should have added 6 days, not 7. Tested and working on dev.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/58)
=> Bug 1310715 - Weekly date param should add 6 days to execution date

ansible/files/airflow/airflow.cfg
This fixes the issue of dev deployments accidentally launching clusters for elapsed jobs -- all new DAGs will now start off by default and must be explicitly turned on when ready.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/57)
=> Bug 1310486 - Default dags_are_paused_at_creation to True in airflow config

ansible/deploy_aws.yml, ansible/deploy_local.yml, ansible/provision_aws.yml
Local paths in playbooks are now relative to the playbook location, not where the playbook is run from in ansible 2.1.2.0
After we merge these changes, everyone will need to update their ansible versions locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/60)
=> Bug 1309352 - Update all local paths in ansible playbooks for ansible 2.1.2.0

dags/main_summary.py
Reading from main_summary is a lot more efficient than reading the
raw data. 3 instances should be plenty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/68)
=> Reduce the number of instances for Addons

dags/churn.py
This schedules the weekly job for generating the desktop churn/retention dataset.
This has been tested with the following command:
`> ansible-playbook ansible/deploy_local.yml -e '@ansible/envs/dev.yml' -e "command='test churn churn 20161221'"`
r? @Dexterp37
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/77)
=> Bug 1304503 - Port the churn report job to Airflow

ansible/files/docker-compose.yml, dags/debug.py, dags/operators/sleep_operator.py
- Adds a few debugging dags and an operator that I found useful while working on this issue
- Raises memory limits to 4 GB on the worker and the scheduler
I wasn't actually able to reproduce the error locally (just a bunch of the Broken Pipe errors that we apparently get all the time, not just when we get zombie tasks). Nonetheless, it's clear we're running up against the memory limits on these machines when we're running at max concurrency and this is a quick and easy change -- the ECS machine has 30GB of memory so we're far from hitting actual resource limits. I just checked and the scheduler container is at just over 1 GB of memory with 3 concurrent tasks, and I was able to max out 2GB on the worker locally so I think it makes sense to raise the limit for both the worker and scheduler. …
=> Bug 1321424 - Raise memory limits

dags/main_summary.py, dags/sync_log.py, dags/sync_view.py
Schedule the sync_log job to run daily (after a 1-hour timeout to wait for all data to arrive).
I am running a test right now, will update when it completes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/80)
=> Bug 1291340 - Add sync log import DAG

dags/main_summary.py, jobs/main_events_view.sh
Landed this job last week in telemetry-batch-view and am now getting around to adding it to the daily main_summary dag (I'll run the backfill by hand through whenever this lands)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/87)
=> Add events job to main_summary dag

jobs/telemetry_aggregator.py
The changes to telemetry.sh moves anaconda from /home/hadoop to /mnt.
Tested this and it works. @vitillo r?
=> Change ipython location for telemetry aggregator

jobs/client_count_view.sh
The legacy memory management mode doesn't work properly in Spark 2.0.2
and causes ClientCountView to crash when creating a DataFrame of the
main_summary table.
=> Fix ClientCountView crash triggered by Spark 2.0.2

dags/telemetry_aggregates.py, dags/telemetry_aggregates_fennec_backfill.py
Note: this PR depends on #90 & mozilla/python_mozaggregator#42.
https://bugzilla.mozilla.org/show_bug.cgi?id=1344020.
=> Use default EMR release for telemetry_aggregates

jobs/longitudinal_view.sh
The legacy memory management mode doesn't work properly in Spark
2.0.2 and causes LongitudinalView to crash.
=> Fix LongitudinalView crash triggered by Spark 2.0.2

dags/churn.py
[Bug 1345217 - [Churn] Separate csv uploads to s3 from churn job](https://bugzilla.mozilla.org/show_bug.cgi?id=1345217)
This job runs downstream of churn, generating csv files from the churn parquet data. The source notebook was added to [mozilla-reports](https://github.com/mozilla/mozilla-reports/pull/36) this week.
=> Bug 1345217 - Add churn_to_csv downstream from churn

ansible/files/spark/airflow.sh
This will prevent an error in case the kernel indicated in the notebook
is not available on the EMR machine.
=> Override the kernel used for ipynb jobs with the python2 one

dags/longitudinal.py
The repo was recently named from firefox-hardware-survey to
firefox-hardware-report. This commit updates the URL of the
summarize_json.ipynb file accordingly.
=> Update URL of summarize_json.ipynb

dags/churn.py
This uses `ds_nodash` to set the execution date to the date that the job is scheduled on.
=> Bug 1350380 - Use ds_nodash instead of DS_WEEKLY for churn

jobs/longitudinal_view.sh
Requires https://github.com/mozilla/emr-bootstrap-spark/pull/79.
I verified that steps run via EMRSparkOperator inherit the environment variables added in the bootstrap script.
=> Bug 1355153 - Run parquet2hive after longitudinal generation

dags/topline.py, jobs/topline_summary_view.sh
This commit adds monthly and weekly topline summary generation to airflow. The current reporting uses periods compatible with airflow's `@weekly`and `@monthly` shortcuts.
=> Bug 1357877 - [part 1] Add ToplineSummaryView

dags/txp_pulse.py
Looks like I added an errant 'r' when appending to my previous commit. Did a local deploy offline to make sure there weren't any other silly errors.
=> Remove errant character in txp_pulse

dags/topline.py
This increases the number of nodes for monthly topline summary to 20 nodes, which is 4x the capacity of the weekly job. This job would fail before, but now takes 1.75 hours to complete (j-3OTVLPM4P9DH6 is the cluster used for testing).
=> Increase nodes for monthly ToplineSummary to 20

dags/churn.py, jobs/churn.sh
This schedules churn from mozetl instead of mozilla-reports. See [cluster details of the test run](https://us-west-2.console.aws.amazon.com/elasticmapreduce/home?region=us-west-2#cluster-details:j-1IY45MWS4RJS5) for reference. The test job is still running as of this comment.
=> Bug 1361113 - Use churn from mozetl instead of mozilla-reports

dags/main_summary.py
Adds the revamped Test Pilot Mau Dau job to Airflow -- tested spinning up the job from local dev and it started running the job fine (failed as expected on a missing path in telemetry-test-bucket.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/116)
=> Add Test Pilot MAU DAU task

dags/main_summary.py, jobs/search_rollups.sh
[Bug 1364530 - Migrate Search ETL job to python_mozetl](https://bugzilla.mozilla.org/show_bug.cgi?id=1364530)
This schedules the search ETL from mozetl instead of the gist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/117)
=> Bug 1364530 - Use search rollup from mozetl instead of gist

dags/topline.py, jobs/topline_dashboard.sh
[Bug 1357877 - Add `ToplineSummary` and `topline_dashboard` to Airflow](https://bugzilla.mozilla.org/show_bug.cgi?id=1357877)
This adds the mozetl topline_dashboard script as a dependency of the topline summary. The PR for fixing toLocalIterator issues with timeouts should be addressed before this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/114)
=> Bug 1329844 - Add topline dashboard generator

dags/sync_view.py
Cut the number of nodes in the cluster from ten to five.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/113)
=> Bug 1309881: Use fewer nodes to run sync_view job

dags/core_client_count.py, jobs/core_client_count_view.sh
Tested this in `telemetry-test-bucket`. Test table is in STMO already (`core_client_count` table).
=> Add core client count job

jobs/client_count_view.sh
Noticed this as I was investigating the failures.
Used submission_date previously, which is not a partitioned col.
This should speed up the job a bit. Note that GenericCountView
uses submission_date_s3 as the default, so we can just remove
the argument altogether.
=> Use submission_date_s3 col for client_count

jobs/search_rollups.sh
This fixes launch errors from things like arrow in search_rollups
```
Traceback (most recent call last):
File "/mnt/analyses/python_mozetl/run.py", line 1, in <module>
from mozetl.search import search_rollups as sr; sr.main()
File "/mnt/analyses/python_mozetl/mozetl/search/search_rollups.py", line 13, in <module>
import arrow
ImportError: No module named arrow
```
=> Install dependencies for mozetl

jobs/search_rollups.sh
The order of arguments into the search rollup is wrong.
```
Successfully installed arrow-0.10.0 mozetl
Usage: run.py [OPTIONS] START_DATE MODE BUCKET PREFIX
Error: Invalid value for "mode": invalid choice: 20170628. (choose from daily, monthly)
```
=> Fix argument order for search rollup

jobs/topline_summary_view.sh
This schedules the `mozetl` version of `topline_summary`, which is significantly improved from the old version.
=> Schedule `python_mozetl/topline/topline_summary`

jobs/topline_summary_view.sh
The version number is [appended to the prefix in the topline_summary job](https://github.com/mozilla/python_mozetl/blob/master/mozetl/topline/topline_summary.py#L252), so this should be removed to be in the correct location.
=> Remove extraneous version number from topline prefix

dags/main_summary.py
``` Broken DAG: [/app/dags/main_summary.py] invalid syntax (main_summary.py, line 34) ``` showed up on the stage instance.
=> Fix syntax error in main_summary dag

dags/main_summary.py
[Bug 1380173 - Reduce daily_search_rollup instance count to 1](https://bugzilla.mozilla.org/show_bug.cgi?id=1380173)
This reduces the size of the job from 10 nodes to 1 node. The job takes 51 minutes to run on a single node.
=> Bug 1380173 - Reduce daily_search_rollup instance count to 1

jobs/hardware_report.sh
This ensures the dependencies are also installed.
I'll be able to test this once https://github.com/mozilla/python_mozetl/pull/85 is submitted.
=> Install mozetl before running hardware report

dags/main_summary.py
This is needed otherwise, due to bug [SPARK-12837] in Spark < 2.2.0,
broadcasting during a join will result with an OOM error like: "Total
size of serialized results of XXX is bigger than
spark.driver.maxResultSize (YYY GB)"
=> Make the HBase Addon Recommender job use EMR 5.8.0

dags/main_summary.py, dags/search_rollup.py
This adds daily and monthly search rollups as seperate dags that depend on `main_summary` using the `ExternalTaskSensor`. This lets us match up dags running at different frequencies.
=> Bug 1365580 - Create separate dag for daily and monthly search rollup

dags/main_summary.py, dags/search_rollup.py
This removes the `ExternalTaskSensor` and makes the `search_rollup` job depend
on concrete instances of a job. The daily job will depend on the
`main_summary` dag, while the monthly job will run on the 2nd of the
month.
=> Bug 1397048 - Embed search_rollups directly into dags

jobs/client_count_view.sh
We're averaging around 70GB per run these days, so increase from
the default of 32 partitions to 250 to bring file size back into
the "sweet spot" of 200-300MB.
=> Reduce parquet file size for client_count

Makefile, README.md, dags/main_summary.py
This also addresses #155, at least for the `main_summary` DAG.
This needs to land after [the associated PR over in python_mozetl](https://github.com/mozilla/python_mozetl/pull/128), and I need to test this first, so please hold off on reviewing.
=> Bug 1401655 - Run clients_daily and experiments_daily

dags/churn.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1404502)
`churn_v3` adds `new_profile_ping_parquet` as a source for first session clients. I'd like to schedule `churn_v2` in parallel to compare the differences. This uses the `MOZETL_GIT_BRANCH` variable to pass the branch of the pinned v2 code.
Below is an excerpt from [`make run COMMAND="test churn churn 20170910"` logs](https://us-west-2.console.aws.amazon.com/elasticmapreduce/home?region=us-west-2#cluster-details:j-16U3037M03L2B)
```
+ MOZETL_ARGS=churn
+ MOZETL_GIT_PATH=https://github.com/mozilla/python_mozetl.git
+ MOZETL_GIT_BRANCH=churn-v2
+ MOZETL_SPARK_MASTER=yarn
+ unset PYSPARK_DRIVER_PYTHON
++ mktemp -d -t tmp.XXXXXXXXXX
+ workdir=/tmp/tmp.IONh4V2GiY
```
=> Bug 1404502 - Pin churn_v2 to `python_mozetl/churn-v2` branch

dags/main_summary.py
The experiment aggregates job timed out at least once over the weekend -- it looks like some of the recent spark improvements included EMR 5.8.0 benefit the experiment aggregates job so I'm opting for this instead of upping the number of machines right now.
=> Use EMR 5.8.0 for experiment aggregates job

dags/utils/mozetl.py
Hyphens are not allowed in environment variable names, so this
prevents names with hyphens being properly passed through to
mozetl tasks.
=> Replace hyphens w/ underscores in mozetl env vars

dags/main_summary.py, dags/operators/emr_spark_operator.py, jobs/retention.sh
This schedules the job using a slack of 4 days and 13 bits for the HLL
object. This corresponds to the observation of 99% of client activity
with roughly a 1% standard error introduced HLL.
This job shares components in mozetl and in telemetry-batch-view, so
there is a custom job script to launch. This script also accepts
arguments from the command-line can be useful for backfill.
=> Bug 1381840 - Schedule 1-Day Firefox Retention

jobs/core_client_count_view.sh
This moves from a static year sanitation to a programmatically
determined one from the current year, allowing for edge
boundaries of Dec 31 and Jan 1 (where the year can be the
previous or the next).
Tested on Presto.
=> Bug 1415602 - Make date sanitation correct for future year boundaries

dags/main_summary.py
Running with 100 nodes didn't make much difference in run time, so
switch back to 25. We were getting fairly close to the 10-hour
timeout, so increase that as well.
=> Reduce instances, increase timeout.

jobs/experiment_aggregates_view.sh
I'm working on profiling the job a bit to see where it'd be best to apply effort but for now we should make sure there's up-to-date data in the viewer
=> Temporarily disable scalar bootstrapping in experiment aggregates view

README.md
Adding status badge for circleci build.  This should be an indicator that the dags/*.py files are compiling successfully in master.  
This becomes important because we will soon have airflow sync the dags folder from master every 10 minutes, rather than having to redeploy wtmo every time we want a change to dags.
=> Adding status badge for circleci build

dags/search_rollup.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1422876)
The airflow job for monthly search rollups times out at 4 hours. This bumps the number of nodes from 3 to 10.
=> Bug 1422876 - Bump workers for monthly search rollup

dags/main_summary.py
Looks like the timeouts are just the job growing over time into the timeout limit. Probably worth double-checking to make sure we're dropping clients out of the dataset after 28 days without activity, but this will get the job running until @fbertsch gets back and can take a closer look.
=> Increase heavy users view timeout

dags/operators/emr_spark_operator.py
Bumps the default EMR version to 5.9.0, which I believe has been the default version on ATMO for a while. EMR greater than 5.8.0 contains the application history log for free. 
Here's a cluster run: [link](https://us-west-2.console.aws.amazon.com/elasticmapreduce/home?region=us-west-2#cluster-details:j-2050NFW5OFQD9)
=> Bump default emr release to 5.9.0

dags/churn.py
This swaps the job from rtmo to python_mozetl.
=> Bug 1355990 - Port churn_to_csv to python_etl

dags/main_summary.py
Using the new ETL code for V2 of the addon_aggregates dataset which just merged with `python_mozetl` via [this PR](https://github.com/mozilla/python_mozetl/pull/187).
=> Update addon_aggregates specs

dags/main_summary_backfill.py
It's nearly showtime!
Of note: I changed the max_active_runs to 10 so we should run 10 weeks of backfill at a time. At that rate I'm estimating the whole year's backfill will take ~6 days.
Do not merge until the last backfill PR is merged in tbv
=> Add main summary backfill DAG

dags/main_summary_backfill_mar_2018.py, plugins/celery_visibility_timeout_fix.py
This PR does two things:
- Set the celery visiblity_timeout to 6 hours, up from the default 1 hour which was causing our step sensors to fail (https://stackoverflow.com/questions/44274381/airflow-long-running-task-in-subdag-marked-as-failed-after-an-hour)
- Serialize each day's step in airflow to run one after the other, in which case sensors should not run past the new 6 hour limit
Setting the visibility_timeout to a higher limit has the downside of slower reaction times when a worker has failed and a task should be requeued. This isn't a very common event, and setting it to 6 hours (vs 1 day, which apparently some people do to work around this airflow issue) seems like a good compromise.
=> Bug 1445646: Fix Sensor Timeouts in Main Summary Backfill

Dockerfile.dev
I can't run `make build` on osx for testing dags without this
=> Fix `make build` on osx

dags/main_summary_backfill_mar_2018.py, plugins/moz_emr/moz_emr_mixin.py
3 small changes here:
- Up the parallelism on the backfill to 4 DAGs at once
- Make cluster termination dependent on every main summary day completing successfully (which allows us to selectively re-run days and have the cluster auto-terminate on completion)
- actually use the `action_on_failure` param for job steps
=> Backfill tweaks

jobs/probe_scraper.sh
This reverts commit d7c8526571c1e625c507cef4cc68bf34a57f4458.
public-read is set on the bucket but this only allows List permissions. We need the public-read at the object level.
=> Revert "Remove public-read object ACL since this is set on the bucket"

dags/longitudinal.py
Let's just hope we don't keep this around much longer...
Note this already ran on 40 machines successfully, and the data already exists for 20180324.
=> Bug 1449249 - Increase number of longitudinal machines to 40

dags/taar_amodump.py
This adds a new DAG responsible for uploading a JSON file of AMO data for consumption by TAAR.
Also see: https://github.com/mozilla/python_mozetl/pull/207
=> Add a new DAG to upload AMO JSON for TAAR

dags/mango_log_processing.py
I've configured on_retry_callback to clear the dag state when EmrJobFlowSensor tasks fails. I've tested this and it seems to work as expected and maintains the correct retry counter in the EmrJobFlowSensor task.
r?
=> Configure on_retry_callback to clear dag status on failure Bug 1451000

dags/first_shutdown_summary.py, dags/taar_amodump.py
This schedules the TAAR AMO whitelist ETL job.  This job is strictly dependant on `taar_amodump` completing.
=> Add taar_whitelist to the taar_amodump DAG

jobs/client_count_daily_view.sh
Tested this for `submission_date=20180211` and ran DatasetComparator with all columns except hll and bucketed_uri_count to get:
```
=======================================================================================
BEGINNING JOB dataset_comparator FOR 20180211
Wrong number of rows. Expected 830493. Got 2055911
Wrong number of null values in 'devtools_toolbox_opened'. Expected 740186. Got 1888523
Wrong number of null values in 'top_distribution_id'. Expected 651182. Got 1644546
FAILURE ON JOB dataset_comparator FOR 20180211
=======================================================================================
```
Indicating the same set of distinct value combinations for pre-existing non-hll columns, and a ~2.5 times increase in number of rows due to the new column. increase in …
=> Bug 1434991 - Add total_uri_count_threshold to client_count_daily

dags/main_summary.py, dags/search_rollup.py
[Bug Link](https://bugzilla.mozilla.org/show_bug.cgi?id=1456549)
The search rollup job has been failing intermittently over the last few weeks. I left out some key arguments in the DAG definition that prevented the intended email recipients from getting the retry alerts. I've also bumped up the instance count and timeout value.
=> Bug 1456549 - Fix search rollup timeout and increase instance count

dags/events_to_amplitude.py, jobs/events_to_amplitude.sh
This also means the bash script is no longer specific for
focus_android, so that part of the filename has been dropped.
Depends on https://github.com/mozilla/telemetry-streaming/pull/128
=> Read events_to_amplitude config file from JAR

dags/taar_amodump.py
The taar_lite job is currently timing out in airflow as we do not have enough workers or time to complete the job.  This just bumps the instance count to 5 and extends the runtime to 2 hours which should be more than sufficient to execute the job.
=> Added more workers and extended runtime for taar_lite job

dags/taar_amodump.py
The submission method should be 'spark' to run the taar_lite job correctly.
I've also bumped up the time out period to 4 hours as we've seen the job run up to 2 hours with a 4 node ATMO cluster.
=> Incorrect submission type fix for the taar_lite job

dags/longitudinal.py
I can start the guidranking job from my shell using the test command:
```
(py27) victorng@Victors-MacBook-Pro-2  ~/dev/telemetry-airflow   features/taarlite_guidranking_dag ●  make run COMMAND="test longitudinal taar_lite_guidranking 20180505"
docker-compose run -e AWS_SECRET_ACCESS_KEY -e AWS_ACCESS_KEY_ID web airflow test longitudinal taar_lite_guidranking 20180505
Starting telemetry-airflow_db_1    ... done
Starting telemetry-airflow_redis_1 ... done
Starting telemetry-airflow_app_1   ... done
Waiting for db to listen on 5432...
Waiting for redis to listen on 6379...
/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install …
```
=> Added taar_lite_guidranking to the longitudinal DAG

dags/main_summary.py
As described in the bug, it looks like it's normal operation for the glue job to take longer on days with schema changes.
=> Bug 1465082: Up main_summary_glue timeout to 8 hours

Dockerfile.dev, README.md, airflow.cfg, dags/debug.py
I set the `catchup_by_default` configuration variable to False via the Dockerfile.dev environment. When I tried this last year, it wasn't working for me.
I tested this by rerunning `make build` and  setting the start date of the debug DAG to 3 days ago. When true, it started to run the tasks from the start date. When set false, it only ran the most recent day. I also tried this on `churn`, and it correctly ran only the most recent Wednesday. 
Also, I documented a workaround for Linux users where the user id causes permission errors with the mounted volume.
=> Prevent backfill by default on local Airflow instance

Dockerfile, Dockerfile.dev
For local development, it's likely that you might want to
iterate on values of environment variables, leading to long
Docker builds. By keeping the expensive installation of libs
at the top of the Dockerfile, we can keep those layers cached
allowing quick builds when changing environment variables.
=> Move Dockerfile ENV commands after lib installation

jobs/telemetry_aggregator.py
Adapts to the envvar-based creds needed since https://github.com/mozilla/python_mozaggregator/pull/63
The new credentials file has been uploaded to S3 and I've tested that _preparedb() returns successfully with this code on an ATMO cluster.
=> Bug 1467860 - Load database creds from S3 for aggregator job

dags/longitudinal.py
This PR adds :vng and :mlopatka to the failure notification list for the TAAR job. It additionally marks mlopatka as the owner of the TAAR jobs.
CC @crankycoder and @mlopatka
=> Reflect the current status of TAAR modules ownership

dags/events_to_amplitude.py, dags/fx_usage_report.py, dags/longitudinal.py, dags/main_summary.py, dags/operators/emr_spark_operator.py, plugins/moz_emr/moz_emr_mixin.py
[Bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1462810)
This PR contains a patch for bumping [EMR to 5.13.0](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-release-5x.html), which is the first version with support for [Spark 2.3.0](https://spark.apache.org/releases/spark-release-2-3-0.html).
@jklukas recently ran the Airflow dag against most of the jobs. I'm going to run the jobs against the new version. There shouldn't be any errors because the Spark release is backwards compatible.
=> Bug 1462810 - Bump default EMR version to 5.13.0 for Spark 2.3.0

dags/events_to_amplitude.py
Checked in local airflow dev and the url seems correct
=> Bug 1471368: Pin events to amplitude to older release for now

dags/event_ping_events.py, dags/utils/tbv.py
Scheduling the event ping events dataset from mozilla/telemetry-streaming#149 (tested locally and everything worked fine, and the urls for telemetry-batch-view jobs seem to be fine)
=> Add Event Ping Events dataset job

dags/main_summary.py, jobs/client_count_daily_view.sh, jobs/retention.sh
This PR fixes most of the issues found in #316 ([bug mirror](https://bugzilla.mozilla.org/show_bug.cgi?id=1476047)). 
One side-effect of these changes is that downstream jobs require some data in `telemetry-test-bucket/main_summary/v4` before running, instead of relying on the latest main_summary data.
=> Bug 1476047 - Use correct buckets for `main_summary` dependencies when running in dev

dags/socorro_import.py
There seems to be new intermittent issues with the crash report import job. I just closed a [related bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1477001) where an bump to 10 nodes let the job complete. 
```
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 1.0 failed 4 times, most recent failure: Lost task 3.3 in stage 1.0 (TID 7243, ip-172-31-3-156.us-west-2.compute.internal, executor 5): ExecutorLostFailure (executor 5 exited caused by one of the running tasks) Reason: Container marked as failed: container_1532995648738_0001_01_000006 on host: ip-172-31-3-156.us-west-2.compute.internal. Exit status: 137. Diagnostics: Container killed on request. Exit code is 137
Container exited with a non-zero exit code 137
Killed by external signal …
```
=> Bump socorro_import to 10 nodes

jobs/telemetry_batch_view.py
Previously, there were no logs about which artifact
was being used. That made it hard to debug problems.
This change will make it obvious which JAR is being
used to run a job.
=> Bug 1479580 - Log which JAR is being used in telemetry-batch-view

dags/main_summary.py
This just reverts commit 4c0477f4 to enable the Dynamo data loader job for TAARv3
=> Re-enable taar-dynamo job for TAARv3

README.md, dags/main_summary.py
I updated the README to reflect the current state of testing in Airflow. It's not required to edit the DAG in order to run a full test of `main_summary`.
This also updates the experiment_aggregates job to use 3 nodes in dev.
=> Update instructions for running the main_summary DAG

jobs/telemetry_aggregator.py
Also drop release since these are filtered out later in the job anyway.
=> Aggregate Dev Edition (bug 1476323)

dags/events_to_amplitude.py
The Savant study is complete and no new data has been flowing for several days.
Any future backfills of this data can be accomplished via STMO.
=> Remove savant_events_to_amplitude

dags/events_to_amplitude.py
Last night's run of the devtools job timed out, which is somewhat expected since we're now pulling in beta pings
=> Increase number of devtools instances to correspond with channel bump

dags/events_to_amplitude.py, dags/operators/emr_spark_operator.py
There are a few atomic commits here:
- One adds an "Environment" tag to the cluster to match the tag on ATMO clusters (so that we get a Environment tag on the metrics sent to datadog)
- One adds a bootstrap_args param to EMRSparkOperator
- One sets bootstrap_args to enable datadog metrics for events_to_amplitude
I ran this locally and watched metrics flow all the way to Datadog:
The HttpSink metrics appear as `spark.driver.HttpSink.success.count`, etc.
=> Bug 1465974 Enable metrics for events_to_amplitude clusters

bin/mozetl_runner.py, dags/landfill.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1490099)
This adds the landfill sampler introduced in mozilla/python_mozetl#232 to airflow as it's own DAG. This is currently blocked by mozilla/python_mozetl#254 and [bug 1484334](https://bugzilla.mozilla.org/show_bug.cgi?id=1484334).
This job will eventually have 2 downstream dependencies:
1. A job for creating a tar.gz artifact with the json blobs in the same file-structure as mozilla-pipeline-schemas
2. A job for running the edge-validator and submitting the report to generic ingestion
=> Bug 1490099 - Add landfill sampler

.circleci/config.yml, Makefile, dags/example.py, dags/utils/status.py, plugins/statuspage/__init__.py, plugins/statuspage/client.py, plugins/statuspage/dataset_client.py, plugins/statuspage/hook.py, plugins/statuspage/operator.py, plugins/statuspage/schema.py, plugins/statuspage/statuspage_client.py, requirements.txt, tests/test_dag_utils_status.py, tests/test_dataset_status_hook.py, tests/test_dataset_status_operator.py, tox.ini
This adds [Statuspage](https://firefoxoperations.statuspage.io/) support for datasets through a `DatasetStatusOperator`. This is a first pass that will be tested against `MainSummary`.
There are a suite of unit-tests that cover the hook, operator, and utility function. The client library has been tested by hand.
To manually test the `example_statuspage` dag:
1. `make build && make up`
2. Create a new connection `statuspage_default` and put the statuspage api key in the password field
3. Enable the `example_statuspage` dag
4. Manually run each job in order.
5. In the statuspage component page
- watch the status for the correct behavior
- delete the "Test Airflow Integration" component
=> Bug 1502235 - Add a statuspage operator to telemetry-airflow plugins

dags/main_summary.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1498231)
This registers MainSummaryView failures with statuspage. If there does happen to be a failure, then someone will need to go into the statuspage management page and turn it back to operational after fixing it. This creates a component for the dataset, so incidents can be filed even if the node in the DAG doesn't trigger.
The second half of the bug will end up being a query from redash using email to alert on the dataset status outside of airflow.
=> Bug 1498231 - Register MainSummaryView with Statuspage

dags/socorro_import.py
[buglink](https://bugzilla.mozilla.org/show_bug.cgi?id=1506252)
This renames `socorro_import` to `crash_reports_parquet`. The dag name and the resulting dataset name are still `socorro_import`. The registered name will be "Socorro Crash Reports Parquet" on statuspage.
[Bug 1498228](https://bugzilla.mozilla.org/show_bug.cgi?id=1498228) is blocking.
=> Bug 1506252 - Register socorro crash reports with Statuspage

dags/events_to_amplitude.py
PR Part 1: update the current job to specify prerelease-only
=> Switch devtools prerelease amplitude job to new config schema name

dags/events_to_amplitude.py, jobs/telemetry_batch_view.py
Adding the devtools release events to amplitude job sampled at 50% to the dag -- the other events to amplitude jobs use a custom job script but I've made the changes needed to use the generic tbv job script instead. I'll start with the new release job using the generic runner and move the rest of the jobs next week after this has run for a few days (and when it's not all-hands :))
=> Bug 1505583: Use tbv_envvar for devtools release e2a job

dags/events_to_amplitude.py
Very last PR for this task – now that telemetry-streaming#190 is merged in, we can use the master artifact for this job
=> Use master artifact for events to amplitude devtools release channel job

dags/main_summary.py
The recent 2 days ran in 2.3 hours.
=> Decrease timeout for Main Summary on Databricks

dags/prerelease_telemetry_aggregates.py, dags/release_telemetry_aggregates.py
Previously, telemetry aggregates were part of the same DAG. However,
they are not dependent on one another; so when one fails, the other
eventually stops running (due to an airflow).
This is not the behavior we want -  we want the other to run when
one is failing. This way they are totally independent on the other
one running.
=> Bug 1517013 - Separate telemetry aggregates

dags/main_summary.py
Job works fine with smaller driver, this will make it a little cheaper.
=> Configure driver type in taar_similarity

dags/utils/status.py, tests/test_dag_utils_status.py
Currently, if a dataset is registered using `register_status`, the component is only added after it's first failure. This fixes issue #397 by adding another operator that runs `get_or_create` after a dataset is generated.
=> Fix `register_status` to update statuspage

dags/main_summary.py
This adds `clients_daily_v6` to the set of Datasets that are visible via Statuspage. This should be merged after #398, which should create a new component automatically after the first run.
=> Register Clients Daily with statuspage

dags/mango_log_processing.py
For the meantime to get this working I have it showing up in the "Data Engineering Datasets" section since the group is currently hard-coded in the Statuspage plugin, I've got a WIP branch locally I'd like to put up a PR for but I figure this is a much smaller change and it gets the job into Statuspage sooner.
=> Add amo_mango_log_processing to statuspage

dags/dataset_alerts.py
This adds clients_daily to the dataset_alerts dag. The schedule_interval is updated to run 4 hours after the start of the main_summary DAG, with the sensor running every 30 minutes for another 4 hours.
=> Add Clients Daily to the dataset_alerts dag

plugins/statuspage/dataset_client.py, plugins/statuspage/schema.py, plugins/statuspage/statuspage_client.py, tests/test_dataset_status_client.py
This adds support for the Statuspage `/pages/{page_id}/incidents` api endpoint. The DatasetStatusHook wraps this in `create_incident_investigation`.
This can be used to create or modify existing operators.
=> Create incidents within DatasetStatusHook

dags/dataset_alerts.py, plugins/s3fs_check_success.py, tests/test_s3fs_check_success_operator.py, tox.ini
This PR adds an operator version of a sensor written in #395. This works in the same way as the `S3FSCheckSuccessSensor`, except it is not a long lived job.
I noticed a few things when watching the sensor last night.
* The sensor worked as expected during a catch-up backfill when other jobs were not being run
* The sensor would fail when it ran into unexpected partitions (the `__HIVE_DEFAULT_PARTITION__` of #404)
* The sensor timed out during the run for `2019-01-07`. The logs show that the poke method was never called during the lifetime of the sensor.
- This might be caused by the low concurrency limit, where the pokes are treated as a low-priority and is never given a chance to run.
In light of this, I've disabled the `dataset_alerts` DAG. Instead of using a long-lived sensor, I think …
=> Add an operator to check for _SUCCESS files

dags/dataset_alerts.py, plugins/s3fs_check_success.py
Sensors are not part of the plugin API in airflow 1.9, which is why the module doesn't exist. 
https://github.com/apache/airflow/blob/a592e732356427b4fd1ed27c890cf82e9cf495f0/airflow/plugins_manager.py#L115-L125
=> fixup! Add sensor-plugins to operators

dags/dataset_alerts.py, plugins/statuspage/operator.py, tests/test_dataset_status_operator.py
This is a two part commit that adds an option to automate the creation of Statuspage incidents from the `DatasetStatusOperator`. This will likely be used in the `dataset_alerts` DAG to notify on data that will be late.
=>  Add create_incident flag to DatasetStatusOperator 

plugins/databricks/__init__.py, plugins/databricks/databricks_hook.py, plugins/databricks/databricks_operator.py, tests/test_databricks_hook.py, tests/test_databricks_operator.py
This backports patches made to the Databricks hook and operator as a separately maintained plugin. We should be able to access the operator like any other plugin. We can modify the `MozDatabricksRunSubmitOperator` to use the plugin instead of the one from within the tree.
The backport process was a 3 part process (broken down by commit).
1. Copy the relevant files from https://github.com/apache/airflow/tree/v1-10-stable
2. Fix the imports and mocks to reference the plugins directory e.g. `plugins.databricks.databricks_hook` instead of `airflow.contrib.hooks.databricks_hook`.
3. Export the plugin in the module initialization.
Other than the minor fixes entailed in step 2, the tests and backported functionality should be plug and play.
=> Backport Databricks hook and operator from apache/airflow:v1-10-stable

plugins/databricks/databricks_operator.py
Airflow is running on python 2, so relative imports are not valid syntax. This uses the relative module path.
=> Fix relative import in Databricks plugin

plugins/moz_databricks.py
Reverts mozilla/telemetry-airflow#421
```
Broken DAG: [/home/airflow/gcs/dags/main_summary.py] Use keyword arguments when initializing operators
Broken DAG: [/home/airflow/gcs/dags/landfill.py] Use keyword arguments when initializing operators
Broken DAG: [/home/airflow/gcs/dags/longitudinal.py] Use keyword arguments when initializing operators 
```
=> Revert "Increase databricks retries and retry delay to avoid api errors"

dags/spinner_severity_generator.py
This moves tab spinner job to Databricks.
Test run(succeeded): https://dbc-caf9527b-e073.cloud.databricks.com/#job/1299/run/1
=> Run tab spinner job on Databricks

plugins/moz_databricks.py, tests/test_moz_databricks_operator.py, tox.ini
This is the corrected version of PR #421, which was missing a keyword argument for `json`. This time around, I've added unit tests and tested the operator locally.
=> Increase databricks retries and retry delay to avoid api errors

jobs/probe_scraper.sh
We need Python 3.7 for the `glean_parser`, and also then the probe-scraper. I don't think I want to make these changes for everyone though.
=> Use Miniconda for Py 3.7

bin/run
Since we're moving this to GKE, the container wont need newrelic
=> Remove newrelic from container for running in GKE

plugins/moz_databricks.py, tests/test_moz_databricks_operator.py
This will run mozetl jobs on Python 3 by default on databricks clusters. [This page](https://docs.databricks.com/api/latest/examples.html#python-3-example) shows how to create a new cluster with python 3 set as the default.
This also modifies the test so the json payload can be inspected and values can be asserted.
=> Add python3 support to moz_databricks and set it to default

plugins/moz_databricks.py
The tab_spinner job in mozetl is breaking all of the jobs in python 3 due to an import error. This will prevent the landfill job and the taar jobs from failing over the weekend.
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<command--1> in <module>()
13 
14 with open(filename, "rb") as f:
---> 15   exec(f.read())
16 
<string> in <module>()
/databricks/python/lib/python3.5/site-packages/mozetl/cli.py in <module>()
11 from mozetl.search.aggregates import search_aggregates_click, search_clients_daily_click
12 from mozetl.sync import bookmark_validation
---> 13 from mozetl.tab_spinner import tab_spinner
14 from mozetl.taar import (
15     taar_locale, …
```
=> [hotfix] Set default python version to 2

plugins/moz_databricks.py
Reverts mozilla/telemetry-airflow#441. The py3 import errors are fixed with mozilla/python_mozetl#319, which adds a `test_cli_import` that should prevent this from happening again.
=> Revert "[hotfix] Set default python version to 2"

dags/churn.py, plugins/moz_databricks.py, tests/test_moz_databricks_operator.py
This adds support for `MOZETL_GIT_PATH` and `MOZETL_GIT_BRANCH`, which is used in the `churn_v2` job. These arguments are documented within the `mozetl-submit.sh` script:
https://github.com/mozilla/python_mozetl/blob/6991b5c9be0c0a916f5e2d5abc6c35e8f19f57ca/bin/mozetl-submit.sh#L12-L13
This PR is based on #432, and adds cases on the modified test suite.
=>  Fix #433 - Add support for alternative git path and branch in mozetl jobs

dags/longitudinal.py, dags/main_summary.py
This migrates the TAAR collaborative model generation from the longitudinal DAG to main_summary.
This changes depends on https://github.com/mozilla/telemetry-batch-view/pull/518
=> Migrate the TAAR collaborative recommender job 

Dockerfile, Dockerfile.dev
`gcloud` is required to retrieve Kubernates credentials in the GKEPodOperator.
=> Add google-cloud-sdk

dags/operators/gcp_container_operator.py
CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE is needed to specify service account overrides via the gcloud utility. It is currently used by the GKEPodOperator to fetch cluster credentials.
=> Add GKEPodOperator that uses `CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE`

dags/churn.py, dags/crash_summary.py, dags/fxa_events.py, dags/main_summary.py, dags/socorro_import.py, dags/sql/clients_last_seen_v1.sql, dags/sql/firefox_accounts_exact_mau28_raw_v1.sql, dags/sql/firefox_desktop_exact_mau28_by_dimensions_v1.sql, dags/sql/fxa_auth_bounce_events_v1.sql, dags/sql/fxa_auth_events_v1.sql, dags/sql/fxa_content_events_v1.sql, dags/sql/fxa_users_daily_v1.sql, dags/sql/fxa_users_last_seen_v1.sql, dags/sync_view.py, dags/utils/gcp.py
Now that https://github.com/mozilla/telemetry-airflow/pull/467 https://github.com/mozilla/telemetry-airflow/pull/469 we can revert https://github.com/mozilla/telemetry-airflow/pull/468.
I've merged down the dag task commits and broke out the actual subdag into it's own commit to make it easier.
=> Add load_to_bigquery and migrate tasks from cloud composer.

dags/first_shutdown_summary.py
I missed this in my PR (https://github.com/mozilla/telemetry-airflow/pull/470). r?
=> Add load_to_bigquery for first_shutdown_summary DAG

dags/main_summary.py
In the current configuration, I think the clients_daily query
is going to end up missing new records for the day because it
runs immediately after the EMR job for clients_daily, not waiting
for the data to load to BQ.
=> Make clients_last_seen dependent on clients_daily_v6_bq_load

dags/main_summary.py
Our parquet HLL tables don't actually work with the bigquery HLL functions, and this one is now deprecated, so we should stop loading it into bigquery.
=> Remove client count daily bigquery load

dags/direct2parquet_bigquery_load.py
Since we aren't setting the default to anything useful. This was missed as part of https://github.com/mozilla/telemetry-airflow/pull/482
r?
=> Set bigquery_conn_id to override default

dags/fxa_events.py
There was a [failure this morning](https://workflow.telemetry.mozilla.org/log?execution_date=2019-04-25T10%3A00%3A00%2B00%3A00&task_id=fxa_auth_events&dag_id=fxa_events):
> Invalid schema update. Cannot add fields (field: jsonPayload.fields.flowid)
The source table in the fxa project had a field added. Allowing field addition
as part of the job should make us robust to future schema changes on the fxa
side.
=> Allow field addition in fxa load jobs

dags/utils/gcp.py
[Observed failure](https://workflow.telemetry.mozilla.org/log?task_id=core_clients_daily&dag_id=direct2parquet_bigquery_load&execution_date=2019-05-14T02%3A00%3A00%2B00%3A00):
> /app/script/entrypoint: line 31: sql/core_clients_daily_v1$20190514.sql: No such file or directory
=> Fix regression in building SQL file names for queries

dags/bgbb.py
This fixes a typo I made in #437 that caused various failures last night. 
```
Airflow alert: <TaskInstance: bgbb_fit.bgbb_fit 2019-04-01T08:00:00+00:00 [up_for_retry]>
Airflow alert: <TaskInstance: main_summary.bgbb_pred 2019-05-16T01:00:00+00:00 [failed]>
```
Since the `bgbb_fit` job failed, there were no parameters for the `bgbb_pred` job. I could turn off the fit DAG, but the pred task is coupled to main_summary. Sorry about the extra noise.
=> Fix ds_next to next_ds

dags/main_summary.py
Moves the experiments job to databricks, which, with spot instances, autoscaling, and faster machines for the same price, seems like it'd be a net win while also fixing issues with highly variable volume in experiments.
Dev seems pretty broken right now so I wasn't able to test this entirely :/ Experiments are already currently broken anyway, though, so I feel like even though it's a Friday and I'm generally not for this, it might be worth it to merge this in today if you get a chance to review this before EOD
=> Use Databricks w autoscaling for experiments dataset

jobs/probe_scraper.sh
The only question is which bucket to use, currently it's `telemetry-airflow`. @jasonthomas, is this acceptable?
Long-term we'll switch this all to GCP, but this is a short-term fix.
=> Bug 1549695 - Sync probe-scraper cache to s3

dags/probe_scraper.py
It looks like I should have followed the suggestion in https://github.com/mozilla/telemetry-airflow/pull/523.
=> Set image_pull_policy explicitly for mozilla-schema-generator

dags/bgbb.py, dags/main_summary.py
This adds the v1 the path prefixes for discoverability.
```
$ aws s3 ls s3://telemetry-test-bucket/bgbb/ --recursive
...
2019-06-03 13:43:20     729214 bgbb/active_profiles/v1/submission_date_s3=2019-05-02/sample_id=1/part-00197-tid-6186755752760602289-685d6747-1c59-4bf7-896f-f7080ac7d077-5199.c000.snappy.parquet
2019-06-03 13:43:20     724770 bgbb/active_profiles/v1/submission_date_s3=2019-05-02/sample_id=1/part-00198-tid-6186755752760602289-685d6747-1c59-4bf7-896f-f7080ac7d077-5200.c000.snappy.parquet
2019-06-03 13:43:20     741741 bgbb/active_profiles/v1/submission_date_s3=2019-05-02/sample_id=1/part-00199-tid-6186755752760602289-685d6747-1c59-4bf7-896f-f7080ac7d077-5201.c000.snappy.parquet
2019-06-03 13:16:35          0 bgbb/params/v1/submission_date_s3=2019-05-01/_SUCCESS
2019-06-03 …
```
=> Add version string to bgbb paths

dags/bgbb.py
95% of MAU is covered by users seen in the past 90 days, so this should keep most of the signal while reducing job time and query run times.
=> decrementing model window to 90 days

dags/probe_scraper.py
This updates the schema generator job with the interface exposed in mozilla/mozilla-schema-generator#37.
=> Update environment variables in schema generator

dags/crash_summary.py
Essentially using the same configuration as we do for "main summary
all histograms", with a lower max instance size.
=> Use databricks to run crash summary

dags/direct2parquet_bigquery_load.py
Schedules the new queries in
https://github.com/mozilla/bigquery-etl/pull/207
This is placed in the direct2parquet DAG because downstream
ETL depends on both these new tables and the existing core
ping direct2parquet line.
=> Add glean daily ETL to the direct2parquet DAG

dags/crash_summary.py
It seems like this job does not benefit from using more than one machine,
so let's just use one and save some costs.
=> Use only one node for crash summary

docker-compose.yml
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1564937)
This adds dummy credentials to prevent the broken dag message when running the airflow server locally.
=> Bug 1564937 - Add dummy prio credentials

dags/bq_events_to_amplitude.py
Currently, the job overwrites a table to run; this
means if multiple run in parallel, they may export the
wrong data.
=> Only allow one run of bq-amplitude export at a time

dags/taar_weekly.py
The TAAR similarity job points to an invalid databricks airflow runner.  The fileextension should be `.py`, not `.sh`
=> Bug: 1566623 The TAAR Ensemble airflow job points to an invalid filename

dags/taar_weekly.py
The start_date parameter has a bad default causing regularly scheduled runs to fail.  The changes the string to a datetime type for the taar ensemble run operator.
=> Bug 1566623 - Fix the start_date parameter in the taar_weekly DAG

dags/taar_weekly.py
Oops.  We actually do need the start_date parameter in the taar_ensemble task.
=> Bug: 1566623 - taar_ensemble job needs a start_date parameter

dags/events_to_amplitude.py
I added a bunch of new events to the devtools -> amplitude job yesterday (telemetry-streaming#250) and it looks like the increase in the number of events has led to the job timing out. As a short-term fix, I'm increasing the parallelism for the job 2x, with the hope we can switch to amplitude's csv import sooner than later.
=> Fix devtools prerelease timeouts

dags/utils/gcp.py
Fixes bug introduced in #569 that lead to some failures this morning like:
/app/script/entrypoint: line 31: sql/telemetry_derived/clients_last_seen_v1$20190730.sql: No such file or directory
=> Build sql_file_path before appending date to destination_table

jobs/fx_usage_report.sh
Reference: https://pandas.pydata.org/pandas-docs/stable/install.html#plan-for-dropping-python-2-7
=> Use py2 compatible pandas

jobs/fx_usage_report.sh
Pandas requires numpy>=1.12, so it tries to install numpy 1.17, which is Python 3 only. numpy 1.16.* supports Python 2, and is the latest one to do so.
=> Pin numpy version

jobs/fx_usage_report.sh
The previous iteration still ran into the bug. We now don't allow the pandas install to install anything but pandas.
```
Downloading 's3://telemetry-airflow/steps/airflow.sh' to '/mnt/var/lib/hadoop/steps/s-EYEFR58IMN5Q/.'
Collecting py4j
Downloading https://files.pythonhosted.org/packages/04/de/2d314a921ef4c20b283e1de94e0780273678caac901564df06b948e4ba9b/py4j-0.10.8.1-py2.py3-none-any.whl (196kB)
Installing collected packages: py4j
Found existing installation: py4j 0.10.7
Uninstalling py4j-0.10.7:
Successfully uninstalled py4j-0.10.7
Successfully installed py4j-0.10.8.1
Collecting numpy==1.16.4
Downloading https://files.pythonhosted.org/packages/1f/c7/198496417c9c2f6226616cff7dedf2115a4f4d0276613bab842ec8ac1e23/numpy-1.16.4-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
Installing collected …
```
=> Manually install all pandas deps

dags/sync_view.py
For https://bugzilla.mozilla.org/show_bug.cgi?id=1578581.
Backfill performed and available in `moz-fx-data-derivied-datasets.telemetry_derived.sync_bmk_total_per_day_v1`
=> Add task to load sync_bmk_total_per_day to BigQuery

dags/direct2parquet_bigquery_load.py, dags/fxa_events.py, dags/kpi_dashboard.py, dags/main_summary.py
https://github.com/mozilla/telemetry-airflow/pull/602 didn't work as expected
since the airflow user doesn't have permissions to create jobs in the
shared-prod project. This should allow the job to be in derived-datasets,
but write into shared-prod.
=> Bug: fully qualify destination table with project name

dags/direct2parquet_bigquery_load.py
Currently, these wait tasks aren't completing. I believe it's due to the 1 hour
difference between the DAG schedules.
See https://github.com/mozilla/telemetry-airflow/pull/595#discussion_r322336248
=> Add execution_delta to wait for copy_deduplicate

dags/direct2parquet_bigquery_load.py
Needed until Airflow supports running queries in shared-prod.
=> Fully qualify paths for fenix daily queries

dags/main_summary.py
The job will save results to tables in a `search_staging` dataset for testing purposes.  Let me know if there is already a designated dataset for testing.
Related to https://github.com/mozilla/bigquery-etl/pull/381
=> Add bigquery search dataset queries

dags/fx_usage_report.py, dags/main_summary.py, dags/utils/dataproc.py, dataproc_bootstrap/fx_usage_init.sh, jobs/fx_usage_report.sh
Notes:
This job originally read main_summary from s3://telemetry-parquet in the AWS Dev account and wrote data to s3://net-mozaws-prod-us-west-2-data-public in the AWS Prod account which is hosted by cloudfront.
This job now reads parquet data from GCS and still writes to the same location in s3.  When the spark/bigquery main summary access has been resolved, we can modify this job to read from bq.
Currently a few YAUs are slightly higher for dataproc on gcs parquet data. This is not a KPI so we will leave it at that.
TODO -
=> Migrate Fx usage report from emr to dataproc

dags/main_summary.py
I believe as part of https://github.com/mozilla/telemetry-airflow/pull/559 the experiments bigquery table schema was modified which included a field type change for `sample_id` from `STRING` to `INT64` however we did not update the task to replace the field as part of the import which is causing the BigQuery data load to fail.
r?
=> Replace sample_id with type integer for bigquery experiments load

dags/update_orphaning_dashboard_etl.py, dags/utils/dataproc.py, jobs/update_orphaning_dashboard_etl.py
This adds update-orphaning ETL job adapted from the original notebook[1].
Core logic remains unchanged, there is a BigQuery shim code
(`longitudinal_shim_aggregate` and `longitudinal_shim_transform`) added to
maintain compatibility with legacy Longitudinal schema.
I have verified this job's output [2] against original one scheduled from ATMO [3] - there's pretty good match, differences in calculated metrics do not exceed 0.2%.
[1] https://github.com/mozilla/mozilla-reports/blob/80c9bd6468877e1df1f48208c7c99266bedb9896/projects/app_update_out_of_date.kp/orig_src/app_update_out_of_date.ipynb
[2] s3://telemetry-public-analysis-2/app-update-test/data/out-of-date/20191006.json
[3] s3://telemetry-public-analysis-2/app-update/data/out-of-date/20191006.json
=> Bug 1577460 - add BigQuery-based update orphaning ETL script

dags/adi_by_region.py
The way it was before only works when the dag runs on time. If back filling it doesn't work.
=> Fix adi by region dates

dags/direct2parquet_bigquery_load.py, dags/fxa_events.py, dags/kpi_dashboard.py, dags/main_summary.py
GUD now uses the v2 tables and the v1 tables are no longer needed.
=> Remove smoot_usage_v1 queries

dags/prio/processor.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1592737)
The prio_processor dag is currently blocked on 2019-10-25 because of an issue with large rows in `payload_bytes_decoded`. The dag was originally set with a `depends_on_past` condition because multiple dags would run at the same time. The job is currently stateful because it reuses fixed kubernetes clusters and storage bucket between runs for intermediate results.
If the Airflow FAQ is accurate, and the observation on the local run of 2019-10-28 and 2019-10-29 holds in production, then this should probably do the right thing and run a single date at a time.
=>  Bug 1592737 - Remove depends_on_past condition

dags/direct2parquet_bigquery_load.py, dags/fxa_events.py, dags/kpi_dashboard.py, dags/main_summary.py
This is now possible due to updates to permissions such that Airflow can
now run BQ jobs in shared-prod.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1582791
Thank you, @jasonthomas. This is going to avoid some significant hassles esp. for the GLAM queries that are coming up.
=> Run queries in shared-prod for destination tables in shared-prod

bin/run, plugins/moz_databricks.py
This fixes all of the broken DAGs in the local environment.
1. This adds dummy extra values for both GCP and AWS
2. This lists out all of the necessary GCP and AWS connection strings
3. This moves the mozetl runner generation from the operator initization to the operator execution
I ran the `system_check` DAG to verify that mozetl jobs still work (which currently only runs on Databricks).
https://dbc-caf9527b-e073.cloud.databricks.com/#setting/sparkui/1031-232337-gimpy15/driver-logs
```
Out[1]: '\n# This runner has been auto-generated from mozilla/telemetry-airflow/plugins/moz_databricks.py.\n# Any changes made to the runner file may be over-written on subsequent runs.\nfrom mozetl import cli\n\ntry:\n    cli.entry_point(auto_envvar_prefix="MOZETL")\nexcept SystemExit:\n    # avoid …
```
=> Bug 1593149 - Fix broken DAGs in local Airflow environment

dags/utils/gcp.py
the parquet import and the parquet export were using the same cluster name, which is a problem for main summary and clients daily
=> Fix dataproc cluster name collision

dags/main_summary.py
This was used by a dashboard at
https://metrics.services.mozilla.com/firefox-dashboard/
which has been decommissioned per [Bug 1571454](https://bugzilla.mozilla.org/show_bug.cgi?id=1571454).
=> Remove the "engagement_ratio" task.

dags/main_summary.py, dags/operators/gcs_to_s3.py, dags/utils/gcp.py
Disable XCOM in GoogleCloudStorageToS3Operator to prevent too large
value error.
Include static partitions in export_prefix so that we don't copy all
history every day.
r=me
=> Fix export_to_parquet gcs_to_s3 step

dags/operators/gcs_to_s3.py, dags/operators/moz_gcs_to_s3.py, dags/utils/gcp.py
This forks the upstream gcs to s3 operator to add support for distributing tasks to a `ThreadPool`.
Without this it took 48 minutes to copy 12.8 GiB for clients_daily.
r=me
cc @akkomar
=> Use thread pool to copy from gcs to s3

dags/hardware_report.py
Dataproc job names cannot contain whitespaces.
=> Fix Hardware Report job name

dags/main_summary.py
[the default subdag executor was changed in airflow 1.10](
https://github.com/apache/airflow/blob/v1-10-stable/UPDATING.md#default-executor-for-subdagoperator-is-changed-to-sequentialexecutor) so that subdags are limited to one executor. 
The reason they did this was because it was possible for a subdag to consume all the executors such that top level dags couldn't run.
The reason we should allow these subdags to run in parallel is that the main summary parquet export subdag can save about 20 minutes by running `avro_delete` and `gcs_to_s3` in parallel, and these subdags only have a max of two tasks that would be running in parallel.
=> Use default executor for parquet export subdags

dags/ssl_ratios.py
now reads `main` (populated by copy_dedup) rather than `main_summary` as of https://github.com/mozilla/bigquery-etl/pull/502
=> Update upstream for ssl_ratios

dags/main_summary.py
There was a failure last night:
> org.apache.spark.sql.catalyst.parser.ParseException:
> extraneous input '<EOF>' expecting {')', ','}(line 1, pos 546)
And it points to the line starting "TRANSFORM(active_addons..."
Looks like we're just missing a closing paren. cc @relud
=> Bugfix for clients_daily_export

dags/direct2parquet_bigquery_load.py, dags/fxa_events.py, dags/kpi_dashboard.py, dags/main_summary.py
At the request of Skyline dashboard stakeholders.
This seemed preferable to adding these folks to the `telemetry-alerts@mozilla.com` firehose.
=> Add Skyline dashboard stakeholder emails to KPI-relevant tasks

dags/mozaggregator_mobile.py
This is necessary to deploy https://github.com/mozilla/python_mozaggregator/pull/201. Having this partitioning scheme will make it easier to validate the data and keep it around.
For reference, the command line arguments are as follows:
https://github.com/mozilla/python_mozaggregator/blob/35bb1c0a0d1051e0662d6169eaa5d2387995e278/mozaggregator/cli.py#L125-L143
=> Bump mobile_metrics dataset to v3 with submission_date based partitioning

dags/mozaggregator_mobile.py, dags/mozaggregator_prerelease.py, dags/utils/dataproc.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1596242)
This has been tested locally. This should be safe to deploy since it is running parallel with the existing job. This will be used to validate whether the aggregates are correct relative to the moztelemetry version. 
Job output: https://console.cloud.google.com/dataproc/jobs/mobile_aggregates_0be053f4?organizationId=442341870013&project=amiyaguchi-dev&region=global
```
mobile_aggregates_0be053f4
Start time
Nov 15, 2019, 3:31:28 PM
Elapsed time
35 min 8 sec
Status
Line wrapping
Equivalent command line
WARNING: python_moztelemetry will stop working *VERY SOON* (if it hasn't stopped working already)
Please see this post to fx-data-dev for more information: https://mail.mozilla.org/pipermail/fx-data-dev/2019-November/000291.html …
```
=> Bug 1596242 - Migrate mobile_aggregate_view to GCP

dags/utils/gcp.py
this is used by 4 tables: `main_summary`, `clients_daily`, `clients_last_seen`, `firefox_desktop_exact_mau28_by_dimensions`. None of them conflict with s3->gcs jobs, which also use `moz-fx-data-derived-datasets-parquet`.
to test permissions I plan to rerun the export of `firefox_desktop_exact_mau28_by_dimensions` for yesterday, because it's the smallest.
=> Don't use tmp bucket for export_to_parquet

dags/error_aggregates.py
More than one update per work day will make mission control more usable and monitorable.  Cost isn't an issue (~15 cents per query).
=> Increase error agg dag frequency to 3 hours

jobs/bgbb_runner.py
This was missing from #765. This runner is necessary for the job to start, and is referenced in https://github.com/mozilla/telemetry-airflow/blob/master/dags/bgbb.py#L94
=> Add missing bgbb_runner

dags/bgbb.py, dags/main_summary.py
This turns off the the aws jobs and modifies the bigquery load job to skip loading from aws. This can be merged in once there has been a successful airflow of the predict job.
=> Bug 1596205 - Turn off AWS bgbb (active_profiles) jobs

jobs/update_orphaning_dashboard_etl.py
This removes usage of `main_1pct_backfill` table which is no longer
needed after main ping table has been backfilled.
This also adds a filter for `build.version` being not null. Such pings
should not be included in this analysis (we had a single ping having
this field empty in the last year).
=> Use only main ping view in update orphaning ETL

dags/bq_events_to_amplitude.py, dags/events_to_amplitude.py
~This is the next step after https://github.com/mozilla/telemetry-airflow/pull/759~
This moves mobile products' views to generic Amplitude ingestion.
=> Bug 1574490 - Migrate mobile products to generic Amplitude ingestion

dags/copy_deduplicate.py, dags/main_summary.py
These are added as helpers for rewriting old queries that used
the HLL-based "client_count" datasets. Using this data makes
them faster and cheaper than using the "last_seen" tables
directly.
=> Schedule the exact_mau by client count dims queries

dags/copy_deduplicate.py, dags/fxa_events.py, dags/main_summary.py, dags/utils/forecasting.py
Depends on https://github.com/mozilla/forecasting/pull/10
We aren't going to start relying on these "productionized" forecasts until beginning of 2020, so for now nothing depends on the forecast tasks and we leave the kpi_dashboard dag alone.
=> Add tasks for running simpleprophet forecasts

dags/utils/tbv.py, jobs/telemetry_batch_view.py
Since we're removing the parquet data tomorrow there's no need to keep updating the metastore.
=> Remove references to metastore from TBV

bin/run, dags/attitudes_daily.py
I've already added these variables to the prod Airflow instance so this should be good to go – the dag will get filled out with a few more steps when those queries are ready
=> Bug 1583947: Add initial attitudes daily dag

dags/utils/dataproc.py
related prs
- https://github.com/mozilla/telemetry-airflow/pull/809 (blocked by this one)
- https://github.com/mozilla-services/cloudops-infra/pull/1575 (infra to create NATs, whitelists, etc.)
To specify NAT'd cluster with access to the gcp postgres, use these args here in your moz_*_runner subdags:
zone='us-west2-a',
subnetwork_uri='default',
internal_ip_only=True
=> Add functionality to create dataproc clusters with outgoing traffic via NAT 

dags/operators/bq_sensor.py
The current super(...) call goes one class too far in the hierarchy, so we
never initialize the timeout param in BaseSensorOperator.
Currently, these waiting tasks only work correctly if the target is ready the
first time it's checked. If it's not ready, an exception is thrown rather
than going into a loop for waiting.
In practice, we see the amplitude wait tasks fail twice and then usually succeed
on the third try, only because the query is finally ready by then.
=> Fix initialization of timeout param in bq_sensor

dags/clean_pods.py, dags/probe_scraper.py
Gke has a pod limit of 1k. Old finished GKEPodOperator runs count towards this limit and must be cleaned
related https://github.com/mozilla-services/cloudops-infra/pull/1720
=> Cleans out old GKE pods

dags/mozaggregator_mobile.py
The job currently fails with the the following error:
```
[2020-01-02 20:56:42,515] {logging_mixin.py:95} INFO - [2020-01-02 20:56:42,514] {pod_launcher.py:181} INFO - Event with job id export-mobile-metrics-avro-37e155bc Failed
[2020-01-02 20:56:42,596] {logging_mixin.py:95} INFO - [2020-01-02 20:56:42,595] {pod_launcher.py:104} INFO -   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
[2020-01-02 20:56:42,596] {logging_mixin.py:95} INFO - [2020-01-02 20:56:42,596] {pod_launcher.py:104} INFO -     return self.load_wsgiapp()
[2020-01-02 20:56:42,598] {logging_mixin.py:95} INFO - [2020-01-02 20:56:42,598] {pod_launcher.py:104} INFO -   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
[2020-01-02 …
```
=> Set entrypoint in mozilla/python_mozaggregator image to bash

dags/mozaggregator_mobile.py
```
Exception:
Google DataProc job has state: ERROR: Job failed with message [Error: no such option: --source]. Additional details can be found at 'https://console.cloud.google.com/dataproc/jobs/mobile_aggregates_d36ecb8e?project=airflow-dataproc®ion=global'.
```
Operations are evaluated left to right. I had intended this to be something like `[1] + [2] if False else [3] == [1,3]`, but instead I got `[3]`.
=> mobile_aggregates - Add parenthesis to ensure proper evaluation order

dags/mozaggregator_mobile.py
```
Running job for 20200102
Traceback (most recent call last):
File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o52.load.
: org.apache.spark.sql.AnalysisException: Failed to find data source: avro. Avro is built-in but external data source module since Spark 2.4. Please deploy the application as per the deployment section of "Apache Avro Data Source Guide".;
at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:647)
```
https://console.cloud.google.com/dataproc/jobs/mobile_aggregates_5f7fd77a?project=airflow-dataproc&region=global
This PR adds the relevant …
=> Mobile aggregates - Fix "org.apache.spark.sql.AnalysisException: Failed to find data source: avro"

dags/mozaggregator_mobile.py, dags/mozaggregator_prerelease.py
This PR exports the saved_session ping for prerelease aggregates. This also adds an additional namespace to the path so the mobile aggregates and prerelease aggregates can run without interference of each other.
=> Add saved_session export for mozaggregator_prerelease

dags/operators/gcp_container_operator.py
Suggesting we default `image_pull_policy` to `Always`. This is a major footgun for existing GKE jobs; we would expect `latest` to always pull (per kubernetes), but that doesn't seem to be the case if `image_pull_policy` isn't set correctly.
=> Default GKE to always pull images

dags/main_summary.py
Planning on increasing the global configuration core.max_active_runs_per_dag for all dags. So I'm explicitly setting main summary's configuration to what it is currently
=> Setting main summary max active dag runs explicitly

dags/main_summary.py, dags/utils/dataproc.py, jobs/taar_dynamo.py
* added options for master and worker disk type and size
* dataproc should really be operated with only pd-ssd disk types and >
1TB drives.
* added explicit 10 retry configuration for boto3+dynamodb
* added custom exponential backoff around the batch write
as boto3 does not seem to backoff quite enough
=> GCP port of taar-dynamo

dags/probe_scraper.py, dags/utils/gcp.py, dags/utils/leanplum.py
We are now default to "Always" for image_pull_policy,
so there's no reason to add that again to every util.
=> Remove unnecessary image_pull_policy params

dags/main_summary.py
should help the catchup of clients_last_seen move faster. Our cluster is relatively underutilized since migrating off EMRSparkOperator/etc
=> increasing max runs for main summary

dags/taar_daily.py
Previously, ExternalTaskSensor tasks were blocked waiting for main summary run from midnight. This fixes them by scheduling the whole dag at 1am.
=> Update daily TAAR DAG schedule

dags/attitudes_daily.py, dags/copy_deduplicate.py, dags/main_summary.py
Cleanup of dangling references to the `templates` directory (which caused some failing jobs over the weekend) as a follow-up to mozilla/bigquery-etl#723
=> Update python script locations from templates/ to sql/ directory

dags/taar_daily.py
I thought the owner is notified about failures but turns out vng is not in the recipient list of failure emails :man_shrugging:
=> Add vng to email notifications list for taar_daily DAG

dags/document_sample.py
The errors table is now available for airflow and CI to run queries on. The document sample DAG fails because of the default partitioning set in the `bigquery_etl_query` function. This table does not need partitioning set, since no no two runs will be the same and the query takes into account the timestamp of the run.
https://github.com/mozilla/telemetry-airflow/blob/757bc75c2068652ae758ad69d5e881ae3e1792a6/dags/utils/gcp.py#L443-L458
Error with existing table:
```
[2020-02-19 00:35:19,149] {logging_mixin.py:95} INFO - [2020-02-19 00:35:19,149] {pod_launcher.py:104} INFO - BigQuery error in query operation: Error processing job 'moz-fx-data-shared-
[2020-02-19 00:35:19,150] {logging_mixin.py:95} INFO - [2020-02-19 00:35:19,150] {pod_launcher.py:104} INFO - …
```
=> Update document sample for appends

dags/bq_events_to_amplitude.py, dags/prio/processor.py
when schedule_interval is used as a task parameter rather than a dag parameter
=> Remove some dag warnings

dags/glam.py, dags/glam_subdags/histograms.py
In my local tests, this seemed to allow tasks to run concurrently in a subdag.
=> Use default executor to run tasks in parallel in SubDags.

dags/main_summary.py
Deprecating this job per https://mail.mozilla.org/pipermail/fx-data-dev/2020-February/000318.html
=> Remove experiments_v1 tasks from main summary dag

dags/copy_deduplicate.py, dags/fxa_events.py, dags/kpi_dashboard.py, dags/main_summary.py
There was a group of folks involved with KPI reporting in 2019 who no longer need to be alerted about failures in these tasks.
=> Remove outdated emails

dags/fxa_events.py
Closes https://github.com/mozilla/bigquery-etl/issues/785
This should get us unstuck without having to change anything in bigquery-etl.
The fxa_oauth_events_v1 table in shared-prod will continue to exist, but just
won't receive any more updates.
I will follow up with a bigquery-etl PR to add commentary that marks the
query as deprecated.
=> Remove fxa_oauth_events query

dags/glam.py, dags/glam_subdags/daily_aggregates.py
This PR is mainly doing 2 things:
1. All clients daily processing now generates the sql queries on the fly that it needs before running them. This means that new probes added would be included daily (https://github.com/mozilla/bigquery-etl/issues/760).
2. Factors out `clients_daily_*` tasks into scalar and histogram subdags
=> Factor out clients_daily_* as subdags and generate these queries daily.

dags/glam_org_mozilla_fenix.py
This sets the connection id back to the derived dataset connection id, in order to fix #872.
=> Use default service account for glam_org_mozila_fenix dag

dags/utils/gke.py
This fixes #891. When tested locally, the DAG now fails in a new location.
=> Fix #891 - Use snake_cased cluster definition to match protobuf

dags/pensieve.py
Currently, the dependencies look like this:
This PR fixes this by correctly setting multiple upstream tasks as dependencies
=> Fix upstream dependencies for pensieve

dags/main_summary.py
With this change and https://github.com/mozilla/telemetry-airflow/pull/889 we will no longer be writing any new data into `moz-fx-data-derived-datasets:telemetry_derived`.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1612541
=> Move addons tasks to write into shared-prod

dags/bq_events_to_amplitude.py, jobs/hardware_report.py, jobs/update_orphaning_dashboard_etl.py
We should be able to merge these changes immediately. They are internal details that don't need to hit derived-datasets anymore.
=> Move dashboard and amplitude ETL to shared-prod tables

dags/utils/dataproc.py
On 2020-03-23 Hardware report job is consistently failing with `The zone 'projects/REDACTED/zones/us-west1-b' does not have enough resources available to fulfill the request.  '(resource type:compute)'.`.
We should be able to avoid this error by using Auto Zone Placement.
=> Use Auto Zone Placement for Dataproc clusters

dags/utils/dataproc.py
This fixes #916 by setting region in cluster delete operation.
Delete operator uses [`global`](https://github.com/apache/airflow/blob/1.10.7/airflow/contrib/operators/dataproc_operator.py#L608) region by default which causes [failures](https://workflow.telemetry.mozilla.org/log?task_id=delete_dataproc_cluster&dag_id=update_orphaning_dashboard_etl.update_orphaning_dashboard_etl&execution_date=2020-03-23T02%3A00%3A00%2B00%3A00) in DAGs that use DataprocHelper.
=> fixup! Use Auto Zone Placement for Dataproc clusters (#916)

dags/incline_dash.py
Apparently this is valid syntax for creating a tuple. Who knew?
This is causing the task to throw AttributeError.
=> Remove errant trailing comma in incline_dash dag

dags/incline_dash.py
It appears that `.format` gets applied before templating happens?
These were showing up literally as strings like `{ ds }` in error logs.
=> Remove jinja variables refs from formatted strings

dags/asn_aggregates.py
Schedules https://github.com/mozilla/bigquery-etl/pull/850
This can only get merged after everything is set up so that Airflow can access `payload_bytes_raw`: https://bugzilla.mozilla.org/show_bug.cgi?id=1627798
=> Schedule ASN aggregates query

dags/copy_deduplicate.py, dags/incline_dash.py
This will immediately replace the VR browser tables, but there will be follow-up steps to point all downstream Fenix ETL at this source as well, after which we can remove many deprecated tables.
Depends on https://github.com/mozilla/bigquery-etl/pull/887 and https://github.com/mozilla/bigquery-etl/pull/877
=> Add generic glean ETL

jobs/ltv_daily.py
The `partitionField` option doesn't work unless the field is actually a date. I tested this in a sandbox project and confirmed that the resulting table is partitioned.
=> Bug 1627091  - Cast date column to a date

dags/glam_org_mozilla_fenix.py
I made a typo that can only be tested in production:
```
[2020-04-14 20:37:05,402] {logging_mixin.py:112} INFO - [2020-04-14 20:37:05,401] {pod_launcher.py:234} INFO - Event with job id extract-csv-342c80ba Failed
[2020-04-14 20:37:05,486] {logging_mixin.py:112} INFO - [2020-04-14 20:37:05,486] {pod_launcher.py:125} INFO - bash: script/glam/extract_csv: No such file or directory
```
=> Use export instead of extract for glam_org_mozilla_fenix dag

jobs/ltv_daily.py
Cleaned up metric specification as well.
Preliminary analysis suggests `search_with_ads` is highly correlated to revenue.
=> Add days_searched_with_ads to list of metrics

dags/public_data.py
The `public_data_gcs_metadata` task in the `public_data` DAG was never executed since it was stuck waiting for `ssl_ratios` (`INFO - Poking for ssl_ratios.ssl_ratios on 2020-04-19T06:00:00+00:00`). 
I think the problem is that `ssl_ratios` is scheduled `@daily` while `public_data` is scheduled for 6am UTC. Setting the `execution_delta` to 6h should fix this.
=> Add execution_delta to wait_for_ssl_ratios in public_data DAG

dags/copy_deduplicate.py
As announced one week ago on fx-data-dev:
https://mail.mozilla.org/pipermail/fx-data-dev/2020-April/000339.html
I will plan to merge this, then respond to the thread indicating these table are no longer being updated and that the underlying data will be removed at the end of the week. Also, I'll announce that vrbrowser tables are sticking around as I received word that they are being actively used and we don't have a clear transition path.
=> Remove legacy Fenix ETL

dags/copy_deduplicate.py
These were descheduled in #940 in favor of generic Glean baseline ETL, but
VR Browser folks have existing dashboards which rely on some features here that
don't exist in the baseline-only ETL. We will continue to support this for now
until we develop a more robust strategy for incorporating per-product metrics
into the generic ETL.
=> Reschedule vrbrowser_clients_daily

dags/public_data.py
`gke_command(command=...)` expects a list as parameter
=> public_data metadata task command as list

dags/bq_events_to_amplitude.py
This is part of the work to cover the immediate overages we are
seeing in Amplitude events.
=> Bug 1632970 - Stop sending FFTV and Focus events to Amplitude

dags/ltv.py, jobs/ltv_daily.py
This makes two big changes:
1. Adds days_seen to predictions. We will now predict the number
of days we will see this user over the next 28 days.
2. Adds p_alive for all metrics. We can use this to determine
if we think the user is alive or dead. If p_alive for
days_seen is <.5, we may assume the user is dead.
Small changes:
- Code fixup
- Cluster on sample id and client id
- Allow adding new fields to output table
@benmiroglio I've run this on the full set of rfm data from yesterday. You can see the results in `frank-sandbox.analysis.ltv_daily`. I've added you as a viewer to that dataset so you should have access.
The results for `p_alive` look interesting and merit further investigation:
The x-axis there is `p_alive` for `days_seen`, and the y-axis is cumulative fraction of users.
=> Ltv updates

dags/taar_weekly.py
taar-weekly is failing because the pip-install.sh script is not being referenced correctly.
This ran properly in the dev enviroment because the path to the shell script did not have the `jobs/` prefix, but failed in production as I didn't put the prefix back in.
=> fixed improper path to pip-install.sh

dags/glam_org_mozilla_fenix.py
See https://workflow.telemetry.mozilla.org/log?task_id=gcs_delete&dag_id=glam_org_mozilla_fenix&execution_date=2020-04-17T00%3A00%3A00%2B00%3A00 for example of a failure. This is caused by insufficient permissions on the `google_cloud_derived_datasets` connection. This should be resolved by changing it to use the `google_cloud_airflow_dataproc` connection.
=> Replace connection id for glam-dev-bespoke with airflow_dataproc

dags/shredder.py
This was misconfigured because I misunderstood how `schedule_interval` impacts `ds` relative to actual run date.
This should run on Tuesday mornings UTC every 28 days, with `--end-date` set to the day before the run actually started, and with `--start-date` set to two `schedule_interval`s before that.
=> Fix shredder dag timing

dags/glam.py, dags/glam_subdags/general.py
In recent changes, https://github.com/mozilla/telemetry-airflow/commit/33ef0949c411a3513939b868fac6cfec8509fd6e, `client_histogram_probe_counts` was changed to a `repeated_subdag` but lost the `date_partition_parameter=None,` parameter. So now the value is set to the default from here: https://github.com/mozilla/telemetry-airflow/blob/master/dags/utils/gcp.py#L458. This is an issue because the table being written to is not partitioned by date (or at all).
Also in recent changes, https://github.com/mozilla/bigquery-etl/commit/f41ee1a7b1026919ffef046cd513857520aa4d63#diff-3f2a16a41a4eccb0c207033901041bdcR161, `submission_date` was added as a parameter for `client_histogram_probe_counts` and it needs to be passed in
=> client_histogram_probe_counts task should not have a date_partition_parameter for desktop glam.

dags/bq_events_to_amplitude.py, dags/fxa_amplitude_export.py
As of https://github.com/mozilla/bigquery-etl/pull/966
this export now depends on the table created in this chain.
=> Move sync send tab export to fxa_amplitude_export DAG

dags/glam_org_mozilla_fenix.py
This is causing job failures, causing aggregated fenix data to not be propagated into the nonprod bucket.
=> Use correct connection id for job running in docker

dags/glam.py
There was a failure here due to missing `s` on these names.
https://workflow.telemetry.mozilla.org/log?task_id=client_histogram_bucket_counts_0&dag_id=glam.client_histogram_bucket_counts&execution_date=2020-05-19T00%3A00%3A00%2B00%3A00
=> Fix variable names for desktop glam dag.

dags/glam.py
Goes with https://github.com/mozilla/bigquery-etl/pull/971
For the logging bug https://github.com/mozilla/telemetry-airflow/issues/844, the scalar queries have around 4-5 minutes of headroom before they crash (It looks like the tasks crash at around 9-10 minutes with no logging) so we can allow logs for those.  But the histogram queries go over so we would need to disable logs for those.
=> Convert desktop glam clients daily queries to gke commands

dags/fxa_events.py
Depends on https://github.com/mozilla/bigquery-etl/pull/1015
=> Move all fxa derived tables to shared-prod firefox_accounts_derived

dags/bqetl_amo_stats.py, dags/main_summary.py
This is the first DAG generated bigquery-etl that we're including here.
We're manually copying over the DAG for now, but eventually we will be
able to remove this definition from telemetry-airflow once WTMO automatically
imports bqetl-generated DAGs.
=> Factor AMO stats queries to their own DAG

dags/bqetl_error_aggregates.py, dags/error_aggregates.py
This depends on https://github.com/mozilla/bigquery-etl/pull/1031
This is DAG is generated in bigquery-etl using the lower-friction scheduled queries machinery.
For now the DAG is copied manually, but eventually we will be
able to remove this definition from telemetry-airflow once WTMO automatically
imports bqetl-generated DAGs. 
The main difference here is that the error_aggregates table now has a version. So before merging, we'd need to create a `error_aggregates_v1` table in `telemetry_derived`, copy existing data over and create a `error_aggregates` view to make sure any queries that depend on `error_aggregates` don't break.
=> Use generated error_aggregates DAG

dags/taar_daily.py
This removes the AWS Dynamo load for TAAR from the taar_daily DAG.
A subsequent PR will enable loading the equivalent data to GCP BigTable.
=> Remove dynamo task for TAAR daily

dags/bqetl_nondesktop.py
Generated via https://github.com/mozilla/bigquery-etl/pull/1044
I moved the query for `firefox_nondesktop_exact_mau28_raw_v1` to `telemetry_derived`. I also copied the table over to shared-prod and created a view in derived datasets to make sure nothing breaks.
=> Set telemetry_derived as dataset for telemetry_derived__firefox_nondesktop_exact_mau28_raw__v1

dags/bqetl_amo_stats.py, dags/bqetl_core.py, dags/bqetl_deviations.py, dags/bqetl_gud.py, dags/bqetl_mobile_search.py, dags/bqetl_nondesktop.py, dags/bqetl_vrbrowser.py, dags/kpi_dashboard.py
Updated bqetl_nondesktop DAG generated by https://github.com/mozilla/bigquery-etl/pull/1050
Before merging, I'll rename the table `firefox_nondesktop_exact_mau28_raw_v1` to `firefox_nondesktop_exact_mau28_v1` in BigQuery and update the corresponding view in derived-datasets.
=> Set mode=reschedule and rename telemetry_derived__firefox_nondesktop_exact_mau28__v1

dags/kpi_dashboard.py
This task is stuck in up_for_reschedule. It's looking for a task run on the
previous day at 16:00 rather than the current day at 10:00.
=> Fixup execution_delta for fxa mau in kpi_dashboard

dags/mozfun.py
This is for scheduling when public UDFs should be deployed. Only Airflow has permissions to deploy UDFs to `mozfun`.
=> Add DAG for mozfun

dags/taar_daily.py, jobs/taar_similarity.py
This updates the TAAR similarity job to run on BigQuery instead of using parquet files on GCS.
The retry limit has been reduced to 0 as retrying a job in TAAR daily is not helpful as the cluster typically goes into an invalid state.
Note that the number of worker nodes has been adjusted to get the runtime down.
Running the job with a local instance of Airflow - this configuration completes execution in just under 12 minutes.
=> Port TAAR similarity to BigQuery

dags/anomdtct.py
Variable replacement only happens for operator parameters that are specified as templated. GKEPodOperator's image parameter is not templated.
=> Use explicit project name for anomdtct image

dags/burnham.py
The `verify_data` task in the burnham DAG currently fails because the types for the `SUM` values don't match. This pull-request updates the `value_sum` values in the test scenario to integers.
I also updated the arguments for this task, so the logs show the full pytest test report.
=> Fix types for burnham test scenarios

dags/burnham.py
I missed one integer value when I copied the query result from the JSON tab in the BigQuery console. Sorry about that.
=> Fix glean_error_invalid_value type in burnham DAG

dags/fxa_events.py, dags/kpi_forecasts.py
Previously, we had set these queries to run at 10:00 UTC because we didn't
know much about the behavior of the FxA Stackdriver log pipeline. We now have
confirmation from jbuck that allowing 1 hour after UTC midnight should be
plenty of time for logs to flow to BigQuery.
=> Run fxa queries at 01:00 UTC

dags/taar_daily.py
While dealing with ETL issues today, I noticed that nothing depends on this particular sensor, so may be cruft that can be removed.
=> Remove unused wait_for_main_summary_export in taar_daily

dags/fxa_events.py
I changed it in bigquery-etl before I merged, but I forgot to fix it here.
=> Use correct user id field in shredder_amplitude_fxa

dags/glam_org_mozilla_fenix.py
https://github.com/mozilla/bigquery-etl/issues/1132
Is this all that's needed?  When we add other products we should add a function that wraps this gke_command call and explicitly sets product and project but I think this is fine for now.
=> Generate fenix glam sql before running

dags/glam.py, dags/glam_fenix.py, dags/glam_org_mozilla_fenix.py, dags/glam_subdags/generate_query.py
bq-etl pr: https://github.com/mozilla/bigquery-etl/pull/1183
issue: https://github.com/mozilla/bigquery-etl/issues/1130
This adds `org_mozilla_firefox`, `org_mozilla_firefox_beta`, and `org_mozilla_fennec_aurora` to the dag and renames the dag to `glam_fenix`.  This erases the task history for the dag but I don't expect that to be an issue.
=> Add fenix variants to glam

dags/leanplum_export.py
Leanplum exports data every 2 hours.  We currently import all the data once per day but release data takes ~8 hours to run.  Increasing the runs per day will reduce the data latency as requested by data science.  There is a mechanism is the export job to skip already imported files so this is safe to run multiple times a day.
Also changes ' to " but the schedule interval is the only real change and highlighted in the diff.
=> Change leanplum export to run every 4 hours

dags/burnham.py
Recent runs have failed with:
> TypeError: Object of type bytes is not JSON serializable
Which I believe is directly related to the switch to running WTMO on python3.
=> Burnham python3 fix

dags/app_store_analytics.py
Available data latency seems to be inconsistent and previous day data is available but incomplete for many metrics.  Setting to two day lag should work but I'll check over the next week to see if three days is needed.
Also I'll make a change to the export to warn about incomplete data.
=> Set app store export to two day lag 

dags/operators/moz_dataproc_operator.py, dags/utils/dataproc.py
Adds the labels env, owner, and jobname to dataproc clusters created by the moz_dataproc* wrapper funcs (for cost attribution if needed later on)
- Labels in GCP dataproc (maybe all products) only allow lowercase letters, numbers and dashes
- Tested successfully creating/deleting cluster with labels
=> Modify dataproc runners to append labels to dataproc clusters

dags/fxa_basket_export.py
The new dag in #1099 was not being recognized.
=> Fixups to fxa_basket_export

dags/fxa_basket_export.py
The service account is only granted access to create objects,
not to list or delete, so the gcs_delete step was failing.
It seems reasonable to maintain those limited privs and to remove the
delete step. We can revisit later if we find this causes issues in reprocessing.
I believe the overwrite behavior should be sufficient.
=> Don't delete from GCS in fxa_basket_export

dags/glam_fenix.py
A small change to get historical data flowing through the (deprecated?) org_mozilla_fenix_nightly app id, and a link to the spreadsheet with all of the app names.
=> Add org_mozilla_fenix_nightly and comment on sources

dags/prio/kubernetes.py
The job currently fails because v2.0 changes the top-level project layout.
=> Pin prio-processor to v1.6.1

dags/glam.py
For https://github.com/mozilla/bigquery-etl/pull/1216/files
Adds submission_date param to scalar_percentiles and scalar_probe_counts, and uses date partition for client_scalar_aggregates
=> Add submission date to glam scalar queries

dags/glam_fenix.py, dags/glam_subdags/generate_query.py
This depends on https://github.com/mozilla/bigquery-etl/pull/1221
This adds the dependencies needed for the logical view of fenix apps. The logical view takes the daily tables generated by the glean etl for scalars and histograms, and concatenates the set of client aggregate rows together.
=> Add support for logical app ids in glam etl for glean

dags/copy_deduplicate.py
Airflow is currently failing with 
```
google.api_core.exceptions.Forbidden: 403 Access Denied: Table moz-fx-data-shared-prod:xfocsp_error_report_live.xfocsp_error_report_v4: User does not have permission to query table 
```
This will prevent processing `xfocsp_error_report_live.xfocsp_error_report_v4`
=> Prevent copy_deduplicate xfocsp_error_report_live.xfocsp_error_report_v4

dags/play_store_export.py
This is to account for the ~2 week delay on data availability for some of the tables.  Pricing isn't based on number of days so cost shouldn't increase.
=> Increase play store backfill to 60 days

dags/burnham.py
Hi folks! 👋 
I updated the SQL queries in the burnham DAG to deduplicate documents submitted through automation. As discussed on Slack there is no guarantee live tables don't have duplicates, so we need this extra step to ensure reproducibility.
We don't need to deduplicate rows for the distinct client IDs test, I think. I ran an example for each of the updated queries manually and they seem to produce the expected values.
Resolve https://github.com/mozilla/burnham/issues/61
=> Deduplicate burnham documents

dags/burnham.py
[Glean v31.5.0][glean] changed the error reporting behavior. String values that are too long now record `invalid_overflow` rather than `invalid_value`.
Resolve https://github.com/mozilla/burnham/issues/70
[glean]: https://github.com/mozilla/glean/releases/tag/v31.5.0
=> Update burnham glean error test

dags/burnham.py
The burnham DAG currently creates three clients. Every burnham client will submit exactly one `space_ship_ready` ping after Glean is initialized and a space ship is created. When a client completes `MISSION E: ONE JUMP, ONE METRIC ERROR` the `starbase46` ping is submitted, which happens exactly once in this DAG. The updated DAG will now verify the document counts.
This is currently blocked on the schema deploy for the new pings.
See https://github.com/mozilla/probe-scraper/issues/225
=> Add additional tests for two new burnham tables

dags/prio/kubernetes.py, dags/utils/gke.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1664582)
This is the final configuration for the Prio cluster on GKE (which is more of a skeleton that needs to be filled in for each project). It includes a taint on the node-pool so k8 services won't prevent the nodes from dying, and tolerations on the pod operator to actually run on the node. I've tested this with a slightly different airflow DAG where the cluster is only created on job failure, and where I delete the clusters when the definition changes.
In a follow up, if we can convert the cluster definition here so that it's running persistently, it would make debugging this DAG a lot easier because of the time it takes to boot up a cluster.
=> Bug 1664582 - Add separate node-pool on Prio clusters for running large jobs

dags/burnham.py
We currently don't store DEBUG logs from the burnham application and don't log when the Glean SDK is sending pings. This pull-request sets the respective environment variables for the burnham operators which should  help us diagnose any issues.
Resolve https://github.com/mozilla/burnham/issues/73
=> Enable DEBUG logging for burnham operators

dags/glam.py
This is a temporary workaround for a resources exceeded exception when running clients_scalar_probe_counts tracked here: https://github.com/mozilla/bigquery-etl/issues/1432
The task almost always fails on the first run but succeeds afterwards.  My guess is other queries are taking up too many slots on the first run.  This graph https://workflow.telemetry.mozilla.org/gantt?dag_id=glam shows the successful re-run.  The first run starts at the same time as scalar_percentiles.  My hypothesis is that making these two run sequentially will avoid the exception.  
This is a temporary workaround to avoid daily failures.  There's no guarantee that other queries in the project won't also cause the issue.
=> Make client_scalar_probe_counts depend on scalar_percentiles

plugins/backfill/main.py
I've not had success over the past few days getting the backfill UI to work.
I submit jobs, but they never produce output or result in BQ output.
I checked in cloud logging and found ERROR messages with tracebacks ([example](https://console.cloud.google.com/logs/query;pinnedLogId=2020-10-15T13:57:27.221935242Z%2Fr7d2ll39deckufib8;query=backfill%0Aseverity%3DERROR?project=moz-fx-data-airflow-prod-88e0)):
```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
self.handle_request(listener_name, req, client, addr)
File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
addr)
File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 114, in …
```
=> Fix python 3 string handling issue with backfill UI

dags/prio/kubernetes.py, dags/prio/processor.py, dags/prio_processor.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1675348)
This PR makes the dag/prio module declare subdag functions that can be used to build separate dag. There are no functional changes. A follow-up dag will separate the dag into two separate dags.
=> Bug 1675348 - Refactor prio-processor dag to decouple server components

dags/fission_experiment_monitoring.py
Crash aggregates table depends on both main and crash ping tables.
This makes crash aggregation task wait for main ping deduplication in addition to the crash ping deduplication.
=> Update fission experiment monitoring task dependencies

.circleci/config.yml
This disables the plugin tests to fix #1179. These tested plugins are not being used (moz_databricks and mozetl).
=> Remove plugin tests from CircleCI

dags/prio_processor.py, dags/prio_processor_external.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1675348)
This moves server B into it's own DAG, which means it can be turned off and replaced by a job that's configured elsewhere, like https://github.com/mozilla-services/cloudops-infra/pull/2685
=> Bug 1675348 - Decouple prio server B from admin and server A

dags/burnham.py
The `verify_discovery_data_disable_upload` task failed last night due to the following error:
```
SELECT list expression references metrics.string.mission_identifier which is neither grouped nor aggregated
```
This pull-request adds the missing `GROUP BY` clause to the respective query. I tested the query manually in the BigQuery Console and it returns the expected results now.
Follow-up pull-request for #1182
=> Add missing GROUP BY clause to burnham query

dags/burnham.py
I refactored the SQL templates so that we can use multiple templates in a `WITH` block. This allows us to re-use the deduplication logic for multiple tables in a new test scenario for verifying the client ID in deletion-request pings. 👩‍🚀 
Please let me know your thoughts!
Resolve https://github.com/mozilla/burnham/issues/77
=> Add burnham scenario for client IDs in deletion-request ping

dags/burnham.py
I realized that I copied the wrong task as an upstream for `verify_deletion_request_data`. FWIW this is not related to the recent failures on Airflow, which will hopefully be resolved by https://github.com/mozilla/burnham/pull/115.
Follow-up for #1195
=> Fix upstream for verify_deletion_request_data

dags/burnham.py
The DAG currently looks a bit cluttered. By pruning these dependencies,
it will be easier to tell what's going on at a glance in the tree view:
https://workflow.telemetry.mozilla.org/tree?dag_id=burnham
Also, Airflow now can render docs on the tree view page.
=> Burnham prune deps

dags/glam_fenix.py
There's a new GCP project to support the production glam stuff in [bug 1618341](https://bugzilla.mozilla.org/show_bug.cgi?id=1618341) and the appropriate dataset syndication in [bug 1643511](https://bugzilla.mozilla.org/show_bug.cgi?id=1643511).
=> Update glam fenix dag to point to production project

dags/glam_subdags/extract.py
This changes the bucket for the glam export to the production location at gs://moz-fx-data-glam-prod-fca7-etl-data
=> Change glam bucket for desktop exports to glam-prod

dags/glam_fenix.py
I noticed that the SRC_PROJECT wasn't set correctly for the csv exports. 
https://github.com/mozilla/bigquery-etl/blob/0990be8bfa5ec66eff41da898db75e3d75280f0e/script/glam/export_csv#L7-L9
=> [glam-fenix] Add SRC_PROJECT to export and use variables

dataproc_bootstrap/dataproc_init.sh
Currently, `dataproc_init.sh` updates pip to 20.3.1 which tries to
install the dependencies, but takes > 10 minutes to figure out a
solution set that satisfies the version dependencies.
This has us go back to the previous pip which has the old resolver which
works while we figure out how to straighten out the dependency
requirements.
=> Pin pip to <20.3.0 for now until we fix resolution issue (#1198)

dags/crash_symbolication.py
Execution date should be day before.  Also avoid running on days not needed
=> Change symbolication to run day before

dags/copy_deduplicate.py, dags/experiment_monitoring_data_export.py
This adds a DAG for running the experiment monitoring data export script and removes experiments enrollments from `copy_deduplicate`.
Depends on https://github.com/mozilla/bigquery-etl/pull/1656
=> DAG for running the experiment monitoring data export

.circleci/config.yml
- Pulled from gcr repo since they will deprecate dockerhub in 3/21
- Pin the current image since latest may have broken our sync gcs ci step
=> Modifying googles cloud-sdk image 

dags/copy_deduplicate.py
copy_deduplicate_main_ping task fails consistently on 2020-01-20 due to increased volume of data. By increasing number of slices we deduplicate in we should be able to avoid out of memory BigQuery errors.
=> Increase number of slices in main ping deduplication task

dags/experiment_monitoring_data_export.py
I created a view with the "wrong" name in the meantime so Airflow won't fail the task. The export, hourly and 5-minute queries seem to be running smoothly so far.
=> Fix dataset name for experiment_monitoring_data_export

dags/glam.py
This fixes the other 2/4 queries for fixing https://github.com/mozilla/bigquery-etl/issues/1660 in addition to https://github.com/mozilla/bigquery-etl/pull/1695. Note that the tables will need to be deleted before these jobs are actually scheduled.
=> Add metric and channel to probe count queries for GLAM

dags/operators/bq_sensor.py
This is a follow up to #1233 where other sensors were switched to 'reschedule' mode. This will help us avoid deadlock situation that occured on 2021-01-20, when we had large number of sensor tasks not letting copy_deduplicate jobs to queue.
=> Switch BigQuerySQLSensorOperator tasks to `reschedule` mode on a dedicated sensor pool

dags/copy_deduplicate.py, dags/experiments_live.py
Depends on https://github.com/mozilla/bigquery-etl/pull/1721
This is basically the same approach also used for the experiment enrollments monitoring queries.
=> Schedule experiment search metrics export

dags/copy_deduplicate.py
Reverts #1224 which should no longer be needed after changes as discussed in
[GCP case 26581883](https://console.cloud.google.com/support/cases/detail/26581883?caseId=26581883&accountId=gcp-sa-1256631965&folder=&organizationId=&project=moz-fx-data-shared-prod)
=> Move copy_deduplicate_main_ping back to 100 slices

dags/experiments_live.py, dags/utils/gcp.py
Setting `is_delete_operator_pod=True` for tasks in `experiments_live` and merging export tasks to reduce number of tasks spawned
=> Set is_delete_operator_pod=False for experiments_live pods

dags/operators/gcp_container_operator.py
Tested locally and works to add annotation to pods. 
Annotation should tell cluster auto scheduler that these pods are safe to delete even though they aren't under an replication controller or deployment (something that is preventing our current node pools from scaling down).
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node
=> Fix gke cluster scale down for completed pods without rc

dags/taar_daily.py, jobs/telemetry_batch_view.py
Adapts to the new default branch in telemetry-batch-view.
See https://github.com/mozilla/telemetry-batch-view/pull/565
=> Use 'main' in references to telemetry-batch-view

dags/attitudes_daily.py, dags/bhr_collection.py, dags/bq_events_to_amplitude.py, dags/crash_symbolication.py, dags/firefox_public_data_report.py, dags/glam.py, dags/glam_fenix.py, dags/graphics_telemetry.py, dags/incline_dash.py, dags/jetstream.py, dags/kpi_forecasts.py, dags/ltv.py, dags/parquet_export.py, dags/taar_daily.py, dags/webrender.py
This is a follow-up to https://github.com/mozilla/telemetry-airflow/pull/1233, limiting number of alert emails sent from Airflow.
=> Don't send alert emails on rescheduled sensor retry

dags/fission_experiment_monitoring.py
Replacing `moz-fx-data-shared-prod` for new `mozdata` project for Fission monitoring experiment analysis table.
=> Updating Fission analysis table to utilize `mozdata` project.

jobs/taar_similarity.py
It fixes recent job failures. We don't need hive there.
=> Disable hive for taar similarity job

dags/fxa_export_to_amplitude.py
Per @cvalaas, the SFMC email system is now retired, so the underlying table
here is no longer receiving updates. The job has been failing due to
waiting for data since 2021-03-09.
See https://github.com/mozilla/bigquery-etl/pull/1892 for removal of the view used here.
=> Remove fxa_email_click_amplitude_export

Makefile, README.md, bin/start_gke, bin/stop_gke
Open for suggestions/comments/concerns
- Adds `make gke` and `make clean-gke` targets
~~Changes local environment to only load dags in the new devdags/ folder. (This may be controversial, but saves about 3-4 minutes of startup time involving importing dummy variables and connections)~~
- More info: go/wtmodev
infra pr https://github.com/mozilla-services/cloudops-infra/pull/2967
=> Add make target for sandbox gke clusters to simplify local dev/testing

README.md, plugins/mozmenu.py
Trying to make it easier for developers to discover https://mana.mozilla.org/wiki/display/DOPS/WTMO+Developer+Guide
=> Add links to WTMO dev guide in README and menubar

dags/copy_deduplicate.py
Dependency of [this jira ticket](https://jira.mozilla.com/browse/DS-1424) and the scheduling of https://github.com/mozilla/bigquery-etl/pull/1934.
This also formats the module with black. This is split across two commits.
=> Schedule telemetry_derived.core_clients_first_seen

dags/utils/amplitude.py
We've been cleaning out `moz-fx-data-derived-datasets`, so it's no longer appropriate to be writing temporary data there.
=> Amplitude export should not write to derived-datasets

dags/copy_deduplicate.py
We have previously been unable to run copy_deduplicate as a single query
for main_v4 due to resource constraints in BigQuery causing queries to fail.
See https://github.com/mozilla/telemetry-airflow/pull/1224 as an example.
BQ engineering, though, has made some backend changes to improve efficiency
for cases like this, and recent testing has shown that running a single query
is effective. This should be somewhat more cost efficient than splitting the
query into slices, and it can potentially lead to more effective clustering
and less fragmentation.
We also increase parallelism for non-main_v4 queries. Most of these are small
and overall time of the job may be dominated by simply waiting for BQ per-query
overhead.
I will plan to immediately rerun a day once this is merged as a sanity check …
=> Optimize copy_deduplicate parallelism

dags/copy_deduplicate.py
We are still running into memory errors when running with a single query
after merging https://github.com/mozilla/telemetry-airflow/pull/1279
This moves back to slices, but decreases the number from 100 to 20.
=> Use 20 slices for copy_deduplicate_main_ping

dags/mad_server.py
Follow-up to #1284 
The DAG is merged and the initial task failed ([logs](https://workflow.telemetry.mozilla.org/log?task_id=mad_server_pull&dag_id=mad_server&execution_date=2021-04-18T00%3A00%3A00%2B00%3A00)) with a message that mentioned 'bq-load-gke-1', so I think the problem is simply that we were using a default argument for cluster_name.
=> Specify cluster name for mad_server

bin/run, bin/test-parse, dags/probe_scraper.py
There don't seem to be values for the env vars from the Airflow variables. Hoping this fixes that issue. (The env vars are present, but empty; other env vars (e.g. looker_hub_url) are present and valid.)
=> Use modern convention for variable access

dags/fission_experiment_monitoring.py
Tables updated and `env_vars` added for R-analysis portion of the DAG. 
* `telemetry.main_nightly` and `telemetry.crash` are used directly
* A new arg `BQ_TMP_CRASH_TABLE` corresponds to tmp table that analysis codebase creates on the fly, corresponding to client, `submission_date` aggregations from `BQ_INPUT_CRASH_TABLE`.
I leave removing the portions corresponding to creation of the intermediate tables (e.g., `fission_monitoring_main_v1`) to those versed in airflow.
=> Support for Fission rollout

dags/fxa_export_to_amplitude.py, dags/utils/gcp.py
Depends on https://github.com/mozilla/bigquery-etl/pull/2011
This removes support for `allow_field_addition_on_date`, instead table schemas should be updated via `schema.yaml` files in bigquery-etl. 
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1706683
=> Remove allow_field_addition_on_date support

dags/copy_deduplicate.py
`--only` is not a backfill option, it was used in the old scripts
=> Remove --only parameter from baseline tasks

dags/copy_deduplicate.py
Reverts https://github.com/mozilla/telemetry-airflow/pull/1312
Relies on https://github.com/mozilla/bigquery-etl/pull/2062
=> Run baseline backfill without generating queries

dags/shredder.py
the main and main_summary tables sometimes take a lot of tries to finish. That's fine, but it shouldn't require human intervention, so I'm increasing the retry count to 14 (for a total of 15 attempts), because we've had a few cases of finishing on the 11th or 12th run lately.
=> Increase shredder retries

dags/copy_deduplicate.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1712696
I introduced this regression in
https://github.com/mozilla/telemetry-airflow/pull/1317
which @scholtzan had previously fixed in
https://github.com/mozilla/telemetry-airflow/pull/1313
=> Bug 1712696 Run baseline_clients_first_seen with --no-partition

dags/copy_deduplicate.py
Noticed this while rerunning two days while addressing https://bugzilla.mozilla.org/show_bug.cgi?id=1712696 and realizing that output will not be correct if both days run concurrently.
=> Mark baseline_clients_first_seen as depends_on_past

dags/operational_monitoring.py
I spoke to Anthony about how jinja generates sql from airflow in other locations. He mentioned that it's done with entrypoint scripts: https://github.com/mozilla/bigquery-etl/blob/2f29f6ed9007f9516fe6881a775ff8ae3ee06b65/script/generate_sql#L44
One thing to try is invoking bqetl with `./script/bqetl` since `bqetl` might be aliased from $pwd which may affect where `PackageLoader` is looking.
Giving this a shot
=> Directly reference bqetl script for running operational monitoring.

dags/operators/task_sensor.py
This adds a custom implementation of `ExternalTaskSensor` which also checks if the upstream task failed. This is one of the options described in this [proposal](https://docs.google.com/document/d/1xpCexfUfYn2PVVkwh4ozWIv6F45dobq1TizPwS6_D0Y/edit#). Once we switch to Airflow 2 this can simply be replaced by the new `ExternalTaskSensor`, which works essentially the same this custom sensor does.
This will lead to the `ExternalTaskSensor` tasks eventually failing instead of getting re-scheduled indefinitely.
@hwoo Does this seem like a reasonable approach?
If this seems like a reasonable idea, I'll first test this with a couple of bigquery-etl generated DAGs.
=> Custom ExternalTaskSensor implementation

dags/glam.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1720157#c1)
This increases the number of tasks from 10 to 20 due to:
```
[2021-07-14 21:42:54,520] {pod_launcher.py:156} INFO - b'query execution: Your project or organization exceeded the maximum disk and\n'
[2021-07-14 21:42:54,521] {pod_launcher.py:156} INFO - b'memory limit available for shuffle operations. Consider provisioning more slots,\n'
```
=> Bug 1720157 - Increase number of tasks for bucket counts

bin/run, bin/test-parse, plugins/backfill/main.py, requirements.in, requirements.txt
Why 1.10.15 initially?
https://airflow.apache.org/docs/apache-airflow/2.1.0/upgrading-to-2.html#step-2-upgrade-to-airflow-1-10-15-a-k-a-our-bridge-release
Changelogs of potential note to review (from 1.10.13 -> 1.10.15):
- https://github.com/apache/airflow/pull/10666
- https://github.com/apache/airflow/pull/10963
- https://github.com/apache/airflow/pull/12419
- https://github.com/apache/airflow/pull/10850
- https://github.com/apache/airflow/pull/12328
- https://github.com/apache/airflow/pull/12311
- https://github.com/apache/airflow/pull/12003
- https://github.com/apache/airflow/pull/11480
- https://github.com/apache/airflow/pull/11191
- https://github.com/apache/airflow/pull/11095
- https://github.com/apache/airflow/pull/11468
- https://github.com/apache/airflow/pull/12069
- …
=> [DSRE-9] - Upgrade Airflow wtmo to 1.10.15 bridge release prior to 2.0

dags/glam_fenix.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1722744
Relevant lines:
```
[2021-07-28 07:34:49,118] {pod_launcher.py:156} INFO - b'generated sql/moz-fx-data-glam-prod-fca7/glam_etl/org_mozilla_fenix_glam_beta__latest_versions_v1/query.sql\n'
...
[2021-07-28 07:34:49,169] {pod_launcher.py:156} INFO - b'script/glam/run_glam_sql: line 33: sql/moz-fx-data-glam-prod-fca7/glam_etl/org_mozilla_fenix_glam_beta__latest_versions_v1/view.sql: No such file or directory\n'
```
=> Bug 1722744 - Use query instead of view to fix missing file

dags/operational_monitoring.py
The `operational_monitoring` DAG is currently still under heavy development and frequently failing. To prevent constantly bugs being filed during Airflow triage, I added a note to the DAG description that failures can be ignored for now. Once it's production ready we can update the docs there.
=> Add note to operational_monitoring DAG

dags/glam.py, dags/glam_subdags/extract.py
The PR is to resolve the issue [#1240](https://github.com/mozilla/glam/issues/1240). 
As part of this change, I have added two tasks 
1. glam_sample_counts: This task aggregates (sums) on the histogram values [query](https://gist.github.com/alekhyamoz/031fd954469acd6020d844202c5f8ce4)
2. extract_sample_counts: This task extracts the data from bigquery table and pushed the data to GCS in csv format
The below is how the dag looks including the above two tasks:
=> add sample counts to glam desktop dag

dags/probe_scraper.py
The Airflow tasks failed last night since they expect string values for env variables.
=> lookml-generator UPDATE_SPOKE_BRANCHES as string

dags/bhr_collection.py, dags/etl_graph.py, dags/experiments_live.py, dags/firefox_public_data_report.py, dags/glam.py, dags/glam_fenix.py, dags/graphics_telemetry.py, dags/jetstream.py, dags/kpi_forecasts.py, dags/ltv.py, dags/mad_server.py, dags/mozaggregator_mobile.py, dags/mozaggregator_prerelease.py, dags/mozfun.py, dags/parquet_export.py, dags/partybal.py, dags/play_store_export.py, dags/taar_daily.py, dags/taar_weekly.py, dags/update_orphaning_dashboard_etl.py
Inspired by discussion early today of nostalgia for docs days,
I wanted to add basic docs to all the bespoke DAGs in this repo
to help with giving basic context in the Airflow UI that should help with
onboarding folks to the Airflow triage process.
=> Add missing docs to DAGs

dags/contextual_services_import.py
Based on failure in https://workflow.telemetry.mozilla.org/log?dag_id=contextual_services_import&task_id=quicksuggest2bq&execution_date=2021-11-18T17%3A13%3A28.682138%2B00%3A00 and [kube logs](https://console.cloud.google.com/logs/query;query=quicksuggest2bq.d9badb30c934490cb50eaf05b7ed42db;cursorTimestamp=2021-11-18T17:16:46Z?project=moz-fx-data-derived-datasets)
=> Fixup quicksuggest2bq image url

dags/burnham.py
Doubling the sleep timer. This may be a bit much but I don't think it will hurt since we are effectively doubling the amount of pings sent.
=> More changes to fix burnham dag errors.

requirements.in, requirements.txt
=> [DSRE-316] Update airflow to 2.1.3 to fix Flask issues with editing UI User permissions

dags/glam_fenix.py, dags/glam_firefox_desktop.py
The glam fenix imports are failing with error  'Dependencies not met' 
https://workflow.telemetry.mozilla.org/log?dag_id=glam_fenix&task_id=glam_fenix_import_glean_counts&execution_date=2021-12-10T02%3A00%3A00%2B00%3A00
The error is complaining about the upstream task 'export_org_mozilla_fenix_glam_beta' 
Example: 
The task starts at time 2021-12-11 02:18:35,380,
But the dependent task finishes afterward: at the time [2021-12-11 02:19:24,249]
=> Adding sleep op fenix

dags/glam.py
Isolate the glam import nightly task to understand the time taken by refresh.
=> Isolate glam import nightly task

dags/socorro_import.py
When collecting a list of Airflow tags we identified that some DAG owners were no longer at Mozilla. This PR updates out of date owners.
Airflow Tags Google Sheet: https://docs.google.com/spreadsheets/d/1WXo5_d8j_KfGzT07ay3gC2zAfnhRHzxoZDlwcThNvf0/edit#gid=0
=> Updated owner of socorro_import DAG as per tags google sheet

dags/glam_fenix.py
Reverts mozilla/telemetry-airflow#1431. 
Adding the sleep task is not quite helpful for this issue. 
Will create another PR to add the sleep at [this](https://github.com/mozilla/telemetry-airflow/blob/7a195415de77d7bdb4651406f50df96005960bb8/dags/glam_fenix.py#L166) point in the code.
=> Revert "Adding sleep op fenix"

dags/glam.py
Reverts mozilla/telemetry-airflow#1433. The issue of glam import taking long hours to complete was resolved and the task no longer needs to be isolated.
=> Revert "Isolate glam import nightly task"

dags/socorro_import.py
I'm wkahngreene and one of my aliases is willkg. This removes one of them from the email list.
=> Remove duplicate email address from socorro_import DAG

.circleci/config.yml, .gitignore, Dockerfile, bin/test-dag-tags.py, bin/test-parse, dags/casa.py, dags/crash_symbolication.py, dags/intacct_historical.py
- `bin/test-dag-tags.py` script introduced to query `dag_tag` Airflow table to retrieve a list of all DAGs along with their tags and ensure they are correct.
- `test-environment` check now includes a command for executing a python script validating Airflow DAGs (part of `test-parse` script).
- installing mysql-client on airflow image to be able to query the DB for tag validation
- Added tag assignment to DAGs that were missing them
- Integrate this check with `bigquery-etl` repos
resolves #1443
=> Step to validate airflow dags as part of CI

bin/test-dag-tags.py
In some cases it seems we can have dags with tags not in dags table, in this case print warning but don't fail check.
Not sure why we see this error, in dev branch have not happened before. This adds logic to handle this specific case and log which dag is "missing"
=> Addressing issue with more dags in tags tbl than in dags table

dags/shredder.py
short term fix for [Bug 1747068](https://bugzilla.mozilla.org/show_bug.cgi?id=1747068)
long term fix will add additional billing project(s), when they are provisioned.
=> Bug 1747068 - Mitigate shredder.on_demand falling behind

dags/search_alert.py
Execution date should be used here, not the day before.
=> Search alert: fix date parameter

dags/shredder.py
to increase allowed parallelism
[Bug 1747068](https://bugzilla.mozilla.org/show_bug.cgi?id=1747068)
=> Bug 1747068 - Use --no-use-dml flag for shredder on-demand

dags/burnham.py
Updates burnham version to 22.0.0, glean-sdk version to 43.0.2 and glean-parser version to 4.4.0.
=> Update burnham DAG dependencies.

dags/shredder.py
see [Bug 1747068](https://bugzilla.mozilla.org/show_bug.cgi?id=1747068) for explanation
=> Bug 1747068 - Revert dml and parallelism for shredder-on-demand

dags/glam_glean_imports.py
The recent deployment of glam created a latest version : [gcr.io/moz-fx-dataops-images-global/gcp-pipelines/glam/glam-production/glam:2022.02.0-15](http://gcr.io/moz-fx-dataops-images-global/gcp-pipelines/glam/glam-production/glam:2022.02.0-15)
Updated the airflow dag with the latest version
=>  updated the gcr image for glam with latest version

dags/mozaggregator_prerelease.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1751206
There seems to report of people seeing this error after upgrading spark. I'm not sure if this actually is why we started to see this problem. This is the simple potential "solution" I found and thought it's worth a try.
=> attempting to see if this is enough to resolve bug: 1751206

dags/probe_scraper.py
The FOG checks that the runner kicks off may need it to file bugs for expiring
metrics.
=> bug 1696907 - Give probe_scraper.runner a copy of the BMO API key

dags/shredder.py
and specify `--no-use-dml` for all tasks.
shredder tracks state by target, not by airflow task id, and is designed to gracefully handle restarts. It should handle renaming all of the tasks without issue, but the new tasks will need to be manually started in the current shredder run.
=> Rename shredder tasks now that everything will be flat rate

dags/glam.py, dags/glam_fenix.py, dags/glam_fog.py
As per the discussion in [this link](https://github.com/mozilla/glam/pull/1853) we no longer need to extract the sample counts separately and can be part of the `client_probes_extract` sql part
=>  Remove extracting sample counts to csv in glam dags

dags/glam_fenix.py, dags/glam_fog.py
Rearrange the tasks for the sample counts to be calculated before the extract probe counts task.
=> change the order for the sample counts to be calculated before extract

dags/jetstream.py, dags/operational_monitoring.py
This updates the DAG to use the new opmon container instead (https://github.com/mozilla/opmon)
Once approved, but before merging we'll need to backfill the existing projects.
=> Update operational monitoring DAG

Makefile, bin/run, dags/example_pubsub.py, dags/example_slack.py, dags/utils/slack.py, requirements.in, requirements.txt
This will require a new airflow deployment to pick up library changes.
- PR adds example code for writing to pubsub (the topic must already exist)
- PR adds example code to show how to post to slack when a dag task fails
- PR also clears out airflow-worker.pid when user runs `make clean`
todo
Slack alerts will go to #airflow-alerts channel currently and will look similar to:
=> [DSRE-596] add sample pubsub and slack operators

dags/probe_scraper.py
As discussed, this might help to prevent issues where lookml-generator does not have the most recent schemas available and is generating incorrect LookML
=> Increase wait time for lookml generator to 1h

dags/intacct_historical.py
It looks like sometimes the wait tasks lose connection to the Fivetran API, we should shut them down after a while
=> [Bug 1765180] Timeout for intacct historical wait tasks

dags/intacct_historical.py
When investigating [bug 1765180](https://bugzilla.mozilla.org/show_bug.cgi?id=1765180) I discovered a race condition with how `FivetranSensor` was set as downstream of the associated `FivetranOperator`:
> The [Fivetran sensor](https://github.com/mozilla/telemetry-airflow/blob/main/dags/operators/backport/fivetran/sensor.py) appears to work by reading the last connector run timestamp when it starts and then looking for a change in that. However, if the sensor task is delayed for some reason it might start after the Fivetran sync already completed, in which case it will end up waiting for the next sync, which will be the next daily sync triggered by Airflow.
> 
> That appears to have been the case here where the `intacct-sensor-china_vie` task didn't start until 2022-04-19 02:05:34, while …
=> Start Intacct Fivetran sensors before Fivetran syncs start (bug 1765180)

dags/intacct_historical.py
To avoid hitting Fivetran's limit of 5,000 API calls per hour (which [happened on 2022-04-23](https://workflow.telemetry.mozilla.org/log?dag_id=fivetran_intacct_historical&task_id=intacct-sensor-canada&execution_date=2022-04-22T02%3A00%3A00%2B00%3A00)).
With 17 Intacct syncs in Fivetran, if all the associated sensors were running for an hour and checking every 5 seconds it would result in 12,240 Fivetran API calls per hour.
Checking every 30 seconds instead would result in 2,040 Fivetran API calls per hour, leaving headroom for other Fivetran sensors.
=> Increase Fivetran sensor poke interval for Intacct syncs

dags/intacct_historical.py
Since sensors are starting before the actual Fivetran tasks, they seem to be taking up worker slots and preventing tasks from starting.
=> Use reschedule mode in Intacct Fivetran sensor

dags/copy_deduplicate.py
To better tolerate transient GCP issues, like how the `copy_deduplicate_main_ping` task failed twice and stopped on [2022-04-30](https://workflow.telemetry.mozilla.org/log?dag_id=copy_deduplicate&task_id=copy_deduplicate_main_ping&execution_date=2022-04-29T01%3A00%3A00%2B00%3A00).
=> Increase `copy_deduplicate` DAG task retries from 1 to 2

dags/glam.py, dags/glam_subdags/general.py, dags/glam_subdags/histograms.py
This is an attempt to fix subtasks that became stuck in Airflow. Tasks in these subdags need to run sequentially because they write to a single partition. Currently this is achieved by setting `concurrency=1` on a SubDAG level. This change makes tasks explicitly sequential and removes the concurrency setting.
=> Bug 1774028 - Make repeated subdags in GLAM ETL explicitly sequential

dags/crash_symbolication.py
The crash_symbolication.top_signatures_correlations task is running out
of memory. This upgrades the instance type to make more available.
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1774415
=> Bug 1774415: upgrade instance type for crash_symbolication dag

dags/taar_daily.py, dags/taar_weekly.py
It updates the usage of addons API `https://addons.mozilla.org/api` from v3 to v4.
=> Bump taar image version

dags/utils/gcp.py
as of 2022-07-18T18:17:56Z `gs://spark-lib/bigquery/spark-bigquery-latest.jar` contains a jar for spark 3.1, but the parquet export job uses spark 2.4
=> Fix failing parquet export

bin/run, dags/glam.py, dags/glam_glean_imports.py
Do not commit until:
- Moves all of the glam/glean import jobs into one file, for easier updating.
- Uses TaskGroups to group Dev and Prod tasks into separate groups (viewable from Graph view)
Before:
After:
Note that the graph view isn't perfect, and doesn't display the fan in nature of the glean imports until you click on a taskgroup to expand it:
- Allows devs to change the image version for Dev only, so they can test changes to ETL without hitting prod
- This was set up in a way that adding a Stage env taskgroup is trivial (for the dag code at least, but requires infra changes another db, ip whitelist, sops secrets, etc.)
Open to any suggestions on how to do this differently
=> [DSRE-882] Create dev GLAM ETL Pipeline via WTMO

dags/kpi_forecasting.py
This is paired with https://github.com/mozilla/docker-etl/pull/67 
Adding the task for the mobile non-cumulative forecast and changing the desktop non-cumulative forecast to now depend on unified metrics
=> update forecasting dag

dags/search_term_data_validation.py
The following PR introduces a job for evaluating whether our recorded search terms are changing in ways that might invalidate assumptions on which we've built our sanitization model: https://github.com/mozilla/docker-etl/pull/73
THIS PR schedules THAT job. 
Things I need help on:
- Understanding whether this works and how to test it
- Whether I need to do anything to instantiate the `docker_image` located at the path mentioned in my `DAG`, and if so, what that is.
=> Add scheduling for the data validation metrics job

dags/publish_bqetl_static.py
Depends on https://github.com/mozilla/bigquery-etl/pull/3174 which moves the `publish_static` script into the bqetl CLI
=> Use bqetl CLI command to publish static files

jobs/socorro_import_crash_data.py
This updates the location of the telemetry socorro crash schema file so
the socorro-import job is using the correct one.
Fixes #1546
=> Fix socorro-import schema location (#1546)

dags/search_term_data_validation.py
Here is my thinking:
- No matter where we cd into, for some reason CI seems to want the root directory to be usr/app
- That's really fine, because pytest will run properly from there anyway
- I don't want to flatten the file structure artificially to get our scheduling tools to work properly
- So I am now running the job in airflow from outside the src location
=> Change location from which to run data validation job

dags/probe_scraper.py
to overwrite incorrect extra history introduced by nondeterministic behavior fixed in https://github.com/mozilla/glean_parser/pull/518 + https://github.com/mozilla/probe-scraper/pull/491
=> Temporarily disable update mode for gecko-dev

dags/taar_daily.py
It turned out the TAAR lite API has been returning an empty recommendations list for a while. The issue is that [this job](https://github.com/mozilla/taar_gcp_etl/blob/master/taar_etl/taar_lite_guid_ranking.py) writes an empty file to GCS even though it works on testing. I think it's because there is no data in `telemetry.addons` when it's being executed. A shift 1 day back should help. It is not critical to have a number of installations super precise.
=> Shift taar addons ranking date 1 day back

dags/probe_scraper.py
This adds a direct link to the last 12h of probe_scraper logs in Logs Explorer (retrieved via "Share link option in the UI). In case the link expires I'm keeping the instructions on how to get there from scratch.
=> Update probe_scraper DAG docs

dags/socorro_import.py, dags/utils/gcp.py
This PR fixes the dags:
1. parquet_export - by fixing the project_id references in dags/utils/gcp.py for dataprocOperators to change from derived-datasets to airflow-dataproc
2. socorro_import - by changing usage of BigQueryDeleteTableOperator to GKEPodOperator so that we can piggyback on existing permissions. Previously the airflow-access@derived-datasets SA had broader shared-prod permissions, so that workloads happening on the airflow worker pod could do things like BigQueryDeleteTableOperator to delete a socorro_crash partition. Now that we've switched to GKEPodOperator and the newer GKE airflow-gke cluster, the worker pod will use the airflow-gke-access SA to init a Pod on the airflow-gke cluster, and that Pod's container will have access defined by the default-workloads SA (which …
=> [DSRE-1056] Fix airflow dags after GKE migration

dags/utils/gcp.py
if this fails ill have to test it locally until it doesnt. but lets just quick try pushing this change
After the migration of WTMO jobs from the derived-datasets to airflow-gke/airflow-dataproc projects the parquet export dag's spark portion is failing with:
ERROR: Access Denied: Table moz-fx-data-shared-prod:telemetry_derived.clients_daily_v6$20221012: Permission bigquery.tables.get denied on table moz-fx-data-shared-prod:telemetry_derived.clients_daily_v6$20221012 (or it may not exist).
This is bc the export_to_parquet codepath in dags/utils/gcp.py created spark clusters without overriding the SA so the default compute SA is used and doesnt have read permisisons to shared-prod.telemetry_derived
=> [DSRE-1056] Explicitly set service account for dataproc jobs running via export_to_parquet

dags/operators/backport/fivetran/hook.py, dags/operators/backport/fivetran/operator.py, dags/operators/backport/fivetran/sensor.py
This replaces the backported fivetran connector with the newer version 1.1.2, to resolve issues that occur when FivetranOperator syncs finish quickly.
See #1530 -- this is the same as that except that I pulled over the operator and sensor code as well and added a comment to point to the exact commit.
For testing, I've run things locally and confirm that dags still parse; is there anything else I ought to do?
=> Upgrade backported fivetran connector to v1.1.2

airflow.cfg, plugins/backfill/main.py
The backfill plugin was working for re-running failed tasks. But there is a use case where a dev will add new tasks to an existing dag, e.g. for creating a new table, and then want to use the backfill UI to populate that table for historical data. This is failing because the backfill plugin was only working to re-run failed tasks that had already ran. 
Upon some investigation, the code path that the backfill cli cmd uses pickling (maybe new in v2 or sometime after I had wrote the backfill plugin originally) which was failing in this scenario (new dag task) as opposed to re-running the task manually in the UI which was succeeding (no pickling). So this PR fixes that. I've locally tested that the re-ran task uses code path similar to re-running via UI (non pickle)
Secondly this PR aims to …
=> [DSRE-1101] Fix backfill to not pickle so that newly added dag tasks can run via backfill

dags/data_monitoring.py
- Schedule changed to 7am UTC to make sure the job runs after bqetl processes (should be) finished.
- `fail_process_on_failure` flag added to the GKEOperator arguments to make the task fail if any dim checks fail.
- disabled email notifications for failures and retries to reduce noise.
=> feat: data monitoring DAG tweaked (schedule, email settings, and operator arguemnts

dags/data_monitoring.py
- cli param for date is now called `date`
- some tables have two day lag, to compensate for this passing ds - 1 day as the `--date` option value.
=> bug: corrected data param and passing in ds -1

.dockerignore, .gitignore, .vscode/settings.json, Dockerfile, Makefile, README.md, plugins/__init__.py
This PR fixes the error below. This was introduced in https://github.com/mozilla/telemetry-airflow/pull/1580 when the logic for backfill command generation was moved out of `plugins/backfill/main.py` to `dags/utils/backfill.py`. 
The issue is that Airflow adds `dags`, `plugins` and `config` to `sys.path` at runtime (ref [here](https://airflow.apache.org/docs/apache-airflow/stable/modules_management.html#built-in-pythonpath-entries-in-airflow)) but does not add the project directory `airflow_home`. 
Hence, imports between `plugins` and `dags` will fail in deployments but should work in your IDE since IDE's add the project directory, i.e. `airflow_home`, to `sys.path`.
```shell
telemetry-airflow-web-1        | [2022-11-17 16:42:41,954] {{plugins_manager.py:247}} ERROR - Failed to import …
```
=> fix(backfill): fix BackfillParams import issues

bin/run, dags/overwatch.py
- Added overwatch DAG
- Errors can be ignored for now since Overwatch is still in active development.
- 2 Airflow variables are required
1. `overwatch_image_version` set to `latest`.  Can be used to roll back release.
2. `overwatch_slack_token` used to publish reports to a Slack channel
=> DENG-470 adding overwatch DAG

dags/shredder.py
still handling the backlog
no longer running new jobs in the on-demand backfill projects, because the only remaining partitions in telemetry main are the ones that have failed ~45 times using on-demand slots, and all other shredder jobs are complete for this cycle, so there's an abundance of available reserved slots.
=> handle remaining shredder partitions via reserved slots

dags/bqetl_artifact_deployment.py
```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
self._prepare_and_execute_task_with_callbacks(context, task)
File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
result = self._execute_task(context, task_copy)
File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
result = task_copy.execute(context=context)
File "/usr/local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/kubernetes_engine.py", line 335, in execute
return super().execute(context)
File "/usr/local/lib/python3.7/site-packages/airflow/providers/cncf/kubernetes/operators/kubernetes_p …
```
=> Temporarily disable logs in publish views task

dags/bqetl_artifact_deployment.py
Currently, if the table deploy fails then view deploys will not get triggered. This PR makes a change to run the view deploy regardless of whether table deploys have failed or succeeded.
The main reason for this change is to ensure that views that are not related to a failing table deploy (e.g due to an incompatible schema) can still get deployed instead of being blocked. Views that depend on a table that failed to deploy will result in a failure during view deployment as well.
=> Run view deploy even if table deploy failed

dags/glam_glean_imports.py
Fixes [1804769](https://bugzilla.mozilla.org/show_bug.cgi?id=1804769)
This is the next step to make use of the fix implemented in [GLAM PR #2258](https://github.com/mozilla/glam/pull/2258).
A [release](https://github.com/mozilla/glam/releases/tag/2022.12.1) was created from that PR, which triggered a deployment process and now we have the image with the bug fix on GCR tagged `2022.12.1-37`
After this lands I will re-run the import task that failed (see bug) and see that it completes.
=> Bug 1804769: update glam glean import image to use fix

.circleci/config.yml
This is a follow up PR addressing small issues with the new CircleCI workflow that was introduced in the related PR.
- CI workflow ran all the time, it now only runs on branches other than main and not on tagged commits
- fix docker image including `docker.io`
* https://github.com/mozilla/telemetry-airflow/pull/1619
=> chore(ci): refine new workflow using orbs

dags/intacct_historical.py
The [Intacct Fivetran sync for "MOZ INC"](https://fivetran.com/dashboard/connectors/sage_intacct/sage_intacct_moz/status?requiredGroup=loading_reputation) is now taking longer than 3 hours.
This will fix [bug 1807699](https://bugzilla.mozilla.org/show_bug.cgi?id=1807699) "Airflow task fivetran_intacct_historical.intacct-sensor-moz failing since 2022-12-21".
=> Increase Intacct Fivetran sensor timeout to 6 hours (bug 1807699)

dags/graphics_telemetry.py
=> bug(1809624): graphics_telemetry tweaked to use git instead of pypi repostiory for installing moztelemetry

dags/shredder.py
because Kubernetes is killing it for using too much memory
=> Move shredder-all to highmem node

dags/bqetl_artifact_deployment.py, dags/data_monitoring.py, dags/mad_server.py, dags/probe_scraper.py, dags/taar_daily.py, dags/taar_weekly.py
Provides additional information around the DAG to make the triaging easier.
=> docs: added triage notes to dag docs for bqetl_artifact_deployment, mad_server and taar_weekly

dags/bqetl_artifact_deployment.py
Depends on https://github.com/mozilla/bigquery-etl/pull/3565
Should fix probe_scraper failures
=> Do not use cloud function when generating artifacts for deploy

bin/test-dag-tags.py, dags/backfill.py, dags/data_monitoring.py, dags/utils/tags.py
This is as part of the proposal to make changes to our current triage process to show that a DAG failure should be recorded/reported without any debugging.
=> added triage/record_only && triage/no_triage tags

bin/add_gcp_creds, bin/start_gke, bin/test-parse
Grepping for running containers with an `_` separator was failing under docker compose v2. This should make the bin scripts a little more universal.
=> Fix bin commands to run correctly under docker-compose v2 container naming scheme

dags/merino_jobs.py
300th time is the charm? I previously had the wrong values for bucket and prefix.
=> Lets try this again but with the correct bucket / prefix values

.circleci/config.yml
Add an integration test to validate local environment. Implementation persists image built in the docker build job and reuses it for docker-compose to save time by building once.
- builds the image, 
- save the image to a local artifacts directory,
- uses `persist_to_workspace` step to persist docker image artifact
- attach to artifacts workspace
- load docker image from previous job
- override docker-compose.yaml to use the image artifact instead of rebuilding
- start up local environment
* https://circleci.com/docs/workspaces/
* https://support.circleci.com/hc/en-us/articles/360019182513-Build-a-Docker-image-in-one-job-and-use-it-in-another-job
=> chore(ci): add integration test to validate local environment

dags/bqetl_artifact_deployment.py
We have three operations that need to happen before this:
1. Probe scraper DAG generates new schemas
2. Those schemas get deployed to BQ
3. Rebuild the bq-etl container to cache those stable schemas
Once that's done, the container we run to update artifacts should be up-to-date with the current state of things.
Associated nightly bq-etl build: https://github.com/mozilla/bigquery-etl/pull/3641
=> Delay bqetl artifact timing

dags/dap_collector.py
This adds collector job for fetching DAP (Distributed Aggregation Protocol) metrics.
`dap_auth_token` and `dap_hpke_private_key` variables are now set in Airflow.
=> Bug 1775035 - Add DAP Collector DAG

dags/merino_jobs.py, pyproject.toml
The job keeps failing on Monday because the upstream Wikimedia export is not ready when we try to download the file. So changing the date to Tuesday to improve our chances of download.
=> Change time of Merino job to Tuesdays

.circleci/config.yml
This PR adds image pushing to Google Artifact Registry (GAR) in preparation of the migration from `cloudops-infra` to `dataservices`. 
- Modified `docker-build-artifact` job to reuse the same job in the CI and CD workflows
- Add `publish-registry` to support pushing to GCR and GAR using the same job with different parameters
- Convert `publish-dockerhub` jobs to use `publish-registry` instead
- Add workflows to push tagged and untagged releases (latest) to GAR
- Use `make up` instead of duplicating logic for `docker-compose` integration test
:point_right:  [Successful publish jobs](https://app.circleci.com/pipelines/github/mozilla/telemetry-airflow/3836/workflows/6b96d518-34fd-41c6-bfb3-553e74cad6cc) pushing latest on GAR and GCR
`latest: digest: …
=> chore(ci): push image to GAR

dags/glam_dev.py
This has no prod impact. This is how the original glam etl dag works and is done to avoid exceeding resources on BQ. I'm test running the step `histogram_bucket_counts` on version-partitioned and clustered tables with a full dataset and it's exceeding resources, so I'm switching back to subdags.
Subdags are originally here to avoid one single step that processes too much data. In the past I made this a single step because I was testing with a sampled dataset. Now since I'm back testing with the full dataset I need the subdags back.
=> glam-dev: switching back to subdag for hist bucket counts 

dags/merino_jobs.py, resources/dev_connections.json
Merino needs the wikipedia index in both staging and production! This PR updates the Airflow configuration to add the production task.
The flow is that after the wikipedia index file gets copied over to GCS, both staging AND prod indexing can happen in parallel.
If someone close to the project could please check my math on which arguments needed to be switched to what for the staging job relative to prod, I'd be eternally grateful!
=> Add production step for wikipedia indexing

dags/glam.py
Upon discussion we want to see this thing running again with 10 substeps for result consistency sake.
=> glam - bucket_counts 10 substeps for another execution

plugins/mozmenu.py
=> docs(): updating airflow triage reference link + black formatting on mozmenu.py

dags/glam_dev.py
This is consistent with the DAG doc that says `Please disregard any failures from this DAG. It is being monitored by efilho`
=> Add no_triage tag to glam_dev DAG

dags/experiment_auto_sizing.py
Config for running the auto_sizing image was missing the required `dataset-id` parameter.
=> add dataset to run args

.circleci/config.yml, Makefile
Docker-compose v2.18.0 released a couple of hours ago and introduced a regression with our usage of `image` in `docker-compose.yaml`. We don't know when they'll fix it, so were pinning to the previous version for now.
Also fixes Fernet key generation which has been silently failing in CI probably since it was introduced.
=> fix(ci): pin docker-compose version

dags/update_orphaning_dashboard_etl.py, jobs/update_orphaning_dashboard_etl.py
This uses `mozfun.norm.truncate_version` to extract major version number and use it in subsequent version comparisons.
This is a legacy job that used the longitudinal dataset and back in the day was ported to BQ with a shim function. The approach taken here seems to be the simplest one allowing to minimize risk of breaking things. I have tested this in a sandbox cluster and confirmed that as far as I can tell reasonable statistics are now generated.
=> Fix update_orphaning job

dags/mozaggregator_prerelease.py
Reverts mozilla/telemetry-airflow#1620
Reason: Migrate aggregates.tmo data from AWS to GCP before decommission
=> Revert "Remove mozaggregator2bq export"

dags/probe_scraper.py
To catch issues in generation before they affect production.
=> Move lookml_generator_prod downstream of lookml_generator_staging

dags/data_monitoring.py, dags/fivetran_acoustic.py, dags/overwatch.py, requirements.in, requirements.txt
As discussed in the workgroup meeting, we need to disable catch up in preparation of the Airflow migration.
Re: `data_monitoring.py`, from  @kik-kik 
> The DAG operates on specific data partitions in target tables, and checks that they adhere to certain rules. So it is important that we guarantee that there is a run for each day
So I've updated the start_date to today.
Side effect of disabling `catchup` is some linting business.
=> fix: disable catch up and change start dates.

dags/dim_active_users_aggregates.py
The following mobile apps are being added:
- fenix
- focus_android
- firefox_ios
- focus_ios
This PR depends on:
- https://github.com/mozilla/dim/pull/85
- https://github.com/mozilla/dim/pull/84
- https://github.com/mozilla/dim/pull/83
- https://github.com/mozilla/dim/pull/81
=> feat(DENG-794): added mobile apps to the active_users_aggregates DAG

dags/intacct_historical.py
Adding documentation to the `fivetran_intacct_historical` DAG to reflect the fact that it is decommissioned.
=> [DENG-1003] Decommission Fivetran Intacct Sync

dags/probe_scraper.py
Glean dictionary utilizes data from both generated schemas, and from the lookml namespaces. This dependency will satisfy both.
=> Have glean_dictionary depend on lookml generation

dags/glam.py
Reverting docker img for certain steps [done here](https://github.com/mozilla/telemetry-airflow/pull/1675) to the original one.
=> glam: revert docker img

dags/firefox_public_data_report.py
This is mostly lint, main change is at the bottom.
Background in https://mozilla-hub.atlassian.net/browse/DSRE-1144?focusedCommentId=694637
https://console.cloud.google.com/functions/details/us-central1/data-ensemble-transposer-prod?env=gen1&project=moz-fx-data-ensembl-prod-0371&tab=metrics&pageState=(%22functionsDetailsCharts%22:(%22groupValue%22:%22PT6H%22,%22customValue%22:null)) seems to run hourly but it's only [configured](https://github.com/mozilla/ensemble-transposer/tree/main/config/datasets) to read datasets generated by this DAG. It's possible this behavior (and https://github.com/mozilla/ensemble-transposer/pull/231) are related to caching issues but if we notice them we can address them separately.
The bucket here is backing …
=> Add ensemble-transposer to airflow

dags/bhr_collection.py, dags/crash_symbolication.py, dags/firefox_public_data_report.py, dags/graphics_telemetry.py, dags/update_orphaning_dashboard_etl.py
#follows-up: https://github.com/mozilla/telemetry-airflow/pull/1732
I pulled the image locally and identified the correct path to `gsutil` binary:
```
docker run --rm -it --entrypoint bash google/cloud-sdk:435.0.1-alpine
[...]
ebc9fe389797:/# /usr/bin/gsutil
bash: /usr/bin/gsutil: No such file or directory
ebc9fe389797:/# which gsutil
/google-cloud-sdk/bin/gsutil
ebc9fe389797:/# /google-cloud-sdk/bin/gsutil
Usage: gsutil [-D] [-DD] [-h header]... [-i service_account] [-m] [-o section:flag=value]... [-q] [-u user_project] [command [opts...] args...]
Available commands:
[...]
```
This should fix the error in the Airflow tasks.
=> fix(DENG-951): updated gsutil command to use correct path for the image

dags/search_term_data_validation.py
You can see precedent for this solution in [this issue record](https://github.com/apache/airflow/issues/12136) as well as [this similar change](https://github.com/mozilla/telemetry-airflow/pull/1615) in this repo. 
I made a timeboxed effort (2 hours) at a more comprehensive solution, but couldn't do so without monkeypatching pieces of Airflow in a way that felt super brittle.
=> Temporarily remove logging from data validation DAG:

dags/search_term_data_validation.py
So what happened here was, Merino was pushing an ungodly amount of empty strings into the unprocessed search data, and a job that processes those was running way long and producing beaucoup jobs, and Airflow doesn't have a great failout for the log limit.
Nan has done us the favor of removing those empty strings in Merino logging going forward, and the hope is that this fix is no longer needed.
=> Undo log removal

dags/glam.py
Adds a non-normalized aggregation step and increases the number of `bucket_counts` tasks to 20 to avoid `out of slots` error
=> Glam non norm agg

dags/bqetl_artifact_deployment.py
We had some Airflow failures, because table deploys are scheduled after most of the ETL is already running. Scheduling it to run earlier
=> Change schedule interval of bqetl_artifact_deployment

dags/glam_glean_imports.py
Removing telemetry-alerts from alert recipient since it's causing too much noise and we already have a good amount of folks left in the `"email"` cfg to look at it.
=> Glam glean imports stops emailing telemetry-alerts to reduce noise

dags/graphics_telemetry.py
Follow-up of https://github.com/mozilla/telemetry-airflow/pull/1774
Updating GCS bucket with prod name after testing with nonprod.
Will be merged along with with https://github.com/mozilla/python_mozetl/pull/389
=> DENG-1025: gfx export to prod gcs bucket

dags/shredder.py, plugins/timetable.py, tests/test_timetable.py
the shredder dag is currently running every 28 days after it was turned on, and sometimes randomly adding new runs based on the current time.
This ensures that the dag will run at UTC midnight every 28 days after start_date.
created following this guide: https://airflow.apache.org/docs/apache-airflow/2.5.3/howto/timetable.html
=> Create custom timetable to run shredder every 4 weeks

dags/clean_gke_pods.py
according to the doc string the `clean-gke-pods` DAG can be ignored during Airflow Triage so I added the tag for that.
=> add no_triage tag to clean_gke_pods DAG

dags/search_term_data_validation_v2.py
This is a scheduled daily job to run search term data validation via [this container configuration](https://github.com/mozilla/docker-etl/compare/ctroy-replace-dataval?expand=1).
=> Run replacement data validation job daily at 8 AM

dags/merino_jobs.py
The Merino jobs are currently sending information just to Wil. We will like to change the jobs to send the info to our team in case there are any failures for the jobs.
=> [DISCO-2601] update ownership of merino_jobs to disco-team

dags/mozaggregator_mobile.py, dags/mozaggregator_prerelease.py
See also https://github.com/mozilla/python_mozaggregator/pull/242#issuecomment-1726721526
Most of this is `black`/`ruff`, the material changes are:
* For dataproc tasks that use `PIP_PACKAGES`, pin to https://github.com/mozilla/python_mozaggregator/compare/pbd_fix_2?expand=1 in an attempt to switch to the single pipeline family PBD table
* For container tasks that use the dockerhub image, move to a new image built manually via `build.sh` from https://github.com/mozilla/python_mozaggregator/compare/pbd_fix_2?expand=1, which simply patches the current `latest` image from dockerhub and uploads the result to our internal GCR repo
This isn't meant to be a long term fix: it's the least human-hours fix. The long term fix, going on 4 years now, is to deprecate `aggregates.tmo` and all of these …
=> Switch aggregates jobs to use workaround branch and image

dags/probe_scraper.py
Adding context for future triage so that issues like this https://bugzilla.mozilla.org/show_bug.cgi?id=1854405 may be resolved more easily.
=> Add to triage notes for probe_scraper DAG

dags/copy_deduplicate.py, dags/utils/gcp.py
We've been recently seeing Airflow declaring running GKE tasks as failed and retrying them. This results in multiple pods running per task run.
This change should stop Airflow from starting duplicate pod instances by reattaching retry runs to existing pods.
`reattach_on_restart` was originally defaulted to `False` in https://github.com/mozilla/telemetry-airflow/pull/1184. It seems fine to enable this now since `run_id` is one of the labels but out of caution this PR does not affect other DAGs.
=> Set reattach_on_restart=True in copy_deduplicate

dags/copy_deduplicate.py
Recently we've been seeing copy_deduplicate_all run time increasing. This might be related to introduction of split main ping tables that were deduplicated in this task. They should be moved to copy_deduplicate_main_ping to properly reflect dataset dependencies.
=> Deduplicate main_use_counter and _remainder outside of copy_deduplicate_all

dags/webcompat_kb.py
For scheduling https://github.com/mozilla/docker-etl/tree/main/jobs/webcompat-kb
=> Fixes #1823 - Add dag definition to schedule webcompat-kb job

dags/glam.py, dags/glam_fog.py, dags/glam_subdags/general.py, dags/glam_subdags/generate_query.py, dags/glam_subdags/histograms.py
Sets the `reattach_on_restart` flag to `True` for glam, glam_fog and glam_fenix DAGs in an effort to get rid of the `More than one pod running...` error.
=> Glam - reattach pods on restart

dags/glam_glean_imports.py
To avoid `More than one pod running with the same labels...` failures
=> glam_glean_import tasks reattach to pods on restart

plugins/mozmenu.py
This is a follow up to https://github.com/mozilla/telemetry-airflow/pull/1838
=> Add link to GKE cluster in top bar menu

dags/bqetl_artifact_deployment.py
The `bqetl query backfill` command takes care of instantiating these tables. Some tables (e.g. last_seen tables) have improper schemas when they are instantiated using artifact deployment.
=> Don't deploy glean_usage tables with artifacts

dags/graphics_telemetry.py
A new tag needed to be created in the source repo: https://github.com/mozilla/python_moztelemetry/releases/tag/v0.10.7
=> bug(1854406): updating python_moztelemetry package to use the new git tag reference

dags/graphics_telemetry.py
docs(): Updated graphics telemetry DAG docs
This is to indicate that we only care about the most recent run of the job.
=> docs(): Updated graphics telemetry DAG docs

dags/bhr_collection.py
Changing the original task to write the BHR data to GCS bucket. 
In the event of failure the PR will be reverted (There is a potential risk of data loss)
=> Change the bucket to gcp for bhr data and remove sync job

dags/data_monitoring.py
=> feat(DENG-2064): deprecating DIM checks for rolling_cohorts as they are no longer needed

dags/socorro_import.py
This updates the link to the Socorro GCP migration bug. It also restructures that paragraph so that the history of S3 buckets, what the DAG does now and what the DAG will do after the Socorro GCP project is done.
=> Update socorro_import.py overview comment

dags/data_monitoring.py
depends on: https://github.com/mozilla/bigquery-etl/pull/4641
=> feat(DENG-2063): deprecating DIM checks for telemetry_derived.active_users_aggregates_v1 as migrated to ETL checks

dags/dim_active_users_aggregates.py
depends on: https://github.com/mozilla/bigquery-etl/pull/4673
=> feat(DENG-1990): deprecated dim checks for active_users_aggregates mobile

Dockerfile
As per @mikaeld suggestion, we're going to try the following temp fix to unblock docker build failures:
https://github.com/apache/airflow/issues/36231#issuecomment-1857798655
=> fix():  Removing MySQL repo from our Airflow docker image sources due to incorrect GPG Key error

dags/dim_active_users_aggregates.py
depends on: https://github.com/mozilla/bigquery-etl/pull/4673
=> feat(DENG-1990): deprecated dim checks for active_users_aggregates firefox_desktop

dags/broken_site_report_ml.py
Link to the ETL job: https://github.com/mozilla/docker-etl/tree/main/jobs/broken-site-report-ml
=> Fixes #1889 - Add a dag definition to schedule broken-site-report-ml job

dags/bqetl_artifact_deployment.py
Depends on https://github.com/mozilla/bigquery-etl/pull/4792
Run initialization for queries that don't have a deployed table before deploying schemas.
=> Run query initialization before schema deploys

dags/bqetl_backfill.py
After https://github.com/mozilla/bigquery-etl/pull/4769 `no_partition` isn't required to backfill unpartitioned tables
=> Remove unnecessary no_partition parameter

dags/bqetl_artifact_deployment.py
This reverts #1843, because after #1858 the `glean_usage`-generated tables are no longer being auto-deployed via Airflow-scheduled `bqetl query backfill` commands, and now that #1893 deploys new tables with init logic using `bqetl query initialize` this should deploy the `baseline_clients_*` tables with correct schemas (at least after mozilla/bigquery-etl#4809 is merged).
=> Have `bqetl_artifact_deployment` publish new `glean_usage`-generated tables

dags/casa.py, dags/fivetran_acoustic.py, requirements.in, requirements.txt
This is to replace `airflow-provider-fivetran` Airflow Fivetran provider which has been deprecated last year.
The following PR should be merged in parallel: https://github.com/mozilla/bigquery-etl/pull/5015
=> feat(DENG-2682): Update fivetran imports to use airflow-provider-fivetran-async Airflow Fivetran provider

dags/casa.py, dags/fivetran_acoustic.py
This only makes sense now that we've switched to Astronomer's Fivetran Airflow provider package (https://github.com/mozilla/telemetry-airflow/pull/1922), which allows us to have a single task that both starts the Fivetran sync and waits for it to complete.
=> Limit Fivetran task concurrency so it only tries to run one sync per connector at a time

dags/bqetl_artifact_deployment.py
Views haven't been getting published for the `moz-fx-data-experiments` and `moz-fx-data-marketing-prod` projects, because calling `bqetl view publish` with the `--target-project` argument only considers views in the default `moz-fx-data-shared-prod` project.
=> Fix `bqetl_artifact_deployment.publish_views` to publish views in alternate projects

dags/bqetl_artifact_deployment.py
Related to https://github.com/mozilla/bigquery-etl/pull/5136
The `bqetl_artifact_deployment` DAG will be triggered by bigquery-etl changes so this ensures that only task is running even when multiple PRs get merged in a short period of time.
We are also removing the SQL generation to speed things up. bigquery-etl does contain the generated SQL and should be up-to-date enough when deploys are running
=> bqetl_artifact_deployment max_active_runs and remove SQL generation

dags/casa.py, dags/fivetran_acoustic.py
https://github.com/mozilla/telemetry-airflow/pull/1923 tried to limit Fivetran task concurrency so it would only run one sync per connector at a time, but that didn't actually work because task concurrency limits apparently don't apply when tasks get deferred (maybe an Airflow bug?). This will address that.
While having the operator be deferred while waiting for the Fivetran sync to complete would be ideal from an Airflow resource usage perspective, I believe having the sync behavior work as intended is more important, and having the Fivetran operator take up a worker slot while it's waiting shouldn't be a dealbreaker since that was the behavior until very recently when we switched to Astronomer's Fivetran Airflow provider package with its deferrable operator implementation …
=> Change Fivetran Airflow operators to run synchronously so the task concurrency limit is respected

dags/bqetl_artifact_deployment.py, dags/probe_scraper.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1821773
Fix the regex in the probe scraper notes and update the bqetl_artifact_deployment notes to point to logs explorer because gke has limited retention
=> Bug 1821773 - Update debugging notes for probe scraper and bqetl deploy

dags/bqetl_artifact_deployment.py
Reverts mozilla/telemetry-airflow#1931
Depends on https://github.com/mozilla/bigquery-etl/pull/5188
Removes SQL generation before artifact deploys
=> Revert "Bring back SQL generation in artifact deployments"

dags/operational_monitoring_backfill.py
Mark the `args` parameter in `operational_monitoring_backfill` as optional
=> feat: Make args parameter optional in operational_monitoring_backfill

dags/fivetran_acoustic.py
This PR fixes #1951 by changing the date format 
* [DENG-3082](https://mozilla-hub.atlassian.net/browse/DENG-3082)
Without specifying it the dates get exported as "01/02/2020 12:02:01 PM" which can't be parsed with SQL DATE()
[DENG-3082]: https://mozilla-hub.atlassian.net/browse/DENG-3082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: 1951 - acoustic suppression list date format

dags/bqetl_artifact_deployment.py
This PR makes an addition to the bqetl_artifcact_deployment DAG to also publish bq resources listed under the `data-observability-dev` project inside [bigquery-etl repo](https://github.com/mozilla/bigquery-etl/tree/main/sql/data-observability-dev).
This is to ensure that the resources used for testing data observability platforms undergo the same creation process and configuration to replicate our production settings as closely as possible.
Once the testing is complete these changes will be removed via: DENG-3102
* DENG-2863
* DENG-3102
=> feat(DENG-2863): add data-observability-dev to the list of projects covered by artifact_deployment

dags/fivetran_acoustic.py
This PR should really really fix the broken date format ... 
The attepted fix in #1952 added the quotation marks ending up with `"2023-07-10" 06:33 PM` datetimes 🙃 
This PR also hard codes the starting date for the suppression list DAG since we don't need to backfill from last year but will merge this with a one time download for historic data
* DENG-3082
=> fix: 1952 Acoustic Suppression List DENG 3082 date format

dags/shredder_backfill.py
Created for the tables for https://mozilla-hub.atlassian.net/browse/DENG-2854 but I went with handling the general case instead of hard-coding the list of tables so we can change it as needed and use it again in the future.
This allows serving of deletion requests outside of the predefined interval in the normal shredder run for a provided list of tables.  This only allows shredding of tables that are already being shredded based on the shredder config.
These are the accepted parameters:
Tested using the `moz-fx-data-gke-sandbox` project to verify arguments are correctly passed into the shredder command.
=> feat: Create shredder backfill dag

dags/mad_server.py
This PR changes the secret management of the `mad_server` DAG to Google Secret Management (DAG was previously using Airflow variables). 
* DSRE-1525
=> fix(dags): mad_server secrets are managed on GSM.

utils/gcp.py
We've been hit (again) by Airflow losing track of a running pod, restarting a task and failing with `More than one pod running with labels ...` error. We previously set some of the tasks to reattach to running pods on restart ([1], [2], [3]) which solved this problem for them. We didn't set it by default for all tasks back then to avoid situations where not-autodeleted pods are stuck with the old code. Now that DEs have permissions required to delete pods it seems safe to revisit this.
[1] https://github.com/mozilla/telemetry-airflow/pull/1820
[2] https://github.com/mozilla/telemetry-airflow/pull/1834
[3] https://github.com/mozilla/telemetry-airflow/pull/1837
=> feat: Default reattach_on_restart parameter to True in bigquery_etl_query function

dags/braze_gcs_to_bigquery.py
Trouble shooting #1963 
```
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/moz-fx-data-airflow-gke-prod/jobs?prettyPrint=false: Access Denied: Project moz-fx-data-airflow-gke-prod: User does not have bigquery.jobs.create permission in project moz-fx-data-airflow-gke-prod.
INFO - Marking task as UP_FOR_RETRY. dag_id=bqetl_braze_currents_to_bigquery, task_id=hard_bounce_2bq, execution_date=20240415T184511, start_date=20240415T184513, end_date=20240415T184514
ERROR - Failed to execute job 4708594 for task hard_bounce_2bq (403 POST https://bigquery.googleapis.com/bigquery/v2/projects/moz-fx-data-airflow-gke-prod/jobs?prettyPrint=false: Access Denied: Project moz-fx-data-airflow-gke-prod: User does not have bigquery.jobs.create permission in …
```
=> fix: DENG-3412 braze to bq add source format

dags/braze_gcs_to_bigquery.py
Trouble shooting https://github.com/mozilla/telemetry-airflow/pull/1963
```
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/moz-fx-data-airflow-gke-prod/jobs?prettyPrint=false: Access Denied: Project moz-fx-data-airflow-gke-prod: User does not have bigquery.jobs.create permission in project moz-fx-data-airflow-gke-prod.
INFO - Marking task as UP_FOR_RETRY. dag_id=bqetl_braze_currents_to_bigquery, task_id=hard_bounce_2bq, execution_date=20240415T184511, start_date=20240415T184513, end_date=20240415T184514
ERROR - Failed to execute job 4708594 for task hard_bounce_2bq (403 POST https://bigquery.googleapis.com/bigquery/v2/projects/moz-fx-data-airflow-gke-prod/jobs?prettyPrint=false: Access Denied: Project moz-fx-data-airflow-gke-prod: User …
```
=> fix: DENG-3412 braze to bq add gcp_conn_id

dags/firefox_public_data_report.py
This removes the dataproc operator in the hardware report and uses a biquery etl query and an updated hardware report job that doesn't use spark.  More context is in https://github.com/mozilla/firefox-public-data-report-etl/pull/27
This PR goes with
bigquery-etl: https://github.com/mozilla/bigquery-etl/pull/5332
firefox-public-data-report-etl: https://github.com/mozilla/firefox-public-data-report-etl/pull/27
* DENG-3277
=> feat: [DENG-3277] Replace dataproc usage in public hardware report

dags/bhr_collection.py, utils/dataproc.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1892258
This increases the memory used by the driver and executor processes.  Currently failing with
```
24/04/18 07:17:14 WARN org.apache.spark.scheduler.cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 1 for reason Container killed by YARN for exceeding memory limits.  10.6 GB of 10 GB physical memory used. Consider boosting spark.yarn.executor.memoryOverhead or disabling yarn.nodemanager.vmem-check-enabled because of YARN-4714.
```
Current default settings are `spark:spark.driver.memory=7680m` and `spark:spark.executor.memory=9309m`.  10 GB limit should be the executor memory + 10% from spark.yarn.executor.memoryOverhead. Each vm has 26 GB so it should be fine.
The extent of my testing was making sure …
=> fix: Bug 1892258 - Increase bhr_collection spark memory allocation

dags/bqetl_backfill.py
This PR adds the scheduling_parameters_override parameter to bqetl_backfill to support bqetl argument added here:https://github.com/mozilla/bigquery-etl/pull/5365 and backfill request in Jira ticket mentioned below.
-->
* [AD-243](https://mozilla-hub.atlassian.net/browse/AD-243)
[AD-243]: https://mozilla-hub.atlassian.net/browse/AD-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(bqetl_backfill): adding the bqetl_backfill scheduling_parameters_override parameter

dags/glam.py
This PR makes parameter names explicit while invoking `histogram_aggregates_subdag` from the GLAM DAG.
=> fix(glam): explicit params

dags/glam.py, dags/glam_glean_imports.py
This PR changes the current schedule of the `glam` ETL from 2am UTC to 1pm UTC to eliminate competition for slots with `glam_fog` and `glam_fenix`, now that the three DAGs are running under the same slot reservation.  
Downstream DAGs' schedules were updated in https://github.com/mozilla/bigquery-etl/pull/5609
* https://github.com/mozilla/glam/issues/2809
=> chore(glam): re-schedule glam legacy etl

dags/bqetl_backfill.py
This PR removes sandbox arguments added in error from previous PRs related to AD-243
=> fix(bqetl_backfill): sandbox arguments are still in main...need to be removed

.circleci/config.yml, README.md
This PR restricts the `manual-publish` workflow to non-`main` and tagged commits prefixed by `dev-`. CircleCI uses `OR` for multiple filter conditions, this is why we need a job that checks which branches it runs on.
Created a Github [release](https://github.com/mozilla/telemetry-airflow/releases/tag/dev-manual-release) with tag `dev-manual-release` which triggered this [workflow](https://app.circleci.com/pipelines/github/mozilla/telemetry-airflow/5533/workflows/b0b30e37-0fc1-4667-9b1b-483ef6b986fe) to push the image in GAR.
* DSRE-1658
=> chore(ci): Filter manual-publish workflows.

.circleci/config.yml
Fixes small typo from #1997. Job actually needs to fail if the workflow runs from the main branch.
* [DSRE-1658](https://mozilla-hub.atlassian.net/browse/DSRE-1658)
[DSRE-1658]: https://mozilla-hub.atlassian.net/browse/DSRE-1658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ci): Actually exit with error when `manual-publish` runs from main.

dags/glam.py, dags/glam_glean_imports.py
This PR changes `glam` schedule as an attempt to avoid jobs on `glam_fog` and `glam_fenix` from timing out due to competition for slots. 
* DSRE-1599
=> fix(glam): reschedule to give fenix and fog more time

dags/glam.py
This PR fixes the `execution_delta` of `glam` dag's upstream `copy_deduplicate` (missed in https://github.com/mozilla/telemetry-airflow/pull/2000).
=> fix(glam): fix wait for copy dedup exec delta

dags/bhr_collection.py
Follow up for https://github.com/mozilla/telemetry-airflow/pull/1995 where memory was increased from 15g to 24g.  This results in the error `Required executor memory (24576), overhead (2457 MB), and PySpark memory (0 MB) is above the max threshold (24576 MB) of this cluster` so lowering to 20g
=> fix: Set bhr_collection spark memory to 20g

dags/eam_workday_xmatters_integration.py
Description:
The on_failure_callback set in the DAG is not being called when the task fails. 
Moving it to default_args.
=> fix(DAG): Workday-XMatters [ASP-4631] - Changes in the on_failure_callback

dags/microsoft_store.py
=> feat(microsoft_store): initial add microsoft_store DAG

dags/microsoft_store.py
=> fix: microsoft store DAG update when DAG runs to day before actual date

dags/bhr_collection.py
bhr_collection_child is failing because of occasionally higher volume of bhr pings so slightly decreasing the sampling ratio and increase workers/mem pool
* https://bugzilla.mozilla.org/show_bug.cgi?id=1904695
=> fix(bhr): Update bhr_collection_child worker count and sampling

dags/looker.py, dags/probe_scraper.py
This moves the lookml generation out of the `probe_scraper` DAG into a new `looker` DAG. Having a separate DAG will enable us to trigger lookml generation from the CI of the lookml-generator repository.
=> feat: Separate DAG for generating Looker artifacts

dags/dap_collector_ppa_prod.py
https://mozilla-hub.atlassian.net/browse/AE-364
related PRs:
* create tables & give airflow permission https://github.com/mozilla-it/webservices-infra/pull/2247
* create prod job that this will run https://github.com/mozilla/docker-etl/pull/217
this airflow job will run the new prod etl.
https://workflow.telemetry.mozilla.org/dags/dap_collector_ppa_dev/grid is now working (had to fix a permissions issue, the airflow & docker etl were both OK)
=> feat(dags): Add DAP collector for PPA Prod

dags/search_forecasting.py
=> fix: for search_forecasting remove execution delta as upstream job already applies 7 day lag

dags/glam.py
This PR fixes a bug introduced in https://github.com/mozilla/telemetry-airflow/pull/2019, which removed the step that builds `extract` tables along with steps to export data to GCS.
Bringing back the step erroneously removed as a `TaskGroup`  instead of a `SubDag`, because the latter is deprecated.
=> fix(glam): build extract tables as TaskGroup

dags/glam_glean_imports.py
This PR  fixes a dependency that `glam_glean_imports` has on `glam`. The task depended on in the latter DAG became a TaskGroup.
=> fix(glam_imports): Wait on TaskGroup instead of task

dags/probe_scraper.py
Not sure what this is but upstream rally stuff was removed in https://github.com/mozilla/probe-scraper/pull/781
* DSRE-1173
=> chore: remove search engine usage study

dags/glam.py
See also: https://github.com/mozilla/bigquery-etl/pull/5935
This PR removes the `clients_non_norm_histogram_bucket_counts` step from the GLAM DAG. The aggregations for both normalized and non-normalized data will now be both done at `clients_histogram_bucket_counts`.
* https://github.com/mozilla/glam/issues/2896
=> chore(glam): remove non-normalized bucket counts

dags/glam.py, dags/glam_fenix.py, dags/glam_fog.py
This PR removes steps that calculate percentiles from the GLAM dags.
Percentiles will be calculated ad hoc from now on for cost savings
See also: https://github.com/mozilla/bigquery-etl/pull/5957
=> refactor(GLAM): Remove percentile calculation

plugins/timetable.py
This PR fixes [this error introduced in this PR](https://github.com/mozilla/telemetry-airflow/pull/2052/files#diff-6bc3f0b18e373dee50a3699d36a6afa83d65925836689c2a4a71b4161470c659)
* None
Local env
=> fix(plugins): Use tuple for timetable plugin registration

dags/glam.py
This PR changes the billing project of `glam_sample_counts` from `glam-prod` to `shared-prod`, which will allow some cost reduction due to taking advantage of a different billing type.
* DSRE-1599
=> refactor(GLAM): run sample_counts on shared-prod

dags/glam.py
This PR makes GLAM ETL use a query for each extract job. 
* https://bugzilla.mozilla.org/show_bug.cgi?id=1910670
=> chore(GLAM): extracts no longer parametrized

dags/dbt_daily.py, requirements.in, requirements.txt, resources/dev_connections.json
Related to https://github.com/mozilla/mozdbt/pull/11
This adds a new DAG to trigger dbt cloud runs and installs dbt operator packages. For now the dbt runs depend on copy deduplicate + some extra time in between. As we get actual use cases this might change. But for now this DAG is for testing out some things
=> Schedule daily dbt runs

dags/eam_workday_everfi_integration.py
Go-live preparation: Changed the Jira link to production — removed tag no_triage.
[Jira ticket ASP-5115](https://mozilla-hub.atlassian.net/browse/ASP-5115)
[Epic ASP-4744](https://mozilla-hub.atlassian.net/browse/ASP-4744)
=> feat(url):[Workday/Everfi]Changed the Jira link to prod. Removed tag no_triage.

dags/dbt_daily.py, resources/dev_variables.json
The dbt account ID needs to be specified as part of the DAG config. This ID is not secret so it's fine to have it in an environment variable. It's more convenient to store it in a variable for other DAGs triggering dbt to reference it.
=> fix(dbt_daily): Set dbt account ID

dags/probe_scraper.py
As called out in mozilla/probe-scraper#790 this PR is necessary to address the lack of a way to run the GH workflow for Thunderbird ([docs](https://mozilla.github.io/glean/book/user/adding-glean-to-your-project/enable-data-ingestion.html#validate-and-publish-metrics)). Given that TB uses Mercurial/Git Mirror, I'm replicating the same mechanism used for Firefox Desktop.
* https://bugzilla.mozilla.org/show_bug.cgi?id=1910995
=> feat: Bug 1910995 - Enable the detection of TB metrics

dags/eam_workday_xmatters_integration.py
This PR adds the triage/record_only tag, as well as the repo tag and some docstring to the DAG to improve triage
=> docs: add tags to eam_workday_xmatters_integration_dag

dags/probe_scraper.py
switch the owner from Linh to jrediger for the `glean_dictionary_netlify_build` task in the `probescraper` dag
=> fix: change owner for probe scraper dag glean dictonary task

dags/bqetl_artifact_deployment.py
Follow up to https://github.com/mozilla/bigquery-etl/pull/6081, will fix one of the issues currently affecting artifact deployment.
=> feat: remove data-observability-dev from artifact deployment

dags/looker.py
This adds a new task to the `looker` DAG which runs content validation on KPI dashboards and related explores via `spectacles`
=> feat: Add Looker content validation for KPI related dashboards and explores

dags/looker.py, resources/dev_variables.json
This PR switches from referencing secrets to referencing existing Airflow variables to pass the client secret for LookML validation. Previously the referenced secrets appeared in clear text in the logs. This change will ensure that they are masked
=> fix: Using Airflow variables for LookML validation

dags/looker.py
So the Looker base URL, client ID, and client secret don't need to be passed as command line arguments.
* Follow-up to #2076.
=> refactor: Change `lookml_validate_spectacles` task to use environment variables that Spectacles expects

dags/fxci_metric_export.py
The underlying ETL is switching to explicitly passing in the date, so adjust accordingly.
* Bug 1912067
=> fix: update fxci_metric_export dag to pass in --date

dags/fxci_metric_export.py
There's a check in the code that prevents the export from running too close to midnight. This is because there's a slight lag in the Google Cloud Monitoring data becoming available.
Running 30 minutes past the hour should be plenty of buffer time.
=> fix(fxci): change fxci metric export schedule to run at 00:30

dags/bqetl_artifact_deployment.py
Publish tables and views in the `moz-fx-data-bq-people` project.
mozilla/private-bigquery-etl#443 is adding an ETL that writes to a new table in the `moz-fx-data-bq-people` project, and that table will need to be deployed before the ETL script can run.
* DSRE-1714: Creating table snapshots in moz-fx-data-bq-people
=> feat: Publish tables and views in the `moz-fx-data-bq-people` project (DSRE-1714)

dags/glam_fog.py, utils/glam_subdags/generate_query.py
This PR runs GLAM FoG ETL's `histogram_bucket_counts` in sample ranges, because `release_histogram_bucket_counts` frequently goes over the 6h BQ time limit and has to retry, which spends more money.
Complements https://github.com/mozilla/bigquery-etl/pull/6150 to fix https://github.com/mozilla/glam/issues/2936. 
* https://github.com/mozilla/glam/issues/2936
=> chore(GLAM): Turn FoG histogram_bucket_counts into TaskGroup

dags/glam_fog.py, utils/glam_subdags/generate_query.py
This PR fixes the currently broken GLAM FoG and Fenix ETLs by passing a string parameters to the k8s pod instead of a boolean.
Error in [logs](https://workflow.telemetry.mozilla.org/dags/glam_fenix/grid?dag_run_id=scheduled__2024-09-03T02%3A00%3A00%2B00%3A00&task_id=view_org_mozilla_fenix_glam_release__view_clients_daily_histogram_aggregates_v1&tab=logs):
```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod in version \"v1\" cannot be handled as a Pod: json: cannot unmarshal bool into Go struct field EnvVar.spec.containers.env.value of type string","reason":"BadRequest","code":400}```
=> fix(GLAM): Fix glam gen query

utils/glam_subdags/generate_query.py
This PR fixes GLAM FOG `bucket_counts` by adding `--append_table --noreplace` whenever the flag `replace_table` is `False`
=> fix(GLAM): Add --append_table when needed to FoG bucket counts

utils/glam_subdags/generate_query.py
This PR fixes https://github.com/mozilla/telemetry-airflow/pull/2085 by passing a single parameter in quotes so it doesn't get interpreted as two parameters.
=> fix(GLAM): wrap bash params within quotes

dags/ga4_site_metrics_summary_backfill.py
On Friday, we moved the GA4 tables out of marketing-prod and into shared-prod.  As a follow-up to this PR, we need to update this secondary GA4 DAG to point to the new location for the www_site_metrics_summary_v2 table in shared-prod instead of the old location since the table is no longer there.
* Old location: `moz-fx-data-marketing-prod.ga_derived.www_site_metrics_summary_v2`
* New location: `moz-fx-data-shared-prod.mozilla_org_derived.www_site_metrics_summary_v2`
* [DENG-4152](https://mozilla-hub.atlassian.net/browse/DENG-4152)
[DENG-4152]: https://mozilla-hub.atlassian.net/browse/DENG-4152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(DENG-4142): Update from marketing-prod to shared-prod path

dags/looker.py
With https://github.com/mozilla/lookml-generator/commit/0ad7a716eff08431d392ebde97024dbd05b79278 lookml-generator has now the latest version of spectacles installed. So this line is no longer needed
=> Remove spectacles pip install

dags/bqetl_artifact_deployment.py
This adds a task to deploy Bigeye configs after all tables and views have been deployed. Depends on https://github.com/mozilla/bigquery-etl/pull/6194
https://mozilla-hub.atlassian.net/browse/DENG-4605
=> feat(bqetl_artifact_deployment): Add task to deploy Bigeye monitors

dags/shredder.py
Enabling sampling for the derived desktop events tables.  Still in testing phase so using derived tables instead of main because it's easier to restore.  Using a separate task so that these queries can consistently run and I can see the impact quicker.
This depends on the creation of the temp dataset through https://github.com/mozilla-services/cloudops-infra/pull/5920
* DENG-4641
=> feat(shredder): [DENG-4641] Use sampling for derived events shredding

dags/glam_fenix.py
fixes: [1919047](https://bugzilla.mozilla.org/show_bug.cgi?id=1919047)
This PR adds the possibility to run GLAM fenix ETL's histogram_bucket_counts in sample ranges and prevent release_histogram_bucket_counts is going over the 6h BQ time limit.
* https://bugzilla.mozilla.org/1919047
=> chore(glam_fenix): Turn Fenix histogram_bucket_counts into a TaskGroup

dags/shredder.py
follow-up for https://github.com/mozilla/telemetry-airflow/pull/2093
Slots are approximately evenly distributed across queries so having `--sampling-parallelism` too high takes slots away from non-sampling queries.  Setting to 4 should make it closer to what it was without sampling
* DENG-4641
=> fix(shredder): Reduce sampling parallelism to 4

dags/shredder.py
This has been working correctly for event_events_v1.  Total slot time is consistently slightly lower than previous runs per partition and rows look to be correctly deleted so I'm comfortable with trying this on main which will give a better idea of impact because it won't contend for slots with other queries
more details in https://mozilla-hub.atlassian.net/browse/DENG-4641?focusedCommentId=937030
* DENG-4641
=> feat(shredder): Use sampling for shredder-main

dags/shredder.py
follow up for https://github.com/mozilla/telemetry-airflow/pull/2100
I actually meant to do 4 total concurrent queries at a time (2 queries each for 2 partitions) based on my testing here https://mozilla-hub.atlassian.net/browse/DENG-4641?focusedCommentId=934259.  It will be interesting to see how this affects runtime/slots in prod though
=> fix(shredder): Set sampling parallelism to 2 for shredder-main

dags/shredder.py
Main seems to be taking longer on lower volume days (weekends) which offsets any small improvements for the other days.  Also storage costs for the temp dataset are higher than I expected so removing this while I try a workaround, otherwise it's not worth it.
* DENG-4641
=> chore(shredder): Stop shredder sampling for main

dags/looker.py
DSRE doesn't take an action based on these failures.
=> chore(looker): remove dataops from owners

requirements-override.txt
Patch k8s provider to version 8.3.4 to fix the issue of executor open slots reaching negative number
_new provider installed_
_running clean_gke_pods_
* https://github.com/apache/airflow/pull/39551
* https://github.com/apache/airflow/issues/36998
* https://github.com/apache/airflow/issues/40106
=> fix(providers): Upgrade to kubernetes provider 8.3.4.

dags/bhr_collection.py
Job is failing likely due to running out memory possibly related to a ~15% increase in hangs on this thread: https://sql.telemetry.mozilla.org/queries/102988/source#253834
I think increasing workers will work and cost shouldn't be an issue since the runtime is less than an hour and should decrease with more workers.
* https://bugzilla.mozilla.org/show_bug.cgi?id=1924694
=> fix(bhr): Increase bhr_collection_child cluster size to 10

dags/bqetl_artifact_deployment.py
Requires https://github.com/mozilla-services/cloudops-infra/pull/5736. We should then be running bqetl artifact deploys after every merge to main and every new schemas deploy. Note that on days where there are no schemas updates/bqetl merges, this DAG won't run, so if there is some reason to keep a fallback scheduled this shouldn't land as-is.
* DENG-2963
=> chore(bqetl_artifact_deployment): unschedule DAG

utils/gcp.py
This adds a new function to trigger Bigeye check runs via the `bqetl monitoring run` command. Using this over the provided Bigeye Airflow operators allows us to handle failures and warning differently, and to trigger custom SQL rules.
Depends on https://github.com/mozilla/bigquery-etl/pull/6383
https://mozilla-hub.atlassian.net/browse/DENG-5588
=> feat(bigeye): Add operator to trigger Bigeye runs from within bqetl

utils/gcp.py
Fixes a typo in `bigquery_bigeye_check`
=> feat(bigquery_bigeye_check): fix typo in bigquery_bigeye_check

dags/webcompat_kb.py
Since webcompat_kb was converted to a module in https://github.com/mozilla/docker-etl/pull/298#event-15123335703, the job is failing as it still trying to run a script, this PR fixes it.
=> fix: Change webcompat_kb DAG to run a module instead of a script

dags/kpi_forecasting.py
This PR updates the task names in the KPI forecasting DAG to align with the bqetl_analytics_aggregations DAG, which now uses versions in the naming.
The version should be updated together with table versions updates or depend on the view.
PR 1/2 for [Bug-1932176](https://bugzilla.mozilla.org/show_bug.cgi?id=1932176).
=> fix: Include version in task names to align with dependencies

requirements-override.txt, requirements.in, requirements.txt
Depends on https://github.com/mozilla/bigquery-etl/pull/6546 (to remove operator imports)
This removes the Bigeye dependencies that are no longer in use.
=> feat(bigeye): remove Airflow dependencies

dags/taar_daily.py
[Recent taar_similarity runs](https://console.cloud.google.com/dataproc/jobs/TAAR_similarity_7bec0ec5/monitoring?region=us-west1&project=airflow-dataproc) have been failing with `executor 4): java.lang.OutOfMemoryError: unable to create new native thread` so increasing the memory as a low-effort attempt to fix this.
Current defaults are:
```
spark:spark.driver.memory 7680m
spark:spark.executor.memory 38168m
```
* https://bugzilla.mozilla.org/show_bug.cgi?id=1931005
=> fix(taar): Allocate more memory in taar spark jobs

dags/taar_daily.py
Follow-up to https://github.com/mozilla/telemetry-airflow/pull/2129.  n2 instance types have restrictions on the number of ssds depending on # of vcpu so minimum is 4: https://cloud.google.com/compute/docs/disks/local-ssd#lssd_disk_options
Assuming cluster is alive for 25 minutes per run, additional daily cost should be `16 disks * $0.08 / GiB month * 375 GiB/disk / 43800 minutes/month * 25 minutes = $0.274` but performance improvements from n2 might offset that
* https://bugzilla.mozilla.org/show_bug.cgi?id=1931005
=> fix(taar): Set taar_similarity worker ssds to 4

dags/kpi_forecasting.py
This PR should only be merged after [PR-6539](https://github.com/mozilla/bigquery-etl/pull/6539).
Upgrades version for Desktop.
[DENG-6360](https://mozilla-hub.atlassian.net/browse/DENG-6360)
Please reference related Jira tickets, GitHub issues or Bugzilla. This repo has been 
configured to automatically insert hyperlinks for DSRE and DENG tickets.
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources
-->
[DENG-6360]: https://mozilla-hub.atlassian.net/browse/DENG-6360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: forecast DAG after complete backfill for desktop aua v4.

dags/bqetl_artifact_deployment.py
SQL generation currently requires ~4 GB of memory, and if we don't request at least that amount of memory then when the task tries to allocate more memory as it runs it's at the mercy of whatever memory is available on the node at that time, which might not be enough.
* DENG-6538: publish views and tables tasks occasionally gets stuck
=> fix(bqetl_artifact_deployment): Allocate more memory to tasks when they run SQL generation (DENG-6538)

dags/copy_deduplicate.py, dags/probe_scraper.py, dags/shredder.py
The previous way of specifying GKE container resource configs as a dictionary apparently doesn't work anymore. This PR switches to the new way using `kubernetes.client.models.V1ResourceRequirements` objects, which I've verified works in #2131.
* https://github.com/mozilla/telemetry-airflow/pull/2131
=> fix: Correct `GKEPodOperator` container resource configs so they work properly

dags/copy_deduplicate.py
This PR:
* Reduces the memory requested by `copy_deduplicate_all` to 400 MiB (in the past two weeks `copy_deduplicate_all` has [used at most 381 MiB of memory](https://console.cloud.google.com/monitoring/metrics-explorer;duration=P14D?pageState=%7B%22domainObjectDeprecationId%22:%22EBCB316F-CD77-43E5-A3DB-7258D717823F%22,%22xyChart%22:%7B%22constantLines%22:%5B%5D,%22dataSets%22:%5B%7B%22legendTemplate%22:%22Used%22,%22plotType%22:%22LINE%22,%22targetAxis%22:%22Y1%22,%22timeSeriesFilter%22:%7B%22aggregations%22:%5B%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22groupByFields%22:%5B%5D,%22perSeriesAligner%22:%22ALIGN_MEAN%22%7D%5D,%22apiSource%22:%22DEFAULT_CLOUD%22,%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22filter%22:%22metric.type%3D%5C%22kubernetes.io%2Fcontainer%2Fmemory%2Fused_byte …
=> fix(copy_deduplicate): Reduce `copy_deduplicate_all` pods' memory request from 10 GiB to 400 MiB

dags/probe_scraper.py
This PR:
* Reduces the memory requested by `probe_scraper_moz_central` to 4,500 MiB (in the past two weeks `probe_scraper_moz_central` has [used at most 4,472 MiB of memory](https://console.cloud.google.com/monitoring/metrics-explorer;duration=P14D?pageState=%7B%22domainObjectDeprecationId%22:%22C28BB218-E1FC-4457-987F-145DE2DB48C4%22,%22xyChart%22:%7B%22constantLines%22:%5B%5D,%22dataSets%22:%5B%7B%22legendTemplate%22:%22Used%22,%22plotType%22:%22LINE%22,%22targetAxis%22:%22Y1%22,%22timeSeriesFilter%22:%7B%22aggregations%22:%5B%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22groupByFields%22:%5B%5D,%22perSeriesAligner%22:%22ALIGN_MEAN%22%7D%5D,%22apiSource%22:%22DEFAULT_CLOUD%22,%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22filter%22:%22metric.type%3D%5C%22kubernetes.io%2Fcontainer%2Fmemo …
=> fix(probe_scraper): Reduce `probe_scraper_moz_central` pods' memory request from 13 GiB to 4,500 MiB

operators/gcp_container_operator.py
Currently we mark all GKE pods as `safe-to-evict` so that the presence of completed pods on a node doesn't prevent the cluster from scaling that node down.  However, that has the bad side effect of allowing the cluster to evict any _running_ GKE pods during scale-downs, prematurely killing whatever process/ETL it was running.  This PR fixes that situation by only marking GKE pods as `safe-to-evict` once they've completed (either successfully or failed).
N/A
=> fix: Only allow eviction of GKE pods after they've completed

operators/gcp_container_operator.py
Keeping the pods is already the default behavior, but the [underlying `GKEStartPodOperator` code](https://github.com/apache/airflow/blob/c92929b99fc15c42ccc0799cc696417a5af76161/airflow/providers/google/cloud/operators/kubernetes_engine.py#L643) warns that "_Current default is `keep_pod`, but this will be changed in the next major release of this provider._" So this ensures the current behavior will continue when we upgrade to the next major release of the Google Cloud Airflow provider.
NB: The [clean_gke_pods](https://github.com/mozilla/telemetry-airflow/blob/2db834930b56d7c332975c0af892c5e930613b62/dags/clean_gke_pods.py) DAG runs daily to remove completed pods, and we [add a `"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"` annotation to completed …
=> chore: Set `on_finish_action="keep_pod"` by default for GKE pods

dags/glam_fog.py, dags/glam_fog_release.py
The release aggregates table is being recalculated nightly, but release channel builds happen infrequently enough that we can reduce this cadence to weekly without meaningful loss in usability.
This PR extracts the second half of  `glam_fog` `release` to `glam_fog_release` and schedules the latter every Sat at 10am
* DENG-6752
=> feat(glam): Extract glam_fog_release

dags/looker.py
Running the branch deletion in parallel to the LookML validation did cause some errors: https://workflow.telemetry.mozilla.org/dags/looker/grid?dag_run_id=manual__2025-01-02T17%3A29%3A18.636250%2B00%3A00&task_id=validate_content_spectacles&tab=logs
The same Looker user is used for both tasks, switching to dev mode in the branch deletion task caused the validation task to fail, which was running at the same time. We can run the deletion after validation finishes
=> fix(looker): Run branch deletion after LookML validation

dags/search_forecasting.py
Updates `search_forecasting` DAG schedule to align with changed upstream DAG `bqetl_search_dashboard` schedule.
* `bqetl_search_dashboard` DAG schedule was changed here https://github.com/mozilla/bigquery-etl/pull/6586
=> fix(search_forecasting): reschedule search_forecasting to match bqetl_search_dashboard DAG

dags/bqetl_artifact_deployment.py, dags/glam.py, dags/glam_fenix.py, dags/glam_fog.py, dags/glam_fog_release.py
This PR (along with https://github.com/mozilla/bigquery-etl/pull/6819) replaces references to `moz-fx-data-glam-prod-fca7` with `moz-fx-glam-prod` in order to move GLAM ETLs to GCP V2. 
* DSRE-1783
=> chore(glam): move glam etls to moz-fx-glam-prod

dags/glam_fenix.py, dags/glam_fog.py, dags/glam_fog_release.py
This PR removes the `BUCKET` constant from `glam` dags. The constant is no longer used after https://github.com/mozilla/telemetry-airflow/pull/2141
=> chore(glam): remove unused constants

dags/bhr_collection.py
Last job recently failed with `Driver received SIGTERM/SIGKILL signal and exited with 137 code` which is a driver memory issue https://cloud.google.com/dataproc/docs/support/troubleshoot-oom-errors#master_node_or_driver_node_pool_job_terminations.  The highmem instance will have 64GB vs standard 32GB
This [process memory usage graph](https://console.cloud.google.com/monitoring/metrics-explorer;startTime=2025-01-20T04:37:34.595Z;endTime=2025-01-20T11:27:34.892Z?inv=1&invt=AbnXPQ&project=airflow-dataproc&pageState=%7B%22xyChart%22:%7B%22constantLines%22:%5B%5D,%22dataSets%22:%5B%7B%22plotType%22:%22LINE%22,%22targetAxis%22:%22Y1%22,%22timeSeriesFilter%22:%7B%22aggregations%22:%5B%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22groupByFields%22:%5B%5D,%22perSeriesAligner%22:%22ALIGN_MEAN%22%7 …
=> fix(bhr): Increase bhr driver memory

dags/glam_fog_release.py
By processing less samples at a time we decrease the risk of having the job run out of slots
* DENG-7590
=> fix(glam): further break down glam_fog_release bucket_counts

dags/glam_fenix.py, dags/glam_fenix_release.py
fixes https://github.com/mozilla/bigquery-etl/issues/6849
Following https://github.com/mozilla/telemetry-airflow/pull/2135, this PR extracts the second half of glam_fenix release to glam_fenix_release and schedules the latter every Sat at 10am.
The reason why I didn't make `glam_fog_release` and `glam_fenix_release` one single DAG is there may be a need to schedule them at different times, since `glam_fog_release` is already suffering from lack of resources. I might join them in the future
* DENG-7623
=> chore(glam): Extract glam_fenix_release to a different DAG

dags/bqetl_artifact_deployment.py
[DENG-7845](https://mozilla-hub.atlassian.net/browse/DENG-7845)
This automatically stops `publish_new_tables` tasks after 2 hours. We had some instances where these tasks ended up running for 7h+ and needed to be cleared manually. This should automate the process.
Normally the task runs for less than an hour
[DENG-7845]: https://mozilla-hub.atlassian.net/browse/DENG-7845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(bqetl_artifact_deployment): set task timeout for publish_new_tables to 2h

dags/bqetl_backfill.py
[This option](https://github.com/mozilla/bigquery-etl/blob/main/bigquery_etl/cli/query.py#L665-L672) might be needed for this backfill https://github.com/mozilla/bigquery-etl/pull/7009 if we use this dag instead of managed backfill so adding it preemptively
=> chore(backfill): Add override_retention_range_limit to bqetl_backfill

dags/bqetl_backfill.py
To allow using backfill slots.  By default this will use shared-prod
=> chore(backfill): Add billing_project to bqetl_backfill

dags/bqetl_backfill_complete.py, dags/bqetl_backfill_initiate.py
These tasks are expected to run long and we've had a couple recent issues where airflow lost connection to the pod and attempted to start a new backfill while the existing one was still running
* [DENG-7807](https://mozilla-hub.atlassian.net/browse/DENG-7807)
[DENG-7807]: https://mozilla-hub.atlassian.net/browse/DENG-7807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(backfill): [DENG-7807] Set reattach_on_restart on managed backfill tasks

dags/glam_fog_release.py
fixes [Bug 1944388](https://bugzilla.mozilla.org/show_bug.cgi?id=1944388)
This PR splits that 0 to 9 sample range for `histogram_bucket_counts` in an attempt to avoid running out of resources. This range has more data than the rest due to Windows + Release data being sampled at 10%.
* [Bug 1944388](https://bugzilla.mozilla.org/show_bug.cgi?id=1944388)
=> fix(glam_fog_release): redistribute bucket_counts sample processing

dags/bqetl_artifact_deployment.py
Following up on https://github.com/mozilla/telemetry-airflow/pull/2158, adding the timeout to publish views as well since it's also timing out. [most recent run](https://workflow.telemetry.mozilla.org/dags/bqetl_artifact_deployment/grid?dag_run_id=manual__2025-02-26T04%3A12%3A06.875837%2B00%3A00&tab=logs&task_id=publish_views)
* DENG-7845
=> chore(artifact_deployment): [DENG-7845] Add task timeout to publish_views

dags/fxci_metric_export.py, dags/fxci_pulse_export.py
I have a couple questions I'm hoping someone from the data org can answer before this lands:
1. My understanding is that these should go in the `fxci_derived` dataset instead of `fxci`. Then in bigquery-etl, there should be `view.sql` files that create the user facing views. Just want to verify, is this understanding correct?
2. Can we move the existing tables from the `fxci` dataset to `fxci_derived` right before this is deployed? What's the best way to do that? If this is tricky, I'd honestly be ok with losing that data. This ETL is just on the cusp of exiting the prototype phase, so there's nothing relying on this data quite yet.
=> fix(fxci): use 'fxci_derived' dataset

dags/shredder.py
https://github.com/mozilla/bigquery-etl/pull/6726 reduced the memory usage of shredder-all from ~20GiB to ~1.2GiB ([metrics explorer](https://console.cloud.google.com/monitoring/metrics-explorer;duration=P30D?pageState=%7B%22domainObjectDeprecationId%22:%22ABC5E843-216A-443B-853F-1DCF416BCCBC%22,%22xyChart%22:%7B%22constantLines%22:%5B%5D,%22dataSets%22:%5B%7B%22legendTemplate%22:%22$%7Bresource.labels.pod_name%7D%20mem$%7Bmetric.labels.memory_type%7D%22,%22plotType%22:%22LINE%22,%22targetAxis%22:%22Y1%22,%22timeSeriesFilter%22:%7B%22aggregations%22:%5B%7B%22crossSeriesReducer%22:%22REDUCE_MAX%22,%22groupByFields%22:%5B%22metric.label.%5C%22memory_type%5C%22%22,%22resource.label.%5C%22pod_name%5C%22%22%5D,%22perSeriesAligner%22:%22ALIGN_MAX%22%7D%5D,%22apiSource%22:%22DEFAULT_CLOUD%22,%22c …
=> chore(shredder): Set memory requests for shredder pods

dags/bqetl_backfill_complete.py, dags/bqetl_backfill_initiate.py
This should fix the failing Airflow tasks: https://workflow.telemetry.mozilla.org/dags/bqetl_backfill_initiate/grid?tab=logs&dag_run_id=scheduled__2025-03-13T19%3A00%3A00%2B00%3A00&task_id=detect_backfills
Regression from https://github.com/mozilla/telemetry-airflow/pull/2166
=> fix(bqetl_backfill_<...>) Fix backfill command arguments

dags/probe_scraper.py
Discussed in the Glean Platform Working Group meeting.
Sometimes the `trigger_looker` step that is the immediate upstream of `glean_dictionary_netlify_build` fails and we don't want it to block the Glean Dictionary daily build, because that prevents users from seeing newly added metrics.
* DENG-8049
=> chore(glean_dictionary): building  glean dictionary whether upstream fails or succeeds

dags/merino_jobs.py
We run the merino job with an increased amount of domains. When the job runs with roughly 1k domains, it succeeds. Increasing the domains to ~2.1k domains, the pod "disappears":
```
[2025-03-25, 22:01:43 UTC] {pod_manager.py:518} WARNING - Pod nav-suggestions-prepare-domain-metadata-prod-u1z3dxdi log read interrupted but container base still running. Logs generated in the last one second might get duplicated.
[2025-03-25, 22:01:44 UTC] {pod_manager.py:490} INFO - [base] None
unable to retrieve container logs for containerd://8d275b2803fa554db5126a152a11f9664be15ac9d9e94b84195bb6f74741dc21
[2025-03-25, 22:01:44 UTC] {pod.py:554} INFO - Found matching pod nav-suggestions-prepare-domain-metadata-prod-u1z3dxdi with labels {'airflow_kpo_in_cluster': 'None', 'airflow_version': '2.9.3', …
```
=> chore(merino): Set memory request for merino pods

dags/merino_jobs.py
We have a use case where even re-starting a DAG workflow doesn't use the latest docker image.
=> chore(merino): Make sure to always pull the latest docker image

requirements-override.txt, requirements.in, requirements.txt
Part of the instigation for doing this is that after upgrading WTMO to Airflow 2.10 (DENG-5881) there's been an issue with some task tries not showing in the main UI, and I believe I've identified that the `acryl-datahub-airflow-plugin`'s custom retry handler code is somehow the culprit (disabling the DataHub plugin in the local Docker Compose setup makes the problem go away).  I'm hoping upgrading to a newer version of `acryl-datahub-airflow-plugin` might solve that issue.
* DENG-5881: Upgrade WTMO to Airflow 2.10
=> chore: Upgrade `acryl-datahub-airflow-plugin` to v0.15.0.5

requirements-override.txt, requirements.in, requirements.txt
Reverts mozilla/telemetry-airflow#2181
In case this was the cause of the current Airflow outage.
=> fix: Revert "chore: Upgrade `acryl-datahub-airflow-plugin` to v0.15.0.5"

Makefile
This PR fixes the following error while running `make up` which affects CI:
```
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/circleci/project/logs
make: *** [Makefile:46: up] Error 1
```
=> fix: Create logs folder on root for local development

operators/gcp_container_operator.py
This makes the gke pod link in the task instance details work.  This is a workaround for https://github.com/apache/airflow/issues/46658 pending that being fixed and us upgrading the provider version.  I tested this with a sandbox gke cluster with both deferrable and non-deferrable operators.
I'm open to opinions on whether this is worth doing
=> fix: Fix GKE pod extra link for GKEPodOperator

docker-compose.yml, requirements.in, requirements.txt
We received the following message from Acryl today (emphasis mine):
> We have upgraded your instance to the Acryl DataHub SaaS release v0.3.10.2-acryl. This release brings in a lot of fixes and new features from OSS DataHub to you. Full changelog can be found in the release notes [here](https://datahubproject.io/docs/next/managed-datahub/release-notes/v_0_3_10) for v0.3.10.2-acryl release.
> If you are using remote executor please upgrade your image version to be v0.3.10.2-acryl. This is required so you are running the latest versions and do not face issues in Ingestion or Observability.
> **The recommended CLI to use with this release is 1.0.0.2. This applies for all CLI usages, if you are using it through your terminal, github actions, airflow, in python SDK somewhere etc.** This is a …
=> chore: Upgrade `acryl-datahub-airflow-plugin` to v1.0.0.2

dags/bhr_collection.py
Increasing the number of workers to see if this fixes out of memory errors.
Also removed some aws key references because they aren't used
* [Bug 1964987](https://bugzilla.mozilla.org/show_bug.cgi?id=1964987)
=> chore(bhr): [Bug 1964987] Increase bhr_collection_child to 12 workers

requirements.in, requirements.txt
We received the following message from Acryl on May 19:
> We have upgraded your prod [instance](https://mozilla.acryl.io/) to the Acryl DataHub SaaS release v0.3.11-acryl. This release brings in a lot of fixes and new features from OSS DataHub to you. Full changelog can be found in the release notes [here](https://datahubproject.io/docs/next/managed-datahub/release-notes/v_0_3_11) for v0.3.11-acryl release.
> If you are using remote executor please upgrade your image version to be v0.3.11-acryl. This is required so you are running the latest versions and do not face issues in Ingestion or Observability.
> The recommended CLI to use with this release is 1.0.0.3. This applies for all CLI usages, if you are using it through your terminal, github actions, airflow, in python SDK somewhere etc. …
=> chore: Upgrade `acryl-datahub-airflow-plugin` to v1.0.0.3

dags/glam_fenix.py, dags/glam_fog.py
Splits `clients_histogram_aggregates` and `clients_scalar_aggregates` release into TaskGroups to mitigate resource contention on `glam_fog` and `glam_fenix` DAGs.
* DENG-8731
=> chore(glam): split tasks on glam_fog and glam_fenix

dags/shredder.py
`firefox_desktop_stable.metrics_v1` shredder jobs are timing out after 6 hours so this changes it to per sample_id shredding.  This comes with some extra storage costs but it should at least work until I have have more time to look at this
The default table expiration on the `shredder_tmp` table should also be increased so jobs have more time to finish: https://github.com/mozilla-services/cloudops-infra/pull/6444
* DENG-8672
=> chore(shredder): [DENG-8672] Use per sample_id shredding for firefox_desktop metrics

dags/glam_fenix.py, dags/glam_fog.py
This PR complements https://github.com/mozilla/bigquery-etl/pull/7612
It creates clients_scalar_aggregates_new_v1 and clients_histogram_aggregates_new_v1 for the glam_fog and glam_fenix DAGs. The two tasks are extracted from clients_scalar_aggregates_v1 and clients_histogram_aggregates_v1 respectively. The intention behind this is to reduce resource contention on both DAGs. so if this refactor isn't enough I will add processing by samples on top of it.
* DENG-8798
=> chore(GLAM): aggregates_new for scalar and histogram

dags/probe_scraper.py
https://mozilla-hub.atlassian.net/browse/DENG-8344
Use mozilla-schema-generator image from GAR.
See also https://github.com/mozilla/mozilla-schema-generator/pull/288
=> [DENG-8344] Use mozilla-schema-generator image from GAR

requirements.in, requirements.txt
We received the following message from Acryl today:
> We have upgraded your prod [instance](https://mozilla.acryl.io/) to the Acryl DataHub SaaS release `v0.3.12-acryl`. This release brings in a lot of fixes and new features from OSS DataHub to you. Full changelog can be found in the release notes [here](https://docs.datahub.com/docs/managed-datahub/release-notes/v_0_3_12) for `v0.3.12-acryl` release.
> If you are using remote executor please upgrade your image version to be `v0.3.12-acryl`. This is required so you are running the latest versions and do not face issues in Ingestion or Observability.
> The recommended CLI to use with this release is `1.1.0.2`. This applies for all CLI usages, if you are using it through your terminal, github actions, airflow, in python SDK somewhere etc. …
=> chore: Upgrade `acryl-datahub-airflow-plugin` to v1.1.0.2.

dags/glam_fenix.py, dags/glam_fog.py
GLAM ETL will take a snapshot of `clients_histogram_aggregates` to read from in release, instead of updating the table "in place".
This allows us to split the job into tasks that process a chunk of samples each time with the first job overwriting the destination table and the subsequent ones appending to it.
Will be merged with https://github.com/mozilla/bigquery-etl/pull/7775
* DENG-9113
=> chore(glam): Split histogram_aggregates into sample-based jobs

dags/jetstream_rerun.py
During a Nimbus meeting it came up that some people are trying to trigger reruns by doing a noop on a experiment config (e.g. after an outcome changes, which doesn't trigger a rerun). It would be handy to have a DAG for these kinds of reruns, which would also allow for reruns of specific analysis periods
=> feat(jetstream_rerun): Add new DAG to trigger jetstream reruns

dags/bugzilla.py
https://mozilla-hub.atlassian.net/browse/DENG-9301
We have a sync set up to automatically create Jira tickets for Bugzilla bugs that have the whiteboard tag [dataplatform].As we are moving to tracking issues primarily in Jira, we’d like to ensure that anything opened in the Bugzilla [Data platform and tools product](https://bugzilla.mozilla.org/buglist.cgi?product=Data%20Platform%20and%20Tools&component=General&resolution=---&list_id=17652942) gets synced automatically to Bugzilla. This will require tagging new bugs periodically as done in this scheduled script
=> feat(bugzilla): Add DAG to tag bugs on Bugzilla to sync to Jira

dags/merino_jobs.py
This PR adds the Polygon image ingestion pipeline to the `merino_jobs` Airflow DAG. This schedules the ingestion task weekly to download ticker logos, upload them to GCS, and generate a finance manifest.
[DISCO-3633](https://mozilla-hub.atlassian.net/browse/DISCO-3633)
[DISCO-3633]: https://mozilla-hub.atlassian.net/browse/DISCO-3633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-3633] merino: add polygon image ingestion job

dags/firefox_public_data_report.py
See also https://github.com/mozilla/firefox-public-data-report-etl/pull/36
The URL of the docker image has changed
=> chore(firefox_public_data_report): update docker URL

requirements.txt
In particular, `pip-compile` now picks `mixpanel` v4.10.0 rather than v4.10.1, because v4.10.1 has apparently had its requirements retroactively changed to specify `requests>=2.32.5` which conflicts with Airflow's own `requests==2.32.3` requirement.
* [#data-platform-infra-wg Slack thread](https://mozilla.slack.com/archives/C01E8GDG80N/p1756144798488429)
=> fix: Rebuild `requirements.txt` to fix dependency conflict

dags/peopleintegration_workday_report.py
Use the right service account for GCS. See related cloudops-infra PR for tf code granting the correct role to the shared-prod service account.
* https://github.com/mozilla/telemetry-airflow/pull/2247
* https://github.com/mozilla-services/cloudops-infra/pull/6557/commits/9d0452409ef73f60121c817ec8698e4e743c33e6
=> fix(dags): Peopleintegration use airflow shared prod connection id.

dags/merino_jobs.py
This PR adds the FlightAware fetch schedules pipeline to the merino_jobs Airflow DAG. This schedules the fetch and store task every 6 hours to accumulate a cache of flight numbers for the flightaware integration.
* [DISCO-3716](https://mozilla-hub.atlassian.net/browse/DISCO-3716)
[DISCO-3716]: https://mozilla-hub.atlassian.net/browse/DISCO-3716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DISCO-3716] merino: add flightaware schedules job

dags/shredder.py
Details in DENG-9795.  The full delete statement is timing out after 6 hours and costing a lot.  Running them per partition makes it a lot more efficient so this creates a new task with `--max-single-dml-bytes=1`.  It's possible that setting a lower byte limit for the shredder-all will have improvements across the board but I haven't taken the time to test that.
* DENG-9795
=> fix(shredder): Create new task to force no dml on some tables
