ansible/deploy_local.yml
ansible/envs/dev.yml
ansible/envs/stage.yml
ansible/files/airflow/entrypoint.sh
ansible/files/spark/airflow.sh
ansible/provision_aws.yml
dags/example.py
dags/operators/emr_spark_operator.py
examples/spark/example_date.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vitillo/telemetry-airflow/8)

Various improvements.

---

ansible/files/airflow/airflow.cfg
dags/crash_aggregates.py
jobs/crash_aggregate_view.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vitillo/telemetry-airflow/10)

 Schedule crash aggregate view dataset with Airflow

---

dags/telemetry_aggregates.py
jobs/telemetry_aggregator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vitillo/telemetry-airflow/11)

Add telemetry aggregation job.

---

Dockerfile
ansible/deploy_aws.yml
ansible/deploy_local.yml
ansible/envs/stage.yml
ansible/files/airflow/airflow.cfg
ansible/files/airflow/entrypoint.sh
ansible/files/airflow/replace_env.py
ansible/files/docker-compose.yml

Per bug 1274968, setup smtp for alert delivery.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vitillo/telemetry-airflow/9)

Add SMTP configuration for alerting.

---

ansible/deploy_aws.yml

Oops
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vitillo/telemetry-airflow/12)

Fix indentation

---

Dockerfile
README.md
ansible/files/docker-compose.yml
dags/crash_aggregates.py
dags/example.py
dags/telemetry_aggregates.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vitillo/telemetry-airflow/13)

Use mozdata namespace for docker image.

---

dags/longitudinal.py

This depends on the longitudinal job running successfully to run.
needs-review: @vitillo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/21)

Add update orphaning job to Airflow

---

ansible/deploy_aws.yml
ansible/deploy_local.yml

Reverts mozilla/telemetry-airflow#22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/23)

Revert "Bug 1286825: Set num_runs for scheduler."

---

README.md
ansible/deploy_aws.yml
ansible/deploy_local.yml
ansible/envs/dev.yml
ansible/envs/stage.yml
ansible/files/docker-compose.yml
dags/client_count.py
dags/crash_aggregates.py
dags/longitudinal.py
dags/main_summary.py
dags/operators/emr_spark_operator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/24)

Support private & public visibility for output data.

---

ansible/deploy_aws.yml
ansible/deploy_local.yml
ansible/files/airflow/entrypoint.sh
ansible/files/docker-compose-local.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/25)

Bug 1286825: Wrap the scheduler in a retry loop

---

ansible/envs/dev.yml
ansible/envs/stage.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/26)

Update EMR release to 4.5

---

dags/crash_aggregates.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/28)

Let crash_aggregate_view jobs to run in parallel

---

README.md

r? @maurodoglio
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/29)

Add documentation for re-running a task

---

dags/mobile_clients.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/32)

Bug 1286242 - add mobile_clients dag

---

dags/longitudinal.py
jobs/addon_recommender.sh

r? @vitillo - Also, should you own this job or should I (or somebody else :-D)?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/35)

Schedule training the Addon Recommender

---

jobs/addon_recommender.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/36)

Add the missing backslash in addon_recommender.sh

---

dags/longitudinal.py

The scheduled notebook computes the data for the past week, and appends it to the current state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/34)

Schedule the game HW survey job

---

dags/bugzilla_dataset.py
jobs/bugzilla_dataset.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/31)

Bug 1286201 - add dag for bugzilla dataset update

---

dags/main_summary.py

Set the start date for this dataset back to the beginning of time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/37)

Bug 1275889 - Backfill main_summary v3

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/38)

Add documentation for backfill using the CLI

---

dags/longitudinal.py
jobs/cross_sectional_view.sh

Add configs for cross sectional view generation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/44)

Add configs for cross sectional view generation

---

ansible/files/spark/airflow.sh

Using pyspark + jupyter nbconvert to execute notebook seems to be more
standard and it's gonna be a safer choice for future versions of spark.
Plus, we don't depend on runipy anymore!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/45)

Bug 1304410 - Run ipynb using nbconvert

---

dags/addons.py
jobs/addons_view.sh

See also bug 1305184
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/46)

Bug 1300224 - Add scheduled dataset generation

---

ansible/files/airflow/airflow.cfg
dags/main_summary.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/48)

Bug 1306225 - Decrease default max dag runs to 5

---

ansible/files/spark/airflow.sh
jobs/telemetry_aggregator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/47)

Fix notebook timeout and batch python files execution

---

Dockerfile
dags/operators/emr_spark_operator.py

See
https://aws.amazon.com/premiumsupport/knowledge-center/emr-cluster-status-throttling-error/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/49)

Use exponential back-off for DescribeCluster

---

ansible/files/spark/airflow.sh

@vitillo r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/51)

Bug 1307092 - Allow whitespace in filenames

---

dags/sync_view.py
jobs/sync_view.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/53)

Add the sync pings view job on Airflow

---

dags/crash_aggregates_backfill.py

This dag will be removed/disabled once the backfill is done.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/54)

Bug 1305742 - add dag for crash aggregates backfill

---

dags/main_summary.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/62)

Bug 1312493 - Run Engagement Ratio job via Airflow

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/64)

Add instructions to fix deploy issues

---

dags/longitudinal.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/65)

Add distribution viewer task

---

dags/android_addons.py
dags/android_clients.py
dags/android_events.py

These jobs have been running for months on atmo v1, it's time to move
them to airflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/66)

Bug 1305423 - Add mobile jobs

---

ansible/files/spark/airflow.sh

@robotblake r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/63)

Bug 1312435 - Fix output directory for nbconvert

---

dags/mobile_clients.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/72)

Bug 1319810 - increase cluster size for mobile_clients

---

dags/telemetry_aggregates.py

@vitillo r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/73)

Add Frank to telemetry_aggregates email

---

dags/sync_view.py

So that I can get emails about failures, since I wrote a good chunk of that code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/74)

Update email field in sync_view.py

---

dags/telemetry_aggregates.py

@vitillo, r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/75)

Bug 1286868 - Update config for aggregates job

---

dags/main_summary.py
jobs/hbase_main_summary_view.sh

Please merge only after the relative PR in telemetry-batch-view has been merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/78)

Add ETL job for the HBase main_summary view

---

dags/crash_summary.py
jobs/crash_summary_view.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/81)

Bug 1335065 - Add crash_summary job

---

dags/telemetry_aggregates_fennec_backfill.py

The longest I've seen this run is 2 hours. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/82)

Bug 1336119 - Add telemetry aggregates fennec backfill job

---

dags/telemetry_aggregates_fennec_backfill.py

GH, this was *way* more than "less than a minute ago"...
anyways, here ya go @sunahsuh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/83)

Change name of aggregates telemetry backfill DAG

---

dags/main_summary.py

Downstream from main_summary. Points at a gist -- is that OK?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/84)

Bug 1338615 - daily search rollup notebook

---

ansible/files/spark/airflow.sh

This location changed with https://github.com/mozilla/emr-bootstrap-spark/pull/68

Change python location

---

dags/sync_view.py
jobs/sync_events_view.sh

Adding the sync event view job to the daily sync dag now that we have approval from Mark H.

Add sync events view task to sync dag

---

dags/longitudinal.py

This also renames the job to "Firefox Hardware Report".

Add the HW report team mail to the "game_hw_survey" job

---

dags/spinner_severity_generator.py
jobs/run-severity-generator.sh

Tested this, ran successfully in ~5.5 hours on a 12 node cluster.

Add tab spinner severity job

---

dags/spinner_severity_generator.py

No comment. Urgh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/115)

Change tab spinner job script name

---

jobs/client_count_view.sh

After we do this we can remove the client_count t-b-v job.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-airflow/118)

Use generic count job for client_count

---

dags/focus_event_longitudinal.py
jobs/focus_event_longitudinal_view.sh

Tested in `telemetry-test-bucket`.

Add focus-event longitudinal job

---

dags/main_summary_backfill.py

Add catchup to main_summary_backfill

---

dags/main_summary.py
jobs/experiments_main_summary_view.sh

Kept the timeout and instance_count the same as main_summary to make this largely future-proof.

Add experiments main_summary job

---

dags/main_summary.py
jobs/experiment_main_summary_view.sh

Thanks for getting this scheduled yesterday, @fbertsch -- looks like the script failed due to pluralization

Fix classname typo

---

requirements.txt

Hopefully this "just works" with the package name change.

Bump airflow version

---

dags/android_addons.py
dags/android_clients.py
dags/android_events.py
dags/client_count.py
dags/mobile_clients.py
dags/telemetry_aggregates.py

Mobile ones should have been done ages ago.

Make Frank owner of his jobs

---

dags/main_summary.py

Increase number of nodes for main_summary

---

dags/quantum_rc.py
jobs/quantum_rc_view.sh

My job runs from the most previous Sunday to `date`, which should work as-is here because it looks like `date`s for weekly jobs are all Saturdays.

Add quantum release criteria job

---

dags/main_summary.py
jobs/search_rollups.sh

Update the name of the search script based on changes in
https://github.com/mozilla/python_mozetl/pull/52
Note that we need to co-ordinate the deploy of this change with merging the above PR.

Rename the search_rollups script

---

dags/main_summary.py
jobs/engagement_ratio.sh

The mozetl code has been tested locally but testing this diff locally has been intractable so far.

Bug 1370522 Migrate Engagement Ratio ETL to python_mozetl

---

dags/main_summary.py
jobs/hbase_addon_recommender_view.sh

The data will flow into the instance that was setup [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1383739).
@jasonthomas, is the `aws` part in the .sh file the correct way to get the host? I cargo culted this from the other hbase operator we have.

Add a job for filling the addon recommender HBase view

---

dags/main_summary.py

Bug 1392658: Increase timeout and instance count for Main Summary

---

dags/main_summary.py

This fixes what I broke in PR #161, I should have run the python code beforehand.

Add mozetl_envvar back into main_summary

---

dags/main_summary.py

Add bucket arg to heavy_users

---

dags/longitudinal.py

Hey Anthony, this PR is for scheduling the job you reviewed. This should run weekly, right after the longitudinal job, with the output being stored on a private bucket.

Schedule the TAAR locale job

---

dags/sync_view.py
jobs/sync_flat_view.sh

Please let me know if this is sufficient to schedule this to run regularly, I'm hoping it is, but it's partially/mostly a guess.

Bug 1381641 - Schedule the new SyncFlatView job to run daily

---

dags/longitudinal.py

Also decrease instance count, because this worked last time

Use Spark 2.2 for Longitudinal

---

dags/main_summary.py

This job takes care of checking for previous data itself.

Add heavy_users job

---

README.md

fixing small typos in README.md

fixing small typos in README.md

---

dags/android_addons.py
dags/android_clients.py
dags/android_events.py
dags/bugzilla_dataset.py
dags/client_count.py
dags/core_client_count.py
dags/crash_aggregates.py
dags/crash_aggregates_backfill.py
dags/crash_summary.py
dags/example.py
dags/focus_event_longitudinal.py
dags/longitudinal.py
dags/mobile_clients.py
dags/quantum_rc.py
dags/socorro_import.py
dags/spinner_severity_generator.py
dags/sync_log.py
dags/sync_view.py
dags/telemetry_aggregates.py
dags/topline.py
dags/txp_pulse.py

Addresses remaining items for #155

Clean up task names

---

dags/churn.py

This schedules churn_v3 as the primary churn dataset. This will run concurrently with the old v2 dataset. I have [bug open for decommissioning churn_v2](https://bugzilla.mozilla.org/show_bug.cgi?id=1409584).

Bug 1408162 - Schedule churn_v3

---

dags/client_count_daily.py
jobs/client_count_daily_view.sh

this will create a data set in `client_count_daily/v1/` partitioned by `submission_date`
r? @mreid-moz

Bug 1412971 - Create incremental client_count_daily data set

---

jobs/client_count_daily_view.sh

as per [Bug 1413515 Comment 3](https://bugzilla.mozilla.org/show_bug.cgi?id=1413515#c3)

Bug 1412971 - restore e10s_enabled to client_count_daily

---

Dockerfile
README.md
circle.yml

- Modify airflow conf to EFS dag mount
- add circle ci simple test for dag compilation

[Bug 1362229] Add PR tests for dag compilation

---

requirements.txt

bumping version to 1.8.2

---

dags/sync_view.py

This moves the job away from ATMO.
j-1NNWQICGEDLFI contains the log with the successful test from airflow.
```
INFO:mozetl.sync.bookmark_validation:Processing sync bookmark validation for 20171122
INFO:mozetl.sync.bookmark_validation:Saving table bmk_validation_problems on start_date 20171122 to s3://telemetry-test-bucket/sync/bmk_validation_problems/v1/start_date=20171122
INFO:mozetl.sync.bookmark_validation:Saving table bmk_total_per_day on start_date 20171122 to s3://telemetry-test-bucket/sync/bmk_total_per_day/v1/start_date=20171122
```

Bug 1374831 - Schedule Sync bookmark validation job to run on Airflow

---

dags/churn.py
dags/main_summary.py

See https://github.com/mozilla/python_mozetl/pull/174

Bump instance counts in churn/retention

---

dags/main_summary.py
jobs/experiments_error_aggregates_view.sh

Don't merge yet, I need to:
1. Finish backfilling and move those files over
2. Ensure the experiment analysis job can handle the data
A PR coming for t-b-v in a bit, after some testing.

Add experiments_error_aggregates batch job

---

dags/main_summary.py

@sunahsuh I've added the TAAR dynamo job here as a dependency on the main_summary.
Am I missing something to schedule this daily?

Added DAG entry for TAAR dynamo loader.

---

jobs/probe_scraper.sh

Depends on https://github.com/mozilla/emr-bootstrap-spark/pull/261

Updates to probe_scraper.sh - Bug 1444942

---

dags/taar_amodump.py

We need both the jobs in taar_amodump to run on a daily schedule

Changed taar_amodump from weekly to daily

---

jobs/client_count_daily_view.sh

Blocked on [main_summary backfill](https://bugzilla.mozilla.org/show_bug.cgi?id=1438927)

Bug 1419815 - Use normalized_os_version in client_count_daily

---

dags/main_summary.py

Bleh. Forgot to change the URI when I switched over to the common runner.

Fix uri for experiment analysis view task

---

dags/main_summary.py

don't want to interrupt the existing clients_daily dataset, so adding a new task for it

Add clients_daily_v6 job

---

dags/events_to_amplitude.py
dags/main_summary_backfill_mar_2018.py
dags/operators/emr_spark_operator.py
dags/utils/deploy.py
dags/utils/tbv.py
jobs/telemetry_batch_view.py

@relud  you may want to take a look as well, since you made these scripts.

t-b-v deploy using artifacts

---

jobs/probe_scraper.sh

For https://bugzilla.mozilla.org/show_bug.cgi?id=1460141#c8
r?

Verify OUTPUT_DIR is not empty before sync Bug 1460141

---

dags/taar_amodump.py

This adds the taar_llite ETL job to the taar_amodump DAG.

added taar-lite ETL job to the taar_amodump DAG

---

README.md

This codifies my recent experience in testing t-b-v changes using Airflow.

Additional documentation on options for testing DAGs and tasks

---

README.md

Some more precise language in README

---

dags/telemetry_aggregates.py
jobs/run_telemetry_aggregator.sh
jobs/telemetry_aggregator.py

Ran it with this method on 6/6 and it seems to have worked correctly, data is available per https://mzl.la/2JWvFhu

WIP: Aggregator deploy through egg

---

dags/longitudinal.py

@harterrt for review as bugzilla component owner

Bug 1444413 - remove cross_sectional

---

dags/mango_log_processing.py

This change adds a DAG to process AMO dev and stage logs.
r?

Bug1450108 -  Process Dev and Stage AMO nginx logs using EMR Mango

---

dags/events_to_amplitude.py

This gets the devtools amplitude job scheduled on a provisional basis as the devtools team works on changes in nightly to debug some issues that have come up. My plan is to put the dev api key under the prod location right now, and then once we get the go-ahead, we can up the instances, remove the channel filter in the config file and change the api key to the prod project's

Add devtools events to amplitude job

---

dags/telemetry_aggregates.py
jobs/telemetry_aggregator.py

I do have a concern about overloading the database, but we use a read-replica so we can handle that later, if it happens.

Aggregate release telemetry

---

dags/operators/emr_spark_operator.py

Fix unicode issues in airflow emails

---

dags/android_addons.py
dags/android_clients.py
dags/android_events.py
dags/mobile_clients.py
dags/sync_log.py
jobs/ImportSyncLogs.ipynb
jobs/android-addons.ipynb
jobs/android-clients.ipynb
jobs/android-events.ipynb
jobs/mobile-clients.ipynb

mozilla-reports is getting restructured and made private, so
we won't be able to rely on the uri for the ipynb anymore.
We may also be able to deprecate this job completely soon.
This would unblock https://github.com/mozilla/mozilla-reports/pull/91 and related work.

Move android-addons.ipynb into this repo from mozilla-reports

---

dags/landfill.py

`santitized` should be `sanitized`

Fix typo in the output prefix of the landfill-sampler

---

dags/main_summary.py
jobs/telemetry_batch_view.py
plugins/moz_databricks.py

A few related changes to the Databricks operator, paralleled to telemetry-batch-view.py for consistency.

Bug 1391307 - Run main summary with all histograms

---

dags/longitudinal.py

This adds the longitudinal view to statuspage.

Add longitudinal to statuspage

---

dags/events_to_amplitude.py

This should be merged after https://github.com/mozilla/telemetry-streaming/pull/224

Send Fennec iOS events to Amplitude

---

dags/run_test_emr.py
dags/test_email.py
jobs/run_test_emr.sh

Will remove later.  Just want to run a quick check on dag execution now that we will use mysql backend.

Re-add test dags since we've switched to mysql on gke

---

airflow.cfg
requirements.txt
webserver_config.py

manual workaround was required to get this working (AIRFLOW-2321)

Fixing google oauth for rbac

---

dags/utils/gcp.py

This will ensure that when bq load is re-triggered we won't end up with duplicate data. This should resolve bug 1545772.

Remove bq partitioned table before attempting to load new data

---

dags/utils/gcp.py

Add missing task_id for remove_bq_table

---

dags/direct2parquet_bigquery_load.py
dags/sql/core_clients_daily_v1.sql
dags/sql/core_clients_last_seen_v1.sql
dags/sql/firefox_nondesktop_exact_mau28_raw_v1.sql

This is a continuation of https://github.com/mozilla/telemetry-airflow/pull/465 but for D2P datasets. 
Before we merge we will need to configure `aws_prod_iam_s3` connection in WTMO Airflow.
I've tested this locally.  r?

Import direct2parquet bigquery load jobs

---

dags/fxa_events.py

Fix datetime class reference

---

dags/mango_log_processing.py

Add Blocklist ping ADI to gcs/bigquery

---

dags/sql/clients_last_seen_v1.sql

removed columns `generated_time` and `last_seen_date`
blocked on the back fill completing and being copied into place

Update clients_last_seen_v1.sql for last backfill

---

dags/main_summary.py
dags/utils/gcp.py

and firefox_desktop_exact_mau28_by_dimensions_v1

Export clients_last_seen_v1 to parquet

---

dags/utils/gcp.py

because @relud miscounted 49+2 as 52 >_<

Limit cluster names to 51 total characters

---

dags/fxa_events.py

Bug: schema_update_options must be a tuple, not a list

---

dags/utils/gcp.py

- Convert tuple to list in bigquery-etl helper
- Add default for name in bigquery-etl helper

Fix bigquery-etl helper

---

dags/kpi_dashboard.py
dags/utils/gcp.py

I think this is more flexible and has fewer corner cases

Kpi dash counter

---

dags/kpi_dashboard.py
dags/utils/gcp.py

Depends on https://github.com/mozilla/bigquery-etl/pull/120

Add kpi_dashboard DAG

---

jobs/core_client_count_view.sh

Update telemetry-core-parquet from v2 to v3.

Bug 1551853 - Update source data version

---

dags/main_summary.py

Depends on https://github.com/mozilla/bigquery-etl/pull/151

Export clients_last_seen_raw to clients_last_seen Parquet

---

jobs/core_client_count_view.sh

Bug 1551853 - Fix up channel aliasing

---

dags/direct2parquet_bigquery_load.py

Needed to adapt to https://github.com/mozilla/bigquery-etl/pull/136
I have a backfill complete, so should be ready to deploy this tomorrow.

Run core_clients_last_seen_raw_v1

---

dags/main_summary.py

Select * from clients_last_seen

---

dags/taar_weekly.py
plugins/moz_databricks.py

This creates a weekly dag and attaches the taar_ensemble job to it. 
I also added some extra documentation around the `pypi_libs` initializer argument to MozDatabricksSubmitOperator.
Parameters to the MozDatabricksSubmitRunOperator are from: https://github.com/mozilla/python_mozetl/pull/321#issuecomment-475828726

Enabled the taar_ensemble weekly job

---

dags/main_summary.py

increase instance_count for bgbb_pred

---

dags/adi_dim_backfill.py

Will need to be executed via airflow backfill -s <date> -e 2019-04-17

New dag to backfill 10 years of adi processing from vertica

---

dags/fxa_events.py

Needed to match changes in
https://github.com/mozilla/bigquery-etl/pull/209

Run fxa_users_last_seen_raw_v1 rather than non-raw

---

dags/direct2parquet_bigquery_load.py
dags/fxa_events.py
dags/kpi_dashboard.py
dags/main_summary.py

Need to get https://github.com/mozilla/bigquery-etl/pull/219 merged first.

Schedule "smoot" ETL for the Growth and Usage dashboard

---

bin/run
dags/bq_events_to_amplitude.py
docker-compose.yml

@acmiyaguchi for the connections changes
@haroldwoo for the BQ pieces

Export Fenix events to Amplitude

---

dags/first_shutdown_summary.py

This should fix some of the intermittent timeouts that have been seen in `first_shutdown_summary`.

Bug 1566941 - Move away from EMR, and increase instance count and timeout

---

dags/bq_events_to_amplitude.py

The deploy environment isn't defined for that task, so we're using the env variable directly.

Fix deploy enironment string for amplitude load

---

dags/main_summary.py

fixes [this error](https://workflow.telemetry.mozilla.org/log?execution_date=2019-07-19T01%3A00%3A00%2B00%3A00&task_id=clients_last_seen&dag_id=main_summary)

fix clients_last_seen

---

dags/utils/gcp.py

Fix typo in parameter name

---

dags/direct2parquet_bigquery_load.py

Rename submission_date_s3 on clustered d2p tables

---

dags/utils/gcp.py

Fixes error introduced in #572

Fix python syntax error

---

dags/main_summary.py

`date_submission_col` needs to be updated to match hive partitioning date column. I've also added clustering and rename the date field to match main_summary. 
r?

Update to active_profiles import

---

dags/main_summary.py

Set ds_type to ds for active_profiles

---

dags/copy_deduplicate.py
dags/main_summary.py
dags/utils/gcp.py

Relies on https://github.com/mozilla/bigquery-etl/pull/262

Add bigquery_etl_copy_deduplicate tasks

---

dags/utils/gcp.py

Fix casing of --project-id param

---

dags/probe_scraper.py

I don't want to step on any toes here, but I also want to ensure this is running properly at all times since it's now a daily part of the pipeline deploy :)

Make frank owner of the probe-scraper

---

dags/utils/gcp.py

The `bq_table_name` should match what is being generated by parquet2bigquery or it will not be able to delete the table partition correctly.

Fix bq_table_name

---

dags/direct2parquet_bigquery_load.py
dags/fxa_events.py
dags/kpi_dashboard.py
dags/main_summary.py

Specify sql_file_path

---

dags/bq_events_to_amplitude.py
dags/operators/bq_sensor.py
dags/operators/gcs.py
dags/utils/amplitude.py
requirements.txt

- Check for data for base table or view
- Delete GCS data after upload
- Use a SubDag

Productionize generic Amplitude Ingestion

---

dags/direct2parquet_bigquery_load.py

Depends on https://github.com/mozilla/bigquery-etl/pull/337

Refactor glean_clients_daily to clients_daily in fenix datasets

---

dags/fxa_events.py

Supports https://github.com/mozilla/bigquery-etl/issues/348

Add fxa_oauth query

---

dags/fxa_events.py
dags/utils/gcp.py

Schedules new queries introduced in https://github.com/mozilla/bigquery-etl/pull/396

Add fxa_users_services queries

---

dags/socorro_import.py

This removes outdated comment, jobs are currently deployed automatically:
https://github.com/mozilla/telemetry-airflow/blob/master/.circleci/config.yml#L74

Remove outdated comment

---

dags/update_orphaning_dashboard_etl.py

Should be fine now, I tested this locally.

Add missing import to update orphaning dag

---

dags/update_orphaning_dashboard_etl.py
dags/utils/dataproc.py

Also: Allow adding custom properties to Dataproc clusters

 Add spark-avro package to update orphaning job cluster 

---

jobs/socorro_import_crash_data.py

Dataproc clusters are now using a later version of python 2

Fixing socorro python job

---

dags/copy_deduplicate.py
dags/main_summary.py

Schedules the bigquery-based events queries for eventual replacement of the current spark jobs

Add bq-based events jobs

---

dags/main_summary.py
dags/utils/gcp.py

fixes issues introduced in #654

fix misnamed vars and unused imports

---

dags/main_summary.py
dags/utils/gcp.py

requires https://github.com/mozilla/bigquery-etl/pull/485

Sql main summary

---

dags/main_summary.py

requires https://github.com/mozilla/bigquery-etl/pull/481

Add sql_clients_daily

---

dags/main_summary.py
dags/utils/gcp.py

and use it to export main summary
requires https://github.com/mozilla/bigquery-etl/pull/492

Support BigQuery export to parquet via avro

---

dags/telemetry_aggregates.py

This is required for https://github.com/mozilla/python_mozaggregator/pull/195

Use python3 for mozaggregator jobs

---

dags/mozaggregator_mobile.py
dags/mozaggregator_parquet.py
dags/mozaggregator_prerelease.py
dags/mozaggregator_release.py

https://docs.databricks.com/release-notes/runtime/6.1.html

Use databricks runtime 6.1 for python 3.7 

---

dags/operators/moz_gcs_to_s3.py

Wait for tasks to finish in moz_gcs_to_s3

---

dags/operators/moz_gcs_to_s3.py

with ThreadPool not available in python2

---

dags/fx_usage_report.py
dags/main_summary.py
dags/ssl_ratios.py

r=me
the bigquery export job needs more work, it caused most of the main summary dag to fail

Revert "Replace spark main summary with sql (#700)"

---

dags/utils/gcp.py

Fix avro logic for export_to_parquet

---

dags/main_summary.py

Fix bq exports for clients_last_seen and mau tables

---

dags/main_summary.py

Fix exact mau export

---

dags/operators/dataproc_hadoop_with_aws.py

Fix copypasta

---

dags/glam.py

Oops. Left this in after testing locally with it.

Removing debug cluster name.

---

jobs/addon_recommender.sh

flag removed in https://github.com/mozilla/telemetry-batch-view/pull/555/files#diff-ebfbc196fc5b4a7f5a210a2363aa5ae1L42

drop --output flag to AddonRecommender

---

dags/main_summary.py

dags have no errors locally, and running queries by copy-pasting rendered operators worked without issue

Switch addons and addon_aggregates to being generated in sql

---

dags/main_summary.py

Depends on https://github.com/mozilla/bigquery-etl/pull/536

Bug 1594222 Schedule devtools_panel_usage query

---

dags/main_summary.py

requires https://github.com/mozilla/telemetry-batch-view/pull/557

Run main_summary_experiments on dataproc

---

dags/main_summary.py

This reverts commit d3e1a8f9a851cb2ae19fd6106a0212d1ba1cf617.

Revert "Run main_summary_experiments on dataproc (#763)"

---

dags/bgbb.py
dags/main_summary.py
dags/utils/dataproc.py

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1596205)
This has been tested locally and succeeds successfully. This will write intermediate results out into the shared-prod analysis dataset, and write the results to the appropriate output buckets in gcs.
https://console.cloud.google.com/dataproc/jobs/5efbaaddab6948caadc3d34f893749b7?project=amiyaguchi-dev&region=us-west1
https://console.cloud.google.com/dataproc/jobs/bgbb_pred_dataproc_e6fbf2ac?organizationId=442341870013&project=amiyaguchi-dev&region=global
This depends on https://github.com/wcbeard/bgbb_airflow/pull/13

Bug 1596205 - Move bgbb jobs into GCP

---

dags/copy_deduplicate.py
dags/utils/gcp.py

Add experiment enrollments tasks. See mozilla/bigquery-etl#524 for the corresponding change in bigquery-etl.
This PR adds three new tasks: the first materializes yesterday's experiment enrollment aggregates into `telemetry_derived.experiment_enrollment_aggregates_v1`. The second generates a query for the `experiment_enrollment_aggregates_live` view that advances the date forward and pushes the result into an airflow xcom (via a change in the bigquery-etl entrypoint script in the associated PR. Briefly, this is annoyingly necessary since query parameters are not allowed in view definitions.) The third actually runs the query using a new utility function, `bigquery_xcom_query` that passes an xcom as the query argument to the `bq query` command.

Add experiment enrollment aggregates tasks

---

dags/main_summary.py

Forgot to schedule this query from mozilla/bigquery-etl#524

Add experiments_daily_active_clients incremental query

---

dags/copy_deduplicate.py

Sorry for another PR – wish there was an easy way to test this locally :/

Override default partitioning for event_events_export

---

dags/copy_deduplicate.py

Okay, I was able to test this config with --dry_run on the xport script and the output is what I had actually expected

Use doc_type as partitioning column instead

---

dags/copy_deduplicate.py

Stop spamming klukas with my job's failures

---

dags/copy_deduplicate.py
dags/utils/gcp.py

No, really, this is the last fix for event_events export

---

dags/utils/gcp.py

WTMO is _not_ running python 3.5+ T_T

Fix syntax issue in utils.gcp

---

dags/copy_deduplicate.py
dags/main_summary.py

Fixups for wrong project ID in exact_mau28 by client count

---

dags/glam.py

This task just breaks up the `histogram_probe_counts` task into two.

Add intermediate histogram buckets task.

---

dags/main_summary.py

[For search clients last seen](https://github.com/mozilla/bigquery-etl/pull/451)

Add search clients last seen

---

dags/socorro_import.py

Now that we're no longer using Athena datasource in favor of BQ

Rm parquet cp back from GCS to S3 for socorro job

---

dags/mozaggregator_mobile.py
dags/mozaggregator_prerelease.py

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1606361)
This also deletes the intermediate files from mobile_metrics.

 Bug 1606361 - Update prerelease aggregates to read from avro 

---

dags/copy_deduplicate.py
dags/main_summary.py

This will allow https://github.com/mozilla/bigquery-etl/pull/670 to run without manual interventions.

Allow field addition in clustered event views

---

dags/copy_deduplicate.py

Depends on https://github.com/mozilla/bigquery-etl/pull/663

Add impression_stats_flat query

---

dags/clean_gke_pods.py

Although I can no longer find reference of a 1k limit in the gke docs.

Reduce retention of GKE pod history. 

---

dags/copy_deduplicate.py

Corresponding PR to mozilla/bigquery-etl#707

Add a wait to the experiment enrollments live query gen task

---

dags/copy_deduplicate.py

Depends on https://github.com/mozilla/bigquery-etl/pull/700

Add queries for VR browser pings to copy_deduplicate

---

dags/copy_deduplicate.py
dags/fxa_events.py
dags/main_summary.py

Relies on https://github.com/mozilla/bigquery-etl/pull/719

Add compressed smoot queries

---

dags/kpi_dashboard.py

Depends on https://github.com/mozilla/bigquery-etl/pull/721

Schedule compressed smoot new_profiles query

---

requirements.txt

https://bugzilla.mozilla.org/show_bug.cgi?id=1614501 has more details for posterity

Bug 1614501: Pin werkzeug version as temp fix

---

dags/glam.py

This is the dag change to go with https://github.com/mozilla/bigquery-etl/pull/752

Glam aggregations by sample_id partition.

---

dags/glam.py
dags/glam_subdags/general.py
dags/glam_subdags/histograms.py

This PR goes along with this: https://github.com/mozilla/bigquery-etl/pull/754

Glam: Break up more processing by sample_id partition and add valid builds task

---

dags/glam_subdags/general.py

I missed a couple things here, just following up with fixes.

Glam follow-ups for sample_id partitioning

---

dags/glam_subdags/general.py
dags/glam_subdags/histograms.py

This PR sets the correct destination table for the final step of clients_histogram_aggregates.

Histogram aggregates final subdag should have the clients_histogram_aggregates_v1 destination table.

---

dags/copy_deduplicate.py

We are building the Incline dashboard using the new baseline-only methodology and will soon be transitioning GUD to this methodology as well.

Schedule new Fenix ETL

---

dags/glam.py

This reverts commit 044987131951d7256981621f2bd3c25d7a1f5433.

Revert "Test clients_daily_* with an older docker image."

---

dags/pensieve.py

To schedule pensieve in Airflow. https://github.com/mozilla/pensieve/issues/4

Add DAG for running pensieve

---

dags/copy_deduplicate.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1616895

Bug 1616895 Move impression_stats_flat into bi dataset

---

dags/copy_deduplicate.py

Add Messaging System tasks

---

dags/main_summary.py
dags/socorro_import.py
dags/utils/gcp.py

For https://bugzilla.mozilla.org/show_bug.cgi?id=1612541#c12
r?

Set GOOGLE_CLOUD_PROJECT for parquet2bigquery load operations

---

dags/copy_deduplicate.py

r? @jklukas 
This spins the tasks added [here](https://github.com/mozilla/bigquery-etl/pull/813).

Add exact_mau28 tasks for Messaging System

---

dags/incline_dash.py

Add incline export job

---

dags/shredder.py

I am currently manually running this, but if I stop the manual runs then shredder will pick up where it left off, so long as it runs with `--start-date=2019-11-20` and `--end-date=2020-03-09`.

Schedule shredder to run every 28 days

---

dags/addons_daily.py

The current addons_daily DAG has been turned off since the GCP migration. I've started work to migrate this query from spark to BQ in https://github.com/mozilla/bigquery-etl/pull/819.
I updated the DAG using the [bigquery-airflow cookbook](https://docs.telemetry.mozilla.org/cookbooks/bigquery-airflow.html) as a guide, however I'm not confident that everything looks as it should.
@jklukas Tapping you to take a look since you've seen the bigquery-etl query :).

Update addons_daily dag to call bigquery-etl query

---

dags/analysis.py

This should run the query in https://github.com/mozilla/bigquery-etl/pull/859/files on a daily basis and overwrite the destination table.
cc @jmccrosky

Schedule copy deviations task

---

dags/main_summary.py

Depends on https://github.com/mozilla/bigquery-etl/pull/864

Bug 1601281 Schedule addon_names query

---

.gitignore
Dockerfile
Dockerfile.dev
plugins/__init__.py
plugins/backfill/LICENSE.md
plugins/backfill/main.py
plugins/templates/backfill_page.html

Modified from: https://github.com/AnkurChoraywal/airflow-backfill-util
todo

Fixing Backfill ui plugin

---

dags/incline_dash.py

Closes https://github.com/mozilla/telemetry-airflow/pull/935
Depends on https://github.com/mozilla/bigquery-etl/pull/885

Switch incline_dash DAG to use script/export_incline_dash

---

jobs/ltv_daily.py

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1627091)

 Bug 1627091 - Add partition on date for model perf

---

dags/prio/kubernetes.py
dags/prio/processor.py

This should fix the prio jobs from failing.

Update prio buckets with protocol prefix

---

dags/analysis.py
dags/public_data.py
dags/ssl_ratios.py

This schedules publishing metadata to GCS for publicly available datasets.

Add public_data DAG

---

dags/glam_org_mozilla_fenix.py

This goes along with https://github.com/mozilla/bigquery-etl/pull/870

Extract csv and load into nonprod glam project

---

dags/bq_events_to_amplitude.py

Depends on https://github.com/mozilla/bigquery-etl/pull/899

Bug 1628740 Schedule sync send tab Amplitude export

---

.add_credentials.md
README.md
bin/add_gcp_creds
dags/ltv.py
dags/utils/dataproc.py
docker-compose.yml
jobs/ltv_daily.py

Ben and I decided we wanted the partitioning per-day for this dataset. We will end up limiting the history of the dataset, but during this iteration phase we need to see over-time performance and comparisons.
Documentation for Dataproc should enable others to get up-and-running without consulting either of us.

Dataproc Documentation && LTV Update

---

bin/run
dags/probe_scraper.py

Related to https://github.com/mozilla/probe-scraper/pull/181

Pass execution date and bugzilla key to probe expiry alert

---

dags/socorro_import.py

This adds a new email to the socorro_import list, and also `black`s the file.

Add new email to socorro_import list

---

dags/glam.py
dags/glam_subdags/general.py

Goes with https://github.com/mozilla/bigquery-etl/pull/881

Add sampling parameters to glam desktop.

---

dags/main_summary.py

Depends on https://github.com/mozilla/bigquery-etl/pull/952

Add clients_first_seen query

---

dags/fxa_amplitude_export.py

Depends on https://github.com/mozilla/bigquery-etl/pull/941.

Add DAG for exporting FxA events to Amplitude

---

dags/glam.py

This was causing a failure in the glam dag

Remove unused param in Glam desktop dag.

---

dags/fxa_amplitude_export.py

Move depends_on_past to query

---

bin/run
dags/analysis.py

Schedules https://github.com/mozilla/forecasting/pull/27
Depends on https://github.com/mozilla/bigquery-etl/pull/961

Schedule anomdtct pipeline

---

dags/fxa_export_to_amplitude.py

Harold and I have been trying to get the existing DAG to backfill,
but cannot.
This is an attempt to get the entire DAG to run.

Rename fxa amplitude export DAG

---

dags/fxa_export_to_amplitude.py

Depends on https://github.com/mozilla/bigquery-etl/pull/973

Schedule fxa_amplitude_user_ids table

---

dags/bq_events_to_amplitude.py

Devtools event view uses [event](https://github.com/mozilla/bigquery-etl/blob/master/sql/telemetry_derived/devtools_events_amplitude_v1/view.sql#L36) and [main](https://github.com/mozilla/bigquery-etl/blob/master/sql/telemetry_derived/devtools_events_amplitude_v1/view.sql#L85) tables. This makes the Amplitude export job wait for deduplication of these tables.

Bug 1633638 - wait for event and main tables before exporting DevTools events to Amplitude

---

bin/run
dags/analysis.py

Related to https://github.com/mozilla/forecasting/pull/29

Spreadsheet API key for anomdtct pipeline

---

dags/glam.py

Refer to note in https://github.com/mozilla/bigquery-etl/pull/982

Don't execute probe counts queries in parallel.

---

dags/copy_deduplicate.py

Depends on https://github.com/mozilla/bigquery-etl/pull/979
cc @gkabbz

Schedule firefox_nondesktop_day_2_7_activation

---

dags/webrender.py

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1639373)

Bug 1639373 - Add webrender dashboard for DS-283 to airflow

---

dags/adjust_import.py
jobs/adjust_import.py

Short-term this will re-hash all ids every day. I tested this in my sandbox and data is available at `frank-sandbox:firefox_preview_external.adjust_install_time_v1`

Add job for hashing Adjust Ids

---

dags/webrender.py

As per @saptarshiguha, this should fix recent [airflow failures](https://workflow.telemetry.mozilla.org/log?task_id=webrender_ds_283&dag_id=webrender_ds_283&execution_date=2020-05-25T00%3A00%3A00%2B00%3A00).

Update parameters for webrender dashboard

---

dags/webrender.py

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1639373)
cc @saptarshiguha

Bug 1639373 - Remove options for validating permissions in webrender DAG

---

dags/bqetl_vrbrowser.py
dags/copy_deduplicate.py

DAG generated in https://github.com/mozilla/bigquery-etl/pull/1038

bqetl_vrbrowser DAG

---

dags/bqetl_core.py
dags/copy_deduplicate.py

Uses the `bqetl_core` DAG generated in https://github.com/mozilla/bigquery-etl/pull/1040

Add bqetl_core DAG

---

dags/bqetl_nondesktop.py
dags/copy_deduplicate.py

Depends on https://github.com/mozilla/telemetry-airflow/pull/1015
Generated in https://github.com/mozilla/bigquery-etl/pull/1041

bqetl_nondesktop DAG

---

dags/bqetl_mobile_search.py
dags/copy_deduplicate.py

DAG generated via https://github.com/mozilla/bigquery-etl/pull/1043

Add generated bqetl_mobile_search DAG

---

dags/bqetl_gud.py
dags/bqetl_nondesktop.py
dags/copy_deduplicate.py
dags/fxa_events.py
dags/kpi_dashboard.py
dags/main_summary.py

Generated via https://github.com/mozilla/bigquery-etl/pull/1046

bqetl_gud DAG

---

dags/glam.py

Change daily histogram agg back to bq etl query

---

dags/bqetl_amo_stats.py

Generated via https://github.com/mozilla/bigquery-etl/pull/1059

Bug 1644088 Theme usage stats in AMO queries

---

dags/bqetl_activity_stream.py
dags/copy_deduplicate.py

Generated via https://github.com/mozilla/bigquery-etl/pull/1066

Move impression_stats query to bqetl_activity_stream DAG

---

dags/addons_daily.py
dags/bqetl_search.py
dags/ltv.py
dags/main_summary.py
dags/pensieve.py

Generated via https://github.com/mozilla/bigquery-etl/pull/1065
I hope I didn't miss any references that need to be updated in other DAGs.

Add bqetl_search DAG

---

dags/bqetl_amo_stats.py

Generated in https://github.com/mozilla/bigquery-etl/pull/1068

Remove deprecated amo_stats_dau_v1 queries

---

dags/fxa_events.py

Schedules new queries in https://github.com/mozilla/bigquery-etl/pull/1048

Bug 1628708 FxA Activity and Flow metrics

---

dags/fxa_export_to_amplitude.py
dags/utils/amplitude.py

Depends on https://github.com/mozilla/bigquery-etl/pull/1070

Bug 1633918 Schedule Amplitude email click export

---

dags/anomdtct.py
dags/utils/forecasting.py

Depends on https://github.com/mozilla/forecasting/pull/31

Change forecast tasks to use prod GCR images

---

dags/ltv.py

This is going to actually be writing to a different project. We don't support that with the current bq_etl deploy procedures, so I'm writing it directly using the bigquery operator.

Revenue data writing

---

dags/play_store_export.py

This will probably need updates to the cluster permissions

Add task for play store export

---

bin/run
dags/taar_weekly.py

This adds tasks to generate a TAAR user profile table in BigTable.

Add TAAR user profile BigTable ETL 

---

dags/burnham.py
dags/utils/burnham.py

Fix a few issues with the burnham DAG.

Fix burnham DAG issues

---

dags/burnham.py
dags/utils/burnham.py

This depends on https://github.com/mozilla/burnham/pull/46

Update arguments for burnham-bigquery

---

dags/burnham.py

This pull-request depends on https://github.com/mozilla/burnham/pull/48

Use parameterized query in burnham DAG

---

bin/run
dags/leanplum_export.py
dags/utils/leanplum.py

This sets the version to 2 so tables are suffixed with v2
Also jason just added the `aws_data_iam_s3` connection

Add task for leanplum streaming export

---

dags/glam_org_mozilla_fenix.py

The permissions for this have not been resolved. Any services that want to fetch data from the `glam-fenix-dev` project can be granted access from the sandbox project instead.

Remove exports into bespoke project

---

dags/bqetl_internet_outages.py

Generated via https://github.com/mozilla/bigquery-etl/pull/1111
cc @Dexterp37

Add internet_outages DAG

---

dags/burnham.py

This pull-request adds several new SQL queries as well as expected results for verifying specific test scenarios.
I added brief documentation for each of the tests. 📝

Update test scenarios in burnham DAG

---

dags/bqetl_amo_stats.py

Generated via https://github.com/mozilla/bigquery-etl/pull/1056

Bug 1643683 Add Fenix DAU query for AMO stats

---

dags/bqetl_amo_stats.py

Addresses https://github.com/mozilla/telemetry-airflow/pull/1064/files#r449142466

Fix up bqetl_amo_stats DAG

---

dags/pensieve.py

Depends on https://github.com/mozilla/pensieve/pull/106

Add pensieve json export task

---

dags/play_store_export.py

Change play store export to execute on previous day

---

dags/bq_events_to_amplitude.py

requires https://github.com/mozilla/bigquery-etl/pull/1142

Forward deletion requests to amplitude

---

dags/leanplum_export.py

Would it be better to merge this tomorrow so we don't have a partial day?  IIRC we can't backfill the streaming export

Add android beta and nightly leanplum exports

---

dags/firefox_public_data_report.py

* bump Dataproc image version to 1.5 for Python 3.7
* specify custom partitioning column for user_activity table

Fix Public Data Report DAG

---

dags/bqetl_activity_stream.py
dags/bqetl_addons.py
dags/bqetl_amo_stats.py
dags/bqetl_clients_daily.py
dags/bqetl_core.py
dags/bqetl_deviations.py
dags/bqetl_devtools.py
dags/bqetl_experiments_daily.py
dags/bqetl_gud.py
dags/bqetl_internet_outages.py
dags/bqetl_main_summary.py
dags/bqetl_messaging_system.py
dags/bqetl_mobile_search.py
dags/bqetl_nondesktop.py
dags/bqetl_search.py
dags/bqetl_vrbrowser.py
dags/copy_deduplicate.py
dags/incline_dash.py
dags/kpi_forecasts.py
dags/ltv.py

Generated via https://github.com/mozilla/bigquery-etl/pull/1146

Reschedule DAGs and set priority and pools

---

dags/incline_dash.py
dags/kpi_forecasts.py
dags/pensieve.py

Should fix the tasks that failed

Timedelta fixes

---

dags/leanplum_export.py

Set scheduled time to 4:00 for leanplum

---

dags/bqetl_public_data_json.py

Generated via https://github.com/mozilla/bigquery-etl/pull/1162

Fix public data DAG

---

dags/bqetl_deletion_request_volume.py

Generated via https://github.com/mozilla/bigquery-etl/pull/1106

bqetl_deletion_request_volume DAG

---

dags/utils/gcp.py

blocks https://github.com/mozilla/bigquery-etl/pull/1170

Allow field addition for specified dates in bigquery_etl_query

---

dags/jetstream.py

Depends on https://github.com/mozilla/jetstream/pull/125
See https://github.com/mozilla/jetstream/issues/114

Rename to pensieve to jetstream

---

dags/bqetl_activity_stream.py
dags/bqetl_addons.py
dags/bqetl_amo_stats.py
dags/bqetl_asn_aggregates.py
dags/bqetl_core.py
dags/bqetl_deviations.py
dags/bqetl_devtools.py
dags/bqetl_experiments_daily.py
dags/bqetl_gud.py
dags/bqetl_internet_outages.py
dags/bqetl_main_summary.py
dags/bqetl_messaging_system.py
dags/bqetl_mobile_search.py
dags/bqetl_nondesktop.py
dags/bqetl_public_data_json.py
dags/bqetl_search.py
dags/bqetl_ssl_ratios.py
dags/bqetl_vrbrowser.py

Generated via https://github.com/mozilla/bigquery-etl/pull/1195
To undo, use https://github.com/mozilla/telemetry-airflow/pull/1104

ExternalTaskSensor pool

---

dags/glam_subdags/general.py

Ensure repeated_subdag partition size is an integer

---

dags/bqetl_mobile_search.py

For https://github.com/mozilla/bigquery-etl/pull/1196

Add mobile search clients last seen task

---

dags/monitoring.py

For now this DAG only schedules one task for determining partition sizes but I guess there will be more monitoring related tasks that can be added here in the future.

Add DAG for monitoring tasks

---

bin/run
dags/app_store_analytics.py

https://bugzilla.mozilla.org/show_bug.cgi?id=1576788
Corresponding scripts: https://github.com/mozilla/app-store-analytics-export

Add dag for app store analytics export

---

dags/app_store_analytics.py

Shouldn't be an f-string.  I flip flopped between a few things and forgot to test this final change

Fix app store date argument

---

dags/app_store_analytics.py

To create derived tables combining metrics per dimension
Related bq-etl pr: https://github.com/mozilla/bigquery-etl/pull/1207

Add tasks for app store derived tables

---

dags/fxa_basket_export.py

See https://github.com/mozmeao/basket/issues/426
Relies on permissions in
https://github.com/mozilla-services/cloudops-infra/pull/2326

Add fxa_basket_export DAG

---

dags/monitoring.py

https://github.com/mozilla/bigquery-etl/pull/1225

Add distinct docid count to monitoring dag

---

dags/monitoring.py

Forgot default project is derived-datasets 🙃

Change distinct docid project to shared-prod

---

dags/copy_deduplicate.py

Schedules https://github.com/mozilla/bigquery-etl/pull/1233
Very similar to scheduling `experiment_enrollment_aggregates`

Schedule experiment_search_aggregates queries

---

dags/copy_deduplicate.py

Undoes https://github.com/mozilla/telemetry-airflow/pull/1129
See https://github.com/mozilla-services/cloudops-infra/pull/2441

Revert xfocsp_error_report_live exception in copy_dedup

---

dags/burnham.py

Depends on https://github.com/mozilla/burnham/pull/62

Add new parameters to burnham-bigquery operator

---

dags/monitoring.py

Depends on https://github.com/mozilla/bigquery-etl/pull/1256

Schedule bigquery_etl_scheduled_queries_cost_v1 query

---

dags/burnham.py

As discussed in the cross-functional Glean meeting, this pull-request updates the email receivers for the burnham DAG.
Resolve https://github.com/mozilla/burnham/issues/66

Update burnham DAG email receivers

---

dags/mozaggregator_mobile.py
dags/mozaggregator_prerelease.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1656910

[Bug 1656910] Remove saved-session ping processing

---

dags/ltv.py

Add cluster spec to correct query

---

dags/taar_weekly.py

Replacing vng by anatal

---

dags/glam.py

Use default emails for all glam tasks

---

dags/fission_experiment_monitoring.py

This should be merged after https://github.com/mozilla/bigquery-etl/pull/1327 lands

Add fission experiment monitoring DAG

---

dags/experimenter_experiments_import.py

See https://github.com/mozilla/bigquery-etl/pull/1420

Schedule Experimenter experiments imports

---

dags/monitoring.py

This schedules https://github.com/mozilla/bigquery-etl/pull/1486

Schedule column size monitoring query

---

dags/utils/gcp.py

This might be a cleaner fix compared to https://github.com/mozilla/bigquery-etl/pull/1518

[Bug 1675293] Update schema_update_option handling in bigquery_etl_query

---

dags/jetstream.py

Depends on https://github.com/mozilla/jetstream/pull/282/

Use jetstream with Argo

---

Dockerfile.dev
config/airflow_local_settings.py

Success/Failed look the same to R/G colorblind
https://bugzilla.mozilla.org/show_bug.cgi?id=1675380

Colorblind friendly UI

---

dags/burnham.py

This pull-request makes the following updates to the burnham DAG:
- Add a new burnham client `client4` which submits with `test_name` set to `test_disable_upload`
- Add or extend `WHERE` clauses to existing queries to filter out pings produced by `client4`
- Add a new sensor for the `discovery_v1` table that waits for pings produced by `client4`
- Add a new sensor for the `deletion_request_v1` table that waits for pings produced by `client4`
- Add two new burnham-bigquery operators that verify the data in the aforementioned tables for `client4`
The required burnham capabilities were added in https://github.com/mozilla/burnham/pull/110.
@mdboom and I worked on this together: We would like to extend the `test_deletion_request_ping` scenario with a query that joins data from `discovery_v1` …

Add burnham tests for disabling Glean upload

---

dags/operators/gcp_container_operator.py

Somewhat related:
If we ever override reattach_on_restart=True, and have > 1 Pods that match the same labels, the PodOperator will exit with 'More than one pod running with labels...'
https://github.com/apache/airflow/blob/1.10.12/airflow/contrib/operators/kubernetes_pod_operator.py#L273-L276

Fix 1.10.12 regression with gkepodoperator re-runs

---

bin/run
dags/jetstream.py

Depends on https://github.com/mozilla/jetstream/pull/319

Jetstream cluster IP and certificate as variables

---

dags/copy_deduplicate.py

Run `copy_deduplicate_all` on the highmem node pool

Use highmem node pool for copy_deduplicate_all

---

dags/copy_ga_sessions.py

related https://github.com/mozilla/bigquery-etl/pull/1565

Add dag for copying ga_sessions

---

dags/app_store_analytics.py

related to https://github.com/mozilla/bigquery-etl/pull/1570

Move app store queries to marketing directory

---

dags/glam.py

Goes with https://github.com/mozilla/bigquery-etl/pull/1594

Use clustered query script for glam scalar tasks

---

dags/mau_dashboard_test.py

Goes with https://github.com/mozilla/docker-etl/pull/2

Add mau dashboards dag

---

bin/run
dags/crash_symbolication.py

Goes with https://github.com/mozilla/python_mozetl/pull/353

Add dag crash symbolication dataproc jobs

---

dags/crash_symbolication.py

Execution delta is actually 5 hours

Change task sensor execution delta in symbolication dag

---

dags/anomdtct.py

Depends on https://github.com/mozilla/bigquery-etl/pull/1627
cc @Dexterp37

Add anomdtct DAG back

---

dags/bhr_collection.py
dags/crash_symbolication.py
dags/graphics_telemetry.py

Goes with https://github.com/mozilla/python_mozetl/pull/356
This pr also changes the source url for the other python_mozetl jobs to the main branch

Add bhr_collection dag

---

dags/bhr_collection.py

Change bhr sample size arg to string

---

dags/taar_daily.py

Pass checkpoint directory to the job. I hope it's ok to reuse ETL bucket for this.
Didn't test it locally, except dag parsing. To launch actual job, I need either permissions for prod cluster or to set up sandbox cluster, which is a lot of work. So, testing live. Let me know if you ok with this or I should set everything up and run it from local airflow first.
PR for a corresponding job https://github.com/mozilla/telemetry-batch-view/pull/562

Attempt to fix failing taar colaborative job

---

dags/copy_deduplicate.py
dags/utils/gcp.py

fixes https://github.com/mozilla/bigquery-etl/issues/1614

Run copy deduplicate DAG in shared-prod

---

dags/copy_deduplicate.py

I realized that as long as the Grafana queries haven't been migrated we need to keep updating the event enrollment aggregates live view.

Add back experiment_enrollment_aggregates_live view generation

---

dags/graphics_telemetry.py

Bug 1687361 - Fix graphics telemetry s3 prefix

---

dags/copy_deduplicate.py
dags/experiment_monitoring_data_export.py

Depends on https://github.com/mozilla/bigquery-etl/pull/1680

Update experiment monitoring data export DAG

---

dags/experiment_monitoring_data_export.py

Fix export_monitoring_data arguments

---

dags/experiments_live.py

Would it also help to set `max_active_runs` to 1?

Set concurrency for experiments_live to 1

---

dags/copy_deduplicate.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1690366

Bug 1690366 Add workflow docs to copy_deduplicate DAG

---

jobs/update_orphaning_dashboard_etl.py

This removes usage of analysis dataset.

Update orphaning: use mozdata.tmp for aggregation

---

dags/jetstream.py

https://github.com/mozilla/jetstream/issues/384

Update jetstream DAG to remove entrypoint script

---

dags/mozaggregator_prerelease.py

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1694732)

Bug 1694732 - fix job details on mozaggregator job

---

dags/experiments_live.py

Depends on both https://github.com/mozilla/docker-etl/pull/19 and https://github.com/mozilla/bigquery-etl/pull/1856

Use docker-etl script for experiments monitoring data export

---

dags/experiments_live.py

Depends on https://github.com/mozilla/bigquery-etl/pull/1879

Remove tasks for running experiment search metrics queries

---

dags/burnham.py

Per https://bugzilla.mozilla.org/show_bug.cgi?id=1700121#c10

Bug 1700121 Add sleep task to burnham DAG

---

dags/copy_deduplicate.py

[jira ticket](https://jira.mozilla.com/browse/DS-1424)
Depends on #1275, and hard dependency on https://github.com/mozilla/bigquery-etl/pull/1934

[DS-1424] Schedule baseline clients first seen

---

dags/copy_deduplicate.py

Needed for https://github.com/mozilla/bigquery-etl/pull/1946

Addd dependency between clients daily and first seen

---

bin/run
dags/mad_server.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1695687 (restricted access).

Bug 1695687 Add mad_server DAG

---

dags/mad_server.py

Add gke_location to mad_server DAG

---

dags/probe_scraper.py

Update gke cluster arguments

---

bin/run
dags/probe_scraper.py

- Fix issue with missing time import
- Run isort

Promote lookml-generator to prod

---

bin/run
dags/probe_scraper.py

I'm not 100% sure if the changes in `bin/run` are required, but it'll prevent from errors happening during startup.

Build GLEAN Dictionary after schema generation

---

dags/probe_scraper.py

set downstream from probe_scrapeer

Release lookml-generator

---

dags/copy_deduplicate.py

Depends on https://github.com/mozilla/bigquery-etl/pull/2027
I think this and bigquery-etl are the only places the scripts are used?

Use bqetl CLI for running baseline queries

---

dags/copy_deduplicate.py

`GKEPodOperator` ignores `command`

Use gke_command for baseline tasks

---

dags/copy_deduplicate.py

see https://github.com/mozilla/bigquery-etl/pull/2043

baseline_clients_first_seen --no-partition

---

dags/mad_server.py

Per https://bugzilla.mozilla.org/show_bug.cgi?id=1695687#c74
I'll plan to merge this on Monday, after we've verified stability of the job over the next days.

Change mad_server schedule to weekly

---

dags/operational_monitoring.py

Should land after https://github.com/mozilla/bigquery-etl/pull/2054

Add operational monitoring dag.

---

dags/glam.py

Fixes: https://github.com/mozilla/glam/issues/1390
Other half is https://github.com/mozilla/bigquery-etl/pull/2096

Add GPU process histogram aggregations to GLAM

---

dags/partybal.py

Fixes https://github.com/mozilla/jetstream/issues/790
Once this is merged we should kill the hala job

Schedule partybal

---

dags/bhr_collection.py
dags/bq_events_to_amplitude.py
dags/crash_symbolication.py
dags/firefox_public_data_report.py
dags/fission_experiment_monitoring.py
dags/glam.py
dags/glam_fenix.py
dags/graphics_telemetry.py
dags/incline_dash.py
dags/jetstream.py
dags/kpi_forecasts.py
dags/ltv.py
dags/operational_monitoring.py
dags/parquet_export.py

Related to https://github.com/mozilla/bigquery-etl/pull/2166

Use ExternalTaskCompletedSensors

---

dags/clean_gke_pods.py

Saw your doc change and doing similar

Update docs on clean_gke_pods.py

---

dags/glam.py
dags/glam_subdags/extract.py

Reverts mozilla/telemetry-airflow#1354

Revert "add sample counts to glam desktop dag"

---

dev_webserver_config.py
docker-compose.yml
webserver_config.py

For addressing IAP and google oauth issue (bug 1728197)

[DSRE-159] Build new wtmo 1.10.15 container 

---

dags/glam_subdags/extract.py

Modified the bigquery to gcs function to create multipart files for data transfer (glam_sample_counts_extract)

modified sample counts to create multiple files

---

dags/glam_fenix.py

This is to resolve the issue [1240](https://github.com/mozilla/glam/issues/1240)

added sample counts task to glam fenix

---

dags/probe_scraper.py

Depends on https://github.com/mozilla/lookml-generator/pull/242
Before merging a new lookml-generator version needs to be deployed.

lookml-generator set UPDATE_SPOKE_BRANCHES env variable

---

dags/adm_export.py
docker-compose.yml

See https://bugzilla.mozilla.org/show_bug.cgi?id=1729524
Uses new docker image from https://github.com/mozilla/docker-etl/pull/28
Depends on https://github.com/mozilla/bigquery-etl/pull/2373

Bug 1729524 Add adm_export weekly DAG

---

dags/adm_export.py

Follow-up to #1365
I don't know how I managed to get the wrong table name in here. But I'm
encouraged that the pod was successfully launched, so this is getting close.

Update table name in adm_export

---

dags/taar_daily.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1738045

Bug 1738045 Add clients_last_seen dep to taar_daily

---

dags/burnham.py

This PR adds the configuration necessary to run a Burnham dag against multiple versions of Burnham. It adds an additional client based on the original clients. These new clients will pull the latest Major version of burnham, as specified within the DAG.

Burnham multi version config

---

dags/glam.py
dags/glam_fenix.py

[DSRE-205] Migrate Glam gke cronjob to airflow for better dependency timing

---

bin/run
dags/glam.py
dags/glam_fenix.py

Fixes errors from last night with missing env vars. Hopefully tackled them all

[DSRE-205] Add config and secrets to the migrated glam cron task containers

---

dags/glam.py
dags/glam_fenix.py
dags/operators/gcp_container_operator.py

For import job that requires whitelist into postgres db

[DSRE-205] Add GKENatPodOperator, and modify glam dags use this

---

dags/glam_firefox_desktop.py

Add firefox desktop dag for glam.
The below is screenshot for the dev version:

added the dag for firefox_desktop

---

dags/burnham.py

Attempting a fix for the Burnham errors on Airflow. We forgot a mission and I raised the query limits to see if that helps.

Attempted fix for burnham airflow errors.

---

dags/burnham.py

I added too many ```value_sum``` metrics, this reverts that.

Fix burnham counters.

---

dags/burnham.py

This pull request is a follow-up for #1382:
* Update minimum count of rows for burnham sensors
* Add code comments to burnham sensors
FYI @jrbenny35 @jklukas

Update burnham sensors

---

dags/casa.py

Added DAG for casa fivetran connector

---

dags/glam.py

To debug the glam desktop release import glam taking long

isolate release import for desktop

---

dags/search_alert.py

This schedules script added in https://github.com/mozilla/docker-etl/pull/30

Add search alert DAG

---

dags/intacct_historical.py

changing extract schedule interval to run at 2am daily

edit historical interval

---

plugins/mozmenu.py

Hopefully this is a step in making Airflow triage quicker and easier.

Adding few extra links to the Mozilla menu button for Airflow

---

dags/glam.py
dags/glam_fenix.py
dags/glam_fog.py

Added a link from sample_counts to extract task

Correct a broken link between tasks

---

dags/glam.py
dags/glam_fenix.py
dags/glam_fog.py
dags/glam_glean_imports.py

This PR update the glam to latest version

Fenix dag for sc

---

Makefile
bin/run
dags/fivetran_acoustic.py
dags/utils/acoustic/acoustic_client.py
dags/utils/acoustic/request_templates/export_database.xml.jinja
dags/utils/acoustic/request_templates/get_agg_metric_org.xml.jinja
dags/utils/acoustic/request_templates/get_database_list.xml.jinja
dags/utils/acoustic/request_templates/get_job_status.xml.jinja
dags/utils/acoustic/request_templates/reporting_raw_recipient_data_export.xml.jinja
requirements.in
requirements.txt

feat(DENG-17): Acoustic data in BigQuery

---

dags/kpi_forecasting.py

Depends on https://github.com/mozilla/docker-etl/pull/36

Schedule KPI forecasting

---

dags/copy_deduplicate.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1763116
Should isolate the effect of failures that we are seeing.

Bug 1763116 Separate first_shutdown copy_deduplicate task

---

dags/publish_bqetl_static.py

Closes https://github.com/mozilla/bigquery-etl/issues/2836

Added DAG for static publish script

---

bin/test-dag-tags.py

to make check pass for PR:
https://github.com/mozilla/private-bigquery-etl/pull/49

repo/private-bigquery-etl tag added to VALID_TAGS list

---

dags/copy_deduplicate.py

Follow-up to #1482 to be logically consistent.

Bug 1763116 Separate saved_session copy_deduplicate task

---

dags/fivetran_acoustic.py
dags/utils/acoustic/acoustic_client.py

fixed a bug where we tried to generate report for 0 second time window

fixed a bug where we tried to generate report for 0 second time window

---

dags/burnham.py

This implements both suggestions I made in bug 1740724:
1. Deduping ping rows in the sensor query
2. Include the number of rows included in the calculation into the answer
2 is only done for one of the test queries. 
With 1. I would expect this to never be a mismatch again, so we could also leave it out.

Bug 1740724 - Burnham: Run the sensor check against a deduped table

---

dags/fivetran_acoustic.py

acoustic dag changed from push to pull approach for triggering downstream process.
Related bqetl process will check the final task for completion, instead of being triggered by this DAG.

acoustic dag changed from push to pull approach for triggering downstream process

---

dags/adm_export.py
dags/bhr_collection.py
dags/copy_deduplicate.py
dags/crash_symbolication.py
dags/firefox_public_data_report.py
dags/glam.py
dags/glam_fenix.py
dags/glam_fog.py
dags/glam_glean_imports.py
dags/graphics_telemetry.py
dags/jetstream.py
dags/kpi_forecasting.py
dags/ltv.py
dags/parquet_export.py
dags/socorro_import.py
dags/taar_daily.py
dags/utils/constants.py

https://bugzilla.mozilla.org/show_bug.cgi?id=1762430
This PR replaces all usages of `ExternalTaskCompletedSensor` with `ExternalTaskSensor` and adds `ExternalTaskMarker`s to define downstream dependencies.

[Bug 1762430] Use ExternalTaskMarker and ExternalTaskSensor in favour of ExternalTaskCompletedSensor

---

dags/search_alert.py

Search alert needs to wait for search aggregates to complete since the script queries this table (https://github.com/mozilla/docker-etl/blob/7c0f31290a0642b785f879bad43234e267221a4e/jobs/search-alert/search_alert/main.py#L53).

Wait for search aggregates before starting search alert task

---

dags/adm_export.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1770814
Depends on https://github.com/mozilla/bigquery-etl/pull/2999

Bug 1770814 Move adm_export to daily rather than weekly

---

dags/bhr_collection.py
dags/copy_deduplicate.py
dags/fivetran_acoustic.py
dags/glam.py
dags/graphics_telemetry.py
dags/jetstream.py

Add task markers for downstream dependencies that are part of `bqetl_` DAGs

Add task markers for bqetl_ DAG  downstream tasks

---

dags/copy_deduplicate.py
dags/utils/gcp.py

Depends on https://github.com/mozilla/bigquery-etl/pull/3069

[Bug 1769109] Fix clients_last_seen_joined schedule

---

dags/utils/gcp.py

path changed in https://github.com/mozilla/bigquery-etl/pull/3083

Update URL for export_to_parquet.py

---

dags/burnham.py

I will be sending out an announcement email about this today.
Note that I originally pushed this as #1535. I'm recreating this to work around an issue with CircleCI.

Add note about disabling test suite to burnham DAG

---

dags/probe_scraper.py

Motivated by [Slack discussion](https://mozilla.slack.com/archives/GE83ZMSAW/p1660302421785409?thread_ts=1660300785.950189&cid=GE83ZMSAW), this makes probe_scraper doc clearer.

Update probe_scraper DAG doc

---

dags/kpi_forecasting.py

Expected forecast output:
1.  QDAU for desktop
2. DAU for mobile
No CDOU or QCDOU forecasts.

Remove outdated forecasts.

---

dags/utils/gcp.py

Depends on https://github.com/mozilla/bigquery-etl/pull/3105

Use ./bqetl query run-multipart instead of old script

---

dags/probe_scraper.py

intentionally nothing depends on these tasks right now, both because their output isn't used yet and because they shouldn't block downstream tasks when they break.

Add probe scraper tasks for everything not covered by push mode

---

plugins/backfill/main.py

airflow tasks clear -c no longer exists, was changed to -y
unfort this requires a redeploy of wtmo

[DSRE-1000] Fix backfill UI plugin

---

dags/utils/gcp.py

Depends on https://github.com/mozilla/bigquery-etl/pull/3186

Use copy_deduplicate CLI command

---

plugins/backfill/main.py

for non background (missed in first pass)

[DSRE-1000] Fix backfill plugin clearing tasks pt2

---

dags/probe_scraper.py

~temporary solution intended to be reverted after issues with highmem-pool-v1 are fixed.~

Fix highmem nodepool label name

---

dags/probe_scraper.py

Reverts mozilla/telemetry-airflow#1558

Enable update mode for gecko-dev

---

dags/taar_weekly.py

[DSRE-1056] Fix taar weekly

---

dags/operators/backport/fivetran/hook.py
dags/operators/backport/fivetran/operator.py
dags/operators/backport/fivetran/sensor.py

Revert "Upgrade backported fivetran connector to v1.1.2"

---

dags/probe_scraper.py

requires https://github.com/mozilla/probe-scraper/pull/511

Add a probe scraper job to check expiry and fog expiry

---

dags/probe_scraper.py

tested locally to confirm branching and trigger rule work as expected

Fix branching in probe_scraper dag

---

dags/shredder.py

next run starts monday evening, plan is to merge this monday morning

DSRE-1006 - Handle shredder backlog using on-demand projects

---

.gitignore
.vscode/settings.json
bin/run
dags/data_monitoring.py

dim link: https://github.com/mozilla/dim

feat: Adds Airflow DAG for running some of the DIM checks

---

dags/contextual_services_import.py

It's helpful to keep these correct for whoever is on triage. [Context](https://bugzilla.mozilla.org/show_bug.cgi?id=1799081#c1)

Update owners of contextual sevices DAG

---

dags/jetstream.py
dags/operational_monitoring.py
dags/parquet_export.py

[DENG-475](https://mozilla-hub.atlassian.net/browse/DENG-475)

DENG-475 - Discontinue unused main summary export

---

dags/glam_dev.py
dags/glam_subdags/probe_hotlist.py

add hotlist to glam-dev

---

dags/data_monitoring.py

bug: added missing comma in GKEPodOperator arguments

---

dags/data_monitoring.py

feat: updated image for data_monitoring

---

dags/glam_dev.py

Testing without subdags for the step in question, because it keeps getting stuck on "running" and not executing. 
If it works I'll remove the old code and tidy things up.
Subdag was probably put here for performance reasons, but since the purpose of my work is to have glam-etl compute less probes, my assumption is that by having less data to process this step can become a single one.

glam-dev: no subdag from histogram_bucket_counts

---

dags/bqetl_artifact_deployment.py

requires https://github.com/mozilla/bigquery-etl/pull/3433

Use bqetl view clean to clean up managed views

---

dags/mozaggregator_prerelease.py

https://mozilla-hub.atlassian.net/browse/DSRE-52?focusedCommentId=626695

Remove mozaggregator2bq export

---

dags/merino_jobs.py

* Add no_triage tag while in dev. 
* Fix argument name (gcp-path -> gcs-path)
* Move harder to read env var to cli argument
* Formatting.

Misc fixes to merino jobs airflow

---

dags/merino_jobs.py

Getting an import error in prod. not showing up locally but hopefully this fixes it.

fix tag import error

---

dags/merino_jobs.py

Still getting import errors with the last change. trying again with relative imports like the other dags

lets try using relative imports now

---

dags/merino_jobs.py

I keep messing this up 🤦🏻 So i'm adding all cli arguments

Add all cli arguments to the index option

---

dags/probe_scraper.py

needed for [Bug 1815432 comment 3](https://bugzilla.mozilla.org/show_bug.cgi?id=1815432#c3)
requires https://github.com/mozilla/probe-scraper/pull/559

Support disabling update mode in manual probe-scraper runs

---

dags/merino_jobs.py

Will do an adhoc run to verify

fix: Swap CloudID for URL in the argument list. Move api key to ENV var.

---

dags/dap_collector.py

This is required for https://github.com/mozilla/docker-etl/pull/105

Add date parameter to DAP Collector task

---

dags/utils/gcp.py

This is so we can support monthly table partitions in airflow dags.
See https://github.com/mozilla/bigquery-etl/issues/3303

Add partition templating to the task generator for bqetl

---

dags/copy_deduplicate.py

Failure of this DAG is worth sending an email about to DSRE.

DSRE alert

---

dags/experiment_auto_sizing.py
dags/jetstream.py

Runs [auto-sizing](https://github.com/mozilla/auto-sizing) weekly on Sundays after Jetstream.

add dag for new experiment auto-sizing task

---

dags/shredder.py

unitl long term solutions can be put in place

add no-triage tag to shredder

---

dags/merino_jobs.py

This adds the domain_metadata cli command as a task to the merino_jobs dag.
Right now i'm keeping this as part of the main merino_jobs dag which is scheduled for every tues @ 5 am UTC. Its probably fine to keep this navigational domain task as part of that but when we have separate scheduling requirements we should think about having multiple dags.

DENG-830 Add domain metadata task to merino_jobs dag.

---

dags/merino_jobs.py

Add the prod job. Add a task to email on completion.

DENG-830 Add prod task and a task to email on success as a test for notification

---

dags/merino_jobs.py

Update does an in place update and has no return value. whoops! moving it outside of the operator creation call

Fix default env_vars for merino_jobs dag.

---

dags/dim_active_users_aggregates.py

feat(DENG-794): updated active_users_aggregates project and dim run command

feat(DENG-794): updated active_users_aggregates project and dim run command

---

dags/merino_jobs.py

Required to fix:
https://mozilla-hub.atlassian.net/browse/DENG-834
https://mozilla-hub.atlassian.net/browse/DENG-833

Add parameters to navigational suggestions merino job

---

dags/glam_dev.py

also increase `bucket_counts` subtask count to 20 to avoid out of resources error

glam-dev: remove all_combos step, will be embedded in bucket_counts

---

dags/merino_jobs.py

https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/operators.html#how-does-xcom-work
https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/xcoms.html

Add xcom push/pull to nav suggestions tasks

---

dags/kpi_forecasting.py

Change owner

---

dags/influxdb_to_bigquery.py

The dag schedules to run the docker etl job daily : https://github.com/mozilla/docker-etl/tree/main/jobs/influxdb-to-bigquery
Relates to https://mozilla-hub.atlassian.net/browse/RS-683.

RS 682 - dag to schedule the influxdb_to_bigquery job

---

dags/experiment_auto_sizing.py

Write to `mozanalysis` bucket for consistency with other experiment analysis data.

change auto-sizing bucket config

---

dags/bhr_collection.py
dags/graphics_telemetry.py

Also, had to apply black formatting in order to have the CI complete.

reassigning DAG ownership to kik as per "adopt a DAG" doc

---

dags/data_monitoring.py

bug(): fixing dim command used inside data_monitoring DAG

---

dags/bhr_collection.py
dags/crash_symbolication.py
dags/firefox_public_data_report.py
dags/graphics_telemetry.py
dags/update_orphaning_dashboard_etl.py

https://github.com/mozilla/telemetry-airflow/pull/1728 worked so these should as well.

DSRE 951 2

---

dags/kpi_forecasting.py

The `docker-etl` KPI forecasting code was recently refactored (https://github.com/mozilla/docker-etl/pull/121, [Jira](https://mozilla-hub.atlassian.net/browse/DS-2713)) as part of a broader effort to ensure we have a single source of truth for KPIs. There are breaking changes in that PR that will cause the existing Airflow tasks to fail; this PR should enable the DAG to complete successfully.
Relevant changes in this PR:
- Update the filepaths in the gke command (e.g. `"kpi-forecasting/configs/dau_desktop.yaml"` instead of `"kpi-forecasting/yaml/desktop_non_cumulative.yaml"`).
- Run the DAG daily instead of weekly.
- Wait for the relevant dim_check tasks instead of the unified_metrics table task.
- Add configs and programmatically build the DAG to make it simpler to add new forecasting …

Update kpi_forecasting DAG

---

dags/probe_scraper.py

fixes [Bug 1839909](https://bugzilla.mozilla.org/show_bug.cgi?id=1839909)

Bug 1839909 - Add credentials for sending email to probe scraper glean tasks

---

dags/partybal.py

This fixes the population ratio plotting issue.
I had to update the partybal CI and figured we just push images to the experiments project, like all the other tools are doing

Update partybal image

---

dags/utils/gcp.py

Details - https://mozilla-hub.atlassian.net/browse/DENG-1240

DENG-1240 - Fix bigquery_dq_check function to accept arguments

---

dags/bhr_collection.py

docs(): added more an additional link to BHR pings (DAG notes)

docs(): added more an additional link to BHR pings (DAG notes)

---

dags/glam_glean_imports.py

Updates glam import image to receive https://github.com/mozilla/glam/pull/2419

Update glam import img to use fix

---

dags/update_orphaning_dashboard_etl.py
jobs/update_orphaning_dashboard_etl.py

Fixes [DENG-1026](https://mozilla-hub.atlassian.net/jira/software/c/projects/DENG/boards/593?modal=detail&selectedIssue=DENG-1026)
Configured with the test GCS bucket for now. Will update with prod bucket in case it works
[DENG-1026]: https://mozilla-hub.atlassian.net/browse/DENG-1026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DENG-1026: Update orphaning to write to GCS instead of S3

---

dags/graphics_telemetry.py

Fixes: [DENG-1025](https://mozilla-hub.atlassian.net/jira/software/c/projects/DENG/boards/593?modal=detail&selectedIssue=DENG-1025) along with https://github.com/mozilla/python_mozetl/pull/388
Configured with the test GCS bucket for now. Will update with prod bucket in case it works
[DENG-1025]: https://mozilla-hub.atlassian.net/browse/DENG-1025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DENG-1025: gfx_telemetry r/w to GCS instead of S3

---

dags/search_term_data_validation.py

fix broken link in search_term_data_validation docstring

---

dags/mozaggregator_prerelease.py

Change owner to @edugfilho who is the main owner of the TMO aggs now.

Change prerelease aggs owner

---

dags/search_term_data_validation_v2.py

This is very embarrassing for me 😂 
The docker image endpoint had an underscore where it needs a dash.

Ctroy replace dataval

---

dags/merino_jobs.py

Updating email notification to include taddes and nan when airflow completes creation of top_picks files.

[DISCO-2606] update EmailOperator to list to include taddes and nan

---

dags/copy_deduplicate.py

Adding external task markers that are currently missing

Update external task markers in copy_deduplicate

---

dags/bhr_collection.py

Reverts mozilla/telemetry-airflow#1779

"DENG 1022 - Update bhr_collection DAG to write to GCS instead…"

---

dags/bhr_collection.py

Reverts mozilla/telemetry-airflow#1830

Revert ""DENG 1022 - Update bhr_collection DAG to write to GCS instead…""

---

dags/shredder.py

[DENG-476](https://mozilla-hub.atlassian.net/browse/DENG-476)
[DENG-476]: https://mozilla-hub.atlassian.net/browse/DENG-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DENG-476 - Update shredder tasks for main_v5 migration

---

dags/kpi_forecasting.py

Follows from https://github.com/mozilla/docker-etl/pull/156

Rename KPI forecasting directory

---

dags/kpi_forecasting.py

This change makes the Python call agree with https://github.com/mozilla/docker-etl/pull/158

Update path to agree with docker-etl changes

---

dags/bqetl_backfill.py

This works the same as running `bqetl query backfill`, but _not locally_!

Bqetl backfill 4real

---

dags/dim_active_users_aggregates.py
dags/kpi_forecasting.py

feat(): Updating DIM related scheduling to match that of aggregates DAG

feat(): Updating DIM related scheduling to match that of aggregates DAG

---

dags/bhr_collection.py

The PR does the following 
1. Changing the cluster for the test job
2. Add missing pip packages
3. remove AWS related spark env variables.

Changing the cluster for bhr gcs test job

---

dags/merino_jobs.py

This allows us to access the change diff text comparing most recent domain file to previous

[DISCO-2699] Added xcom pull for diff file access

---

dags/mozaggregator_prerelease.py

Reverts mozilla/telemetry-airflow#1869

Revert "mozaggregator uses main_v5"

---

dags/data_monitoring.py

feat(DENG-2065): deprecating DIM checks for cohorts_daily_statistics as they are no longer needed

---

Dockerfile

file no longer exists in upstream docker image

Remove temporary fix

---

dags/dap_collector.py

This is a follow up to https://github.com/mozilla/bigquery-etl/pull/4703

FXCTO-13 Update dap_collector's output destination

---

dags/probe_scraper.py
resources/dev_variables.json

This moves last remaining secret to GSM.

DSRE-1526 - Move probe_scraper secret to GSM

---

dags/casa.py
dags/fivetran_acoustic.py

fix(): Remove FivetranSensor to avoid double wait for sync to complete

---

dags/adm_export.py

DSRE-1520 Manage secrets for adm_export dag in GSM

---

dags/mad_server.py

@dzeber agreed to take ownership of mad_server.

Update mad_server owner

---

dags/fivetran_acoustic.py
utils/acoustic/acoustic_client.py

*[ DENG-3082](https://mozilla-hub.atlassian.net/browse/DENG-3082)
* DSRE-XXXX

feat(): add acoustic supression list export

---

dags/bqetl_backfill_complete.py
dags/bqetl_backfill_initiate.py

This PR adds two DAGs: one for initiating managed/scheduled bigquery-etl backfills and another for completing them.
* DENG-802
* DENG-983

feat(managed-backfills): DENG-983 Add DAGs for initiating and completing backfills

---

dags/bqetl_backfill_complete.py
dags/bqetl_backfill_initiate.py

This PR replaces the Slack connectio with the overwatch Slack connection (send notifications from the Overwatch app)
* DENG-989

feat(managed-backfills): DENG-989 - Use overwatch Slack app for managed backfills

---

dags/bqetl_backfill_complete.py
dags/bqetl_backfill_initiate.py

This PR fixes a typo in a Slack message for managed-backfills. Also adds notification emails to the two DAGs

fix(managed-backfills): typo in Slack message, add owners

---

dags/braze_gcs_to_bigquery.py

Braze exports data via currents into Google Cloud Storage.
This DAG will import the data from GCS into BigQuery.
For now this in only looking at one of the folders, to see if it is working. Once it is, this DAG will get more tasks
* [DENG-3411](https://mozilla-hub.atlassian.net/browse/DENG-3411)
* [DENG-3412](https://mozilla-hub.atlassian.net/browse/DENG-3412)

feat: DENG-3412 braze sync hard bounce to bigquery

---

dags/braze_gcs_to_bigquery.py

3rd time could be the charm. adding the con_id again
* DENG-3412

fix: DENG-3412 braze to bq add gcp_conn_id again

---

dags/cloudflare_browser_usage.py
dags/cloudflare_device_usage.py
dags/cloudflare_os_usage.py

This PR adds 3 new DAGs that call the open-source Cloudflare API to pull data on device usage, browser usage, and OS usage in different locations and by different cuts.
* DENG-3096

feat: DENG-3096 Create 3 new cloudflare DAGs

---

dags/cloudflare_browser_usage.py
dags/cloudflare_device_usage.py
dags/cloudflare_os_usage.py

This is to fix string formatting issues
* DENG-3096

feat: [DENG-3096] fix string formatting

---

dags/acryl_poc.py
dags/bigeye_poc.py

Just fixing some typos to point to the correct SQL file

fix: Fix SQL path typos for data observability dev DAGs

---

dags/eam_workday_xmatters_integration.py

Added environment secrets to the DAG to be used by the integration script.
JIRA TICKET [ASP-ASP-4631](https://mozilla-hub.atlassian.net/browse/ASP-4631)

feat:[ASP-4631] Workday - XMatters integration

---

dags/monte_carlo_poc.py
requirements.in
requirements.txt
resources/dev_connections.json

This adds a DAG for testing out the Monte Carlo integration with Airflow

feat: Add Monte Carlo POC

---

dags/eam_workday_xmatters_integration.py

Description
This PR is to fix the image link which had extra spaces.

fix(DAG): Workday-XMatters [ASP-4631] - Fixed image link string

---

dags/eam_workday_xmatters_integration.py

Description
This PR is to fix environment variable names and the on_failure_callback function

fix(DAG): Workday-XMatters [ASP-4631] - 

---

dags/eam_workday_xmatters_integration.py

Description
This PR is to test the Jira ticket creation by forcing the docker-etl script to fail.

fix(DAG): Workday-XMatters [ASP-4631] testing Jira ticket creation on failure

---

dags/eam_workday_xmatters_integration.py

Description
Changed the on_failure_callback_function.
Using the JIRA API instead of JiraOperator.

fix(DAG): Workday-XMatters [ASP-4631] - Changes in the on_failure_callback function

---

dags/eam_workday_xmatters_integration.py

Description:
Changed the Issue Type to Bug and Assignee to Julio
JIRA TICKET ASP [4792](https://mozilla-hub.atlassian.net/browse/ASP-4792)

feat(DAG): Workday-XMatters [ASP-4792] - Changed the Jira Issue Type to Bug and Assignee to Julio

---

dags/microsoft_store.py

feat(microsoft store DAG) reconstruct command strings

---

dags/microsoft_store.py

feat(deng 2361 microsoft) take out arguments from DAG

---

dags/microsoft_store.py

feat(microsoft) take out 'microsoft' from the microsoft_store DAG

---

dags/microsoft_store.py

This PR updates the table names in DAG microsoft_store
* [Bug ](https://bugzilla.mozilla.org/show_bug.cgi?id=1903600)

fix: Update table names in DAG microsoft_store

---

dags/socorro_import.py

update `socorro_import` to pull from gcs now that socorro has been migrated to GCP. I have temporarily paused the dag until this is resolved.
* bug 1579266
* https://github.com/mozilla-it/webservices-infra/pull/2188

fix: bug-1579266 update socorro import to pull from gcs

---

jobs/socorro_import_crash_data.py

it should not read from s3 anymore
also fix the code for reading from github
* bug 1579266
r? @ANich

fix: bug 1579266 fix fetch_schema in socorro_import_crash_data.py

---

dags/eam_workday_everfi_integration.py

Description:
New DAG eam-workday-everfi-integration
JIRA TICKET ASP [4747](https://mozilla-hub.atlassian.net/browse/ASP-4747)
JIRA EPIC TICKET [ASP-4747](https://mozilla-hub.atlassian.net/browse/ASP-4747)
[ASP-4747]: https://mozilla-hub.atlassian.net/browse/ASP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DAG): Workday-Everfi [ASP-4747] - New DAG

---

README.md
dags/search_forecasting.py

This PR adds the search forecast dag. 
* https://mozilla-hub.atlassian.net/browse/RS-1248

feat: add search_forecasting dag

---

dags/fxci_metric_export.py
dags/fxci_pulse_export.py

* [Bug 1904928](https://bugzilla.mozilla.org/show_bug.cgi?id=1904928) (tracking)
* [DENG-4195](https://mozilla-hub.atlassian.net/browse/DENG-4195) (secrets)
[DENG-4195]: https://mozilla-hub.atlassian.net/browse/DENG-4195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: create two new dags for the Firefox-CI ETL

---

dags/microsoft_store.py

fix(DAG): microsoft store DAG: change offset of day from 1 to 2

---

dags/eam_workday_everfi_integration.py

Description:
A few changes in the DAG configuration 
retries, retry_delay and schedule_interval 
JIRA TICKET ASP [ASP-5043](https://mozilla-hub.atlassian.net/browse/ASP-5043)
JIRA EPIC TICKET [ASP-4744](https://mozilla-hub.atlassian.net/browse/ASP-4744)
[ASP-5043]: https://mozilla-hub.atlassian.net/browse/ASP-5043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ASP-4744]: https://mozilla-hub.atlassian.net/browse/ASP-4744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(code): Workday-Everfi [ASP-5043] - changes in the DAG configuration

---

dags/webcompat_kb.py

Adds bugzilla token to include moco confidential bugs in the import

chore: Add bugzilla token for webcompat_kb DAG and update docs

---

dags/eam_workday_xmatters_integration.py

Change the Jira domain to Prod and remove no_triage tag
[Jira ticket ASP-4869](https://mozilla-hub.atlassian.net/browse/ASP-4869)
[Epic ASP-4509](https://mozilla-hub.atlassian.net/browse/ASP-4509)

feat(code):Change the Jira domain to Prod and remove no_triage tag

---

dags/glam.py
dags/glam_fenix.py
dags/glam_fog.py
dags/glam_glean_imports.py

removing Linh from Glam DAGs emails

fix: remove linh from dags

---

dags/eam_workday_xmatters_integration.py

Change retries and retry_delay
[Jira ticket ASP-4869](https://mozilla-hub.atlassian.net/browse/ASP-4869)
[Epic ASP-4509](https://mozilla-hub.atlassian.net/browse/ASP-4509)

fix(code):[Workday/XMatters] - Change retries and retry_delay

---

dags/eam_slack_channels.py

New DAG for the Slack Channels Integration 
[Jira ticket ASP-5186](https://mozilla-hub.atlassian.net/browse/ASP-5186)
[Epic ASP-5132](https://mozilla-hub.atlassian.net/browse/ASP-5132)

feat(code): New DAG for the Slack Channels Integration 

---

dags/looker.py

This fixes a typo in the CLI parameters names

Fix typos in spectacles

---

dags/bqetl_artifact_deployment.py

This skips the current run and marks tasks as skipped when there are queued dag runs.  Artifact deployment always uses the latest bigquery-etl image so we only need to run once when there are multiple queued runs.
Note this assumes all runs are equal which might not be true if we re-add [optional sql generation](https://mozilla-hub.atlassian.net/browse/DENG-2963?focusedCommentId=897578) and [artifact deployment after schema deploys](https://github.com/mozilla-services/cloudops-infra/pull/5736).  So this would need updates if that happens
Tested this locally:

chore: Skip artifact deploys when there are other queued runs

---

dags/looker.py

So the variable values aren't shown in the task instance details.
* Fixup for #2071.

fix: Use Airflow templated variables for LookML validation

---

dags/probe_scraper.py

Schedules the script created in https://github.com/mozilla/probe-scraper/pull/797
* DENG-577

feat: Add ping_expiry_alerts task to probe_scraper dag

---

dags/eam_workday_netsuite.py

Initial commit 
[Jira ticket ASP-5235](https://mozilla-hub.atlassian.net/browse/ASP-5235)
[Epic ASP-5165](https://mozilla-hub.atlassian.net/browse/ASP-5165)

feat(code): Workday Netsuite DAG

---

dags/glam_fog.py

It looks like Airflow always uses the last task of a TaskGroup for dependency purposes. This PR fixes the dependency of a TaskGroup by making the firs task (instead of the last) depend on the upstream task.

fix(GLAM): Fix TaskGroup upstream deps

---

dags/glam_fog.py

This PR improves on https://github.com/mozilla/telemetry-airflow/pull/2082 by addressing [a comment](https://github.com/mozilla/telemetry-airflow/pull/2082#discussion_r1744142916)

fix(GLAM): Proper TaskGroup dependency handling

---

dags/socorro_import.py

* https://bugzilla.mozilla.org/show_bug.cgi?id=1915996

fix(socorro_import): try manually built image

---

dags/shredder.py

The description is no longer accurate and the logging links use outdated project/resource names

chore(shredder): Update links and descriptions in shredder doc

---

dags/bqetl_artifact_deployment.py

This fixes a typo to deploy monitors to Bigeye

Fix Bigeye monitoring deploy

---

dags/eam_slack_channels.py

Change schedule interval
[Jira ticket ASP-5347](https://mozilla-hub.atlassian.net/browse/ASP-5347)
[Epic ASP-5132](https://mozilla-hub.atlassian.net/browse/ASP-5132)

feat(code): change schedule interval

---

dags/shredder.py

oops
* https://github.com/mozilla/telemetry-airflow/pull/2093

fix(shredder): Fix shredder arguments typo

---

dags/eam_slack_channels.py
dags/eam_workday_netsuite.py

Add AWS secrets
[Jira ticket ASP-5350](https://mozilla-hub.atlassian.net/browse/ASP-5350)
[Epic ASP-5165](https://mozilla-hub.atlassian.net/browse/ASP-5165)

feat(code): Add AWS secrets

---

dags/bqetl_backfill_complete.py
dags/bqetl_backfill_initiate.py
dags/crash_symbolication.py
dags/socorro_import.py

This PR updates ownership for anicholson DAGs
...

chore: update ownership for anicholson DAGs

---

dags/eam_slack_channels.py

Change the Jira domain to point to Sandbox 
[Jira ticket ASP-5368](https://mozilla-hub.atlassian.net/browse/ASP-5368)

fix(code):Change jira domain to Sandbox

---

dags/glam_glean_imports.py

Fixes https://github.com/mozilla/glam/issues/2989 by adding a separate step to import build revisions into GLAM's database.
* https://github.com/mozilla/glam/issues/2989

fix(glam): add separate import revisions step

---

dags/bqetl_artifact_deployment.py

Adds a `generate_sql` dag param that will run sql generation at the start of the table, view, and metadata publishing.  Plan is to use this when a run is triggered after schema deploy through https://github.com/mozilla-it/dataservices-infra/pull/345 and https://github.com/mozilla-services/cloudops-infra/pull/5736.
Verified this locally by looking at the rendered templates:
* DENG-2963

feat: DENG-2963 Add optional sql generation to artifact deployment

---

dags/eam_workday_netsuite.py

Add AwsBaseHook function to get AWS the credentials
[Jira ticket ASP-5530](https://mozilla-hub.atlassian.net/browse/ASP-5530)

fix(code): Use AwsBaseHook to get AWS the credentials

---

dags/eam_workday_netsuite.py

Fix the docker-etl script name
[Jira ticket ASP-5530](https://mozilla-hub.atlassian.net/browse/ASP-5530)

fix(code):Fix the docker-etl script name

---

utils/gcp.py

This should fix the Airflow failures of missing Bigeye API keys

Set Bigeye API key

---

utils/gcp.py

Follow-up to https://github.com/mozilla/telemetry-airflow/pull/2123. Move the secret into the right utils method

Fix: Use Bigeye API key in bigquery_bigeye_check

---

dags/looker.py

This adds a new task to run LookML validation on spoke-default. This will hopefully detect cases earlier where LookML is causing errors and prevents changes from being made. Currently, often these issues are detected by Looker developers when they try to make a change but can't
There is a chance that this PR might get reverted. We previously tried using `spectacles` for LookML validation in CI but ran into timeout issues (though there validation was running on the PR branch).

feat(looker): Add LookML validation task

---

dags/copy_deduplicate.py

chore: remove main archive step

---

dags/glam_fenix.py
dags/glam_fog.py
dags/glam_glean_imports.py

This PR removes tasks that import `user_counts`. These imports have been irrelevant since GLAM stopped using separate counts [here](https://github.com/mozilla/glam/pull/1876/files#r1887675292)

chore(glam): Remove useless export/import user_counts tasks from glam_fog and glam_fenix

---

dags/taar_daily.py
dags/taar_weekly.py

https://mozilla-hub.atlassian.net/browse/DENG-7245

chore(taar): DENG-7245 pause TAAR jobs

---

dags/eam_workday_netsuite.py

Fix secret names in the DAG script
[ASP-6006](https://mozilla-hub.atlassian.net/browse/ASP-6006)
[ASP-6006]: https://mozilla-hub.atlassian.net/browse/ASP-6006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(code): Workday/Netsuite - Fix secret names

---

dags/eam_workday_netsuite.py

Change cron schedule to 12:AM EST every weekday
[ASP-6093](https://mozilla-hub.atlassian.net/browse/ASP-6093)
[ASP-6093]: https://mozilla-hub.atlassian.net/browse/ASP-6093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(code): [Workday/NetSuite Integration]: Change cron schedule to 12:AM EST every weekday

---

dags/eam_workday_netsuite.py

Change the cron schedule to 12:AM PST every weekday  
[ASP-6093](https://mozilla-hub.atlassian.net/browse/ASP-6093)
[ASP-6093]: https://mozilla-hub.atlassian.net/browse/ASP-6093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(code): [Workday/Netsuite]Change schedule to 12:00 AM PST

---

dags/bqetl_backfill_complete.py

fix(backfill): Fix bqetl_backfill_complete emails

---

utils/glam_subdags/extract.py

This PR replaces the glam etl bucket name with the GCPV2 one. 
* DENG-8296

chore: update GLAM etl bucket name to v2

---

dags/copy_deduplicate.py

Copy dedupe for firefox desktop metrics costs nearly 2x more than for main_v5 even though metrics ping is smaller ([graph](https://sql.telemetry.mozilla.org/queries/107357/source#263833)).  main_v5 copy dedupe is split into 20 jobs so this changes the metrics job into 24 jobs to see if that reduces overall cost
* DENG-8335

chore(copy_dedup): [DENG-8335] Run firefox_desktop.metrics copy_dedup in hourly slices

---

dags/partybal.py

Adds triage notes for `partybal` DAG

chore: Add triage notes for partybal

---

dags/merino_jobs.py

- This PR updates the `merino_jobs` Airflow DAG to create one `TaskGroup` per supported language for wikipedia. Each group contains three language-specific tasks:
- copy-export — downloads the latest CirrusSearch dump for the language
- build-index-staging — indexes to the staging Elasticsearch cluster
- build-index-prod — indexes to the production Elasticsearch cluster
Changes:
- Introduced a `TaskGroup` per language using SUPPORTED_LANGUAGES = ["en", "fr", "de", "it", "pl"]
- Each group includes:
- wikipedia_indexer_copy_export_<lang>
- wikipedia_indexer_build_index_staging_<lang>
- wikipedia_indexer_build_index_prod_<lang>
- Set task dependencies within each group: copy_export >> [index_staging, index_prod]
- Removed previously single-task implementation for copy and indexing
* …

Add Per-Language TaskGroups for Merino Wikipedia Indexing Job

---

dags/webcompat_kb.py

Add web-features dataset id to webcompat_kb command

---

operators/gcp_container_operator.py

This is a workaround for an upstream operator bug which is causing re-running successful `GKEPodOperator` tasks with `reattach_on_restart` enabled to not actually start a new pod if a pod from a previous successful try exists.
* DENG-8670: Clearing Airflow GKE pod operator tasks with `reattach_on_restart` enabled won't re-run the task's logic if a pod from a previous successful try exists

fix: Have `GKEPodOperator` delete succeeded pods to avoid an upstream operator bug (DENG-8670)

---

dags/webcompat_kb.py

Add standards positions dataset to webcompat_kb command line

---

dags/webcompat_kb.py

chore: Add Chrome use counter dataset to webcompat_kb configuration

---

dags/glam_fenix.py
dags/glam_fog.py

Uses `external_task_group_id` for release ExternalTaskSensor.
And some formatting.
* DENG-9214

fix(glam): properly wait on glam_fog and glam_fenix TaskGroups

---

dags/glam_fenix.py
dags/glam_fog.py

Follows https://github.com/mozilla/telemetry-airflow/pull/2230, since that PR didn't do anything.

fix(glam): Try waiting on Done task instead of TaskGroup
